import type { Explanation } from './explainability';

const entries: Explanation[] = [
  { key:'posterior-probability', title:'Posterior Probability', meaning:'The updated probability after the engine combines prior expectations with the latest available evidence.', lookFor:'BUY, SELL and WAIT probabilities, how concentrated they are, and whether calibration supports that confidence level.', think:'It answers “after seeing the current evidence, how should our probabilities change?” It is still a probability, not a guarantee.', aliases:['posterior','posterior probability','bayesian posterior'] },
  { key:'posterior-peak', title:'Posterior Peak', meaning:'The largest probability among the competing BUY, SELL and WAIT outcomes.', lookFor:'Whether the peak is meaningfully larger than the alternatives and whether its calibration is reliable.', think:'A 52% peak is a weak preference. An 80% peak is stronger, but only if historical calibration supports probabilities that high.', aliases:['posterior peak'] },
  { key:'governance-veto', title:'Governance Veto', meaning:'A hard safety rule that blocks an otherwise directional idea because a research, consistency, concentration or quality condition failed.', lookFor:'The exact veto reason and whether it is a data problem, cross-pair conflict, portfolio concentration issue or insufficient evidence.', think:'A veto does not necessarily mean the direction is wrong. It means the system does not consider the decision safe enough to pass its research standards.', aliases:['governance veto','vetoes','veto'] },
  { key:'contradictions', title:'Contradicting Evidence', meaning:'Evidence that points against the current preferred market direction.', lookFor:'How many contradictions exist, how severe they are and whether they come from independent evidence families.', think:'Good research preserves opposing evidence instead of hiding it. A strong idea can survive small contradictions, but severe independent contradictions should reduce conviction.', aliases:['contradictions','opposing evidence','contradictory evidence'] },
  { key:'expectation-gap', title:'Expectation Gap', meaning:'The difference between what the economic evidence suggests and what the market appears to have already priced.', lookFor:'Whether the market is underpricing, fairly pricing or overpricing the fundamental expectation.', think:'Markets move most when reality differs from what was expected. A good macro view can have little edge if everyone has already priced it.', aliases:['expectation gap','pricing gap'] },
  { key:'primary-score', title:'Primary Score', meaning:'The first-pass directional score before the deeper governance and contradiction layers adjust it.', lookFor:'How far it is from zero and how much the refined score changes afterward.', think:'Treat the primary score as the starting hypothesis, not the final answer.', aliases:['primary score','primary'] },
  { key:'refined-score', title:'Refined Score', meaning:'The directional score after additional evidence, contradictions, risk and governance adjustments.', lookFor:'Whether refinement strengthens, weakens or flips the original signal.', think:'A large change from primary to refined tells you the second-pass evidence materially changed the thesis.', aliases:['refined score','refined'] },
  { key:'dynamic-threshold', title:'Dynamic Decision Threshold', meaning:'The minimum strength required before the engine allows a directional decision in the current environment.', lookFor:'Whether the threshold rises during uncertainty, structural breaks, event risk or weak evidence.', think:'Harder environments should require stronger evidence. A dynamic threshold makes the engine more selective when conditions are unreliable.', aliases:['dynamic threshold','threshold'] },
  { key:'independent-evidence', title:'Independent Evidence', meaning:'Supporting information that comes from genuinely different underlying sources or mechanisms rather than duplicates of the same fact.', lookFor:'Independence ratio, effective evidence count and cross-domain confirmation.', think:'Five independent confirmations are much stronger than five websites repeating one original release.', aliases:['independent evidence','evidence independence','independence ratio'] },
  { key:'scenario-robustness', title:'Scenario Robustness', meaning:'How consistently the decision survives alternative plausible macro scenarios or stress assumptions.', lookFor:'Number of scenario matches, flips, WAIT outcomes and the robustness score.', think:'A decision that flips under a tiny assumption change is fragile. A robust decision survives several reasonable alternatives.', aliases:['scenario robustness'] },
  { key:'turning-point-risk', title:'Turning-Point Risk', meaning:'The risk that an economic or market trend is near a reversal or major change in direction.', lookFor:'Slope reversals, acceleration changes, breadth of turning indicators and catalyst timing.', think:'Trend-following evidence becomes less reliable near turning points, so confidence should usually be reduced.', aliases:['turning point risk','turning-point risk'] },
  { key:'catalyst-density', title:'Catalyst Density', meaning:'How concentrated important scheduled events are around the current decision window.', lookFor:'Number of high-impact events, time gaps between them and whether several affect the same currency.', think:'Dense event schedules create more opportunities for the information set to change quickly and can make a static forecast less stable.', aliases:['catalyst density'] },
  { key:'causal-chain', title:'Causal Transmission Chain', meaning:'The sequence linking macro causes to market effects, for example inflation → policy expectations → yields → currency response.', lookFor:'How many nodes are verified, which are missing and whether the observed nodes align or oppose the thesis.', think:'A prediction is stronger when the expected transmission mechanism is actually visible in the market rather than assumed.', aliases:['causal chain','causal transmission'] },
  { key:'counterfactual', title:'Counterfactual Test', meaning:'A “what would need to change for us to be wrong?” stress test of the current thesis.', lookFor:'Minimum adverse shift, weakest components and the explicit conditions that would change the engine’s mind.', think:'Good decisions are falsifiable. If nothing could ever change the conclusion, the model is not testing itself properly.', aliases:['counterfactual','counterfactual stress','fragility'] },
  { key:'temporal-evidence', title:'Temporal Evidence', meaning:'Evidence about timing, including recent releases, revisions, communications and proximity to upcoming catalysts.', lookFor:'Conflicts between old and new information and whether the evidence is still relevant to the chosen horizon.', think:'Correct information used at the wrong time can still produce a bad decision.', aliases:['temporal evidence'] },
  { key:'historical-calibration', title:'Historical Calibration', meaning:'A comparison between model confidence and the realized outcomes of past similar decisions.', lookFor:'Sample size, hit rate, Brier score and whether performance is stable across horizons and regimes.', think:'Historical calibration tells you whether the model has earned the confidence level it is currently displaying.', aliases:['history calibration','historical calibration'] },
  { key:'execution-gate', title:'Execution Gate', meaning:'The final state that determines whether a directional research conclusion is allowed to progress toward an actionable setup.', lookFor:'PASS, WAIT or veto reasons and whether risk controls have already reduced confidence.', think:'A directional thesis and permission to act are two different decisions.', aliases:['execution gate'] },
  { key:'thesis', title:'Investment / Trading Thesis', meaning:'The concise causal explanation for why the engine currently prefers a direction.', lookFor:'Primary drivers, opposing evidence, assumptions and invalidation conditions.', think:'A useful thesis should explain cause and effect, not merely say that a score is high.', aliases:['decision thesis','thesis statement','thesis'] },
  { key:'counter-thesis', title:'Counter Thesis', meaning:'The strongest reasonable explanation for why the current preferred view could be wrong.', lookFor:'Whether the counter thesis is supported by independent data and what evidence would make it dominant.', think:'Actively representing the opposing case reduces confirmation bias.', aliases:['counter thesis','counter-thesis'] },
  { key:'invalidation', title:'Invalidation Condition', meaning:'A predefined condition that tells the engine its current thesis is no longer valid.', lookFor:'Concrete observable conditions rather than vague statements.', think:'Invalidation protects against endlessly defending a view after the evidence changes.', aliases:['invalidation','invalidations'] },
  { key:'premortem', title:'Pre-Mortem', meaning:'A structured exercise that assumes the decision failed and asks what most likely caused the failure.', lookFor:'Specific risks, severity, failure conditions and planned responses.', think:'Thinking about failure before it happens exposes blind spots that confidence scores may miss.', aliases:['pre-mortem','premortem'] },
  { key:'confidence-haircut', title:'Confidence Haircut', meaning:'A deliberate reduction in model confidence because a known risk or quality weakness is present.', lookFor:'Which risk caused the haircut and how many percentage points were removed.', think:'The direction can remain unchanged while the appropriate confidence falls.', aliases:['confidence haircut','haircut'] },
  { key:'source-live', title:'Live Source', meaning:'A source currently delivering usable information through the active collection path.', lookFor:'Freshness, successful retrieval and whether it is a primary or fallback source.', think:'Live describes operational state, not automatic truth. Reliability and provenance still matter.', aliases:['source live','live source'] },
  { key:'source-fallback', title:'Fallback Source', meaning:'A backup information path used when the preferred primary source is unavailable or incomplete.', lookFor:'Why fallback was required, age of the fallback evidence and whether values agree with independent sources.', think:'Fallback is better than fabricating data, but it should normally carry a confidence or freshness penalty.', aliases:['fallback source','fallback'] },
  { key:'metadata-only', title:'Metadata-Only Source', meaning:'A source registered in the research universe for reference or provenance but not actively collected for protected or inaccessible content.', lookFor:'Whether the dashboard clearly distinguishes metadata registration from live evidence.', think:'Being listed as a research source does not mean its current content was used in a live decision.', aliases:['metadata only','metadata-only'] },
  { key:'registered-source', title:'Registered Source', meaning:'A source known to the research network but not necessarily active in the current collection cycle.', lookFor:'Its current mode: live, fallback, registered or metadata only.', think:'Registration represents coverage intent, not proof that data from the source influenced the present signal.', aliases:['registered source','registered'] },
  { key:'decision-confidence', title:'Decision Confidence', meaning:'The final confidence assigned after model probabilities, evidence quality, contradictions, risk and governance adjustments.', lookFor:'Calibration, evidence strength, uncertainty and the difference between raw and post-risk confidence.', think:'Confidence is a measured degree of belief. It should rise only when evidence and historical calibration justify it.', aliases:['final confidence','confidence'] },
  { key:'signal-score', title:'Directional Signal Score', meaning:'A signed score summarizing whether the combined evidence leans bullish or bearish.', lookFor:'Magnitude, threshold, stability and whether the score agrees with calibrated probability.', think:'The sign gives direction and magnitude gives strength, but the score should never be read without quality and uncertainty.', aliases:['signal score','directional score'] },
  { key:'risk-decomposition', title:'Risk Decomposition', meaning:'A breakdown showing which separate risk families are reducing the reliability of the current decision.', lookFor:'The largest risk score, active warnings and confidence haircuts.', think:'Separating risks makes it clear whether weakness comes from events, liquidity, model uncertainty, structure or another cause.', aliases:['risk decomposition'] },
  { key:'scenario-analysis', title:'Scenario Analysis', meaning:'A controlled test of how conclusions would change under alternative macro shocks or assumptions.', lookFor:'Direction flips, confidence changes and assets or currencies that behave differently across scenarios.', think:'Scenario analysis is not a prediction that every scenario will happen. It measures fragility and conditional behaviour.', aliases:['scenario analysis','stress laboratory'] },
  { key:'release-memory', title:'Release Memory', meaning:'Historical records of how economic surprises and similar events behaved in the past.', lookFor:'Number of observations, surprise magnitude, bullish/bearish rates and regime dependence.', think:'Release memory provides empirical context, but older events should not override evidence that the regime has changed.', aliases:['release memory','surprise profile'] },
  { key:'econometric-ensemble', title:'Econometric Ensemble', meaning:'A combination of several statistical forecasting approaches rather than relying on one model.', lookFor:'Model weights, agreement, dispersion, walk-forward errors and calibration.', think:'Ensembles can be more stable than individual models, but only if diversity is real and weak models are controlled.', aliases:['econometric ensemble','model ensemble','ensemble'] },
];

const normalize=(value:string)=>value.toLowerCase().replace(/[↑↓×·:()/%+]/g,' ').replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim();

export function resolveDecisionExplanation(text:string): Explanation|null{
  const normalized=normalize(text);
  if(!normalized)return null;
  const matches=entries.flatMap(item=>[item.key,item.title,...(item.aliases??[])].map(alias=>({item,alias:normalize(alias)})))
    .filter(({alias})=>alias.length>=3&&normalized.includes(alias))
    .sort((a,b)=>b.alias.length-a.alias.length);
  return matches[0]?.item??null;
}

export const DECISION_EXPLANATIONS=entries;
