import { QUALITY_FAMILIES } from './quality-framework';

export type Explanation = {
  key: string;
  title: string;
  meaning: string;
  lookFor: string;
  think: string;
  good?: string;
  warning?: string;
  formula?: string;
  aliases?: string[];
};

const core: Explanation[] = [
  { key:'fxga-quality-score', title:'FXGA Quality Score', meaning:'A combined research-health score. It summarizes whether the data, calibration, evidence, robustness and governance are strong enough to trust the analytical output.', lookFor:'Prefer a high score that is supported by strong calibration and evidence, not just strong raw data.', think:'Treat it as a permission layer. A directional forecast can look attractive, but weak quality means the conclusion should carry less weight.', good:'70 or higher with no weak pillar is generally a healthier state.', warning:'A high headline score should not override a very weak calibration or evidence pillar.', formula:'Weighted geometric combination of data quality, calibration, evidence, robustness and governance.' },
  { key:'data-quality', title:'Data Quality', meaning:'How complete, fresh, plausible and internally consistent the information feeding the research engine is.', lookFor:'Coverage, freshness, unresolved series, anomalies, source failures and stale observations.', think:'Bad input can make a sophisticated model look confident for the wrong reason. Quality comes before prediction.', good:'High coverage, low anomaly rates and few unresolved critical series.', warning:'Missing or stale high-impact data should reduce confidence.' },
  { key:'calibration', title:'Calibration Quality', meaning:'Whether probabilities stated by the model match what actually happens over many historical decisions.', lookFor:'Brier score, hit rate by probability bucket, calibration confidence and enough realized samples.', think:'If a model says 70% many times, roughly seven out of ten comparable cases should succeed. Calibration tests that honesty.', good:'Probability buckets closely match realized frequencies and stay stable out of sample.', warning:'A model can have a high hit rate but still be badly calibrated if its probabilities are exaggerated.' },
  { key:'evidence-quality', title:'Evidence Quality', meaning:'How strong, independent, fresh and complete the supporting information behind a conclusion is.', lookFor:'Independent sources, missing mandatory evidence, contradictions and whether the evidence is direct or merely derived.', think:'Ten copies of the same fact are not ten independent confirmations. Diversity and independence matter.', good:'Several independent evidence families point in the same direction with little critical missing data.', warning:'Strong consensus built from duplicated or correlated sources can create false confidence.' },
  { key:'robustness', title:'Robustness', meaning:'How well the conclusion survives changes in assumptions, samples, regimes, parameters and data conditions.', lookFor:'Model agreement, dispersion, structural-break risk, regime stability and sensitivity tests.', think:'A robust result should not disappear because one parameter, one source or one short time window changes slightly.', good:'Different reasonable methods reach similar conclusions.', warning:'A signal that depends on one fragile assumption should be treated cautiously.' },
  { key:'governance', title:'Governance & Reproducibility', meaning:'The controls that make a decision traceable to a specific data vintage, code version, source set and validation state.', lookFor:'Versioning, immutable snapshots, checksums, validation state, audit logs and rollback capability.', think:'If a decision cannot be reconstructed later, its reported historical skill is difficult to audit.', good:'Every decision can be reproduced from point-in-time inputs.', warning:'Manual overrides or unversioned transformations weaken auditability.' },
  { key:'registered-methods', title:'Registered Methods', meaning:'The number of quality-control methods defined in the FXGA framework. Registered means the rule exists in the framework, not that live evidence is available for every method at this moment.', lookFor:'Compare registered methods with measured and supported families.', think:'This distinction prevents the dashboard from pretending that an unavailable test has been performed.', warning:'Never interpret registration count as proof of model accuracy.' },
  { key:'measured-families', title:'Fully Measured Families', meaning:'Control families with enough current evidence and confidence to calculate a meaningful live score.', lookFor:'Whether the most important families such as calibration, evidence and data quality are measured.', think:'More measured families means fewer blind spots in the research audit.' },
  { key:'supported-families', title:'Families With Usable Evidence', meaning:'Families that have at least partial live evidence even if they have not reached the threshold for full measurement.', lookFor:'A low supported count indicates large areas where the system cannot yet verify itself.', think:'Partial evidence is useful, but it should not be presented with the certainty of a mature measured sample.' },
  { key:'quality-gate', title:'Decision Quality State', meaning:'A research gate that classifies the current environment as qualified, watch or insufficient before a directional conclusion is trusted.', lookFor:'Why a state is on watch: weak calibration, sparse evidence, structural breaks, stale data or high uncertainty.', think:'The gate answers “are we allowed to trust this decision strongly?” before asking “which direction?”', good:'Qualified with balanced pillar scores.', warning:'Insufficient means the system should abstain or heavily reduce confidence.' },
  { key:'effective coverage', title:'Effective Coverage', meaning:'The share of requested observations that are usable, including current live observations and explicitly retained last-known-good values.', lookFor:'Compare effective coverage with live coverage. A large gap means many values are usable but not newly refreshed.', think:'Useful does not always mean fresh. Retained values should carry a freshness penalty when the market needs current information.' },
  { key:'live coverage', title:'Live Coverage', meaning:'The percentage of requested observations that were freshly retrieved in the current collection cycle.', lookFor:'A sudden drop can indicate provider, authentication, parsing or network problems.', think:'High live coverage is especially important around market-moving releases.' },
  { key:'last-known-good', title:'Last-Known-Good Retained', meaning:'A previously verified observation kept available when a fresh value could not be retrieved.', lookFor:'How old the retained value is and whether that series normally changes frequently.', think:'Retaining a known value is safer than inventing a replacement, but age still matters.' },
  { key:'unresolved series', title:'Unresolved Series', meaning:'Requested macro series that currently have no usable observation.', lookFor:'Whether the missing series is critical to inflation, growth, labour, policy or another active decision.', think:'One missing low-importance series may not matter. One missing central policy input can matter a lot.' },
  { key:'market coverage', title:'Market Coverage', meaning:'How many tracked market instruments currently have usable price information.', lookFor:'Stale quotes, missing asset classes and whether cross-asset confirmations are still independent.', think:'Macro conclusions are stronger when rates, FX, commodities and risk assets can confirm or challenge them.' },
  { key:'structure coverage', title:'Structure Coverage', meaning:'How many tracked assets have enough technical history to classify current market structure.', lookFor:'Confirmed versus warming states.', think:'A warming structure means the engine has not yet accumulated enough evidence to treat the technical state as fully established.' },
  { key:'actual', title:'Actual', meaning:'The value officially released for an economic indicator.', lookFor:'Compare it with consensus, previous and any revision. Direction alone is not enough.', think:'Markets usually react to the surprise relative to expectations, not simply whether the number is high or low.' },
  { key:'dev', title:'Deviation / Surprise', meaning:'A normalized measure of how far the released value differs from the expected consensus.', lookFor:'Magnitude, sign and whether a higher number is positive or negative for the relevant currency in this specific indicator.', think:'A larger surprise can produce a stronger reaction, but positioning and policy regime can reverse the obvious interpretation.', formula:'Typically based on Actual minus Consensus, often normalized by historical forecast error or volatility.' },
  { key:'consensus', title:'Consensus', meaning:'The market or economist expectation before the release.', lookFor:'How dispersed expectations were and whether the market had already moved toward a different unofficial expectation.', think:'Consensus is the benchmark the actual result must beat or miss to create a conventional surprise.' },
  { key:'previous', title:'Previous', meaning:'The previously reported value for the indicator before the current release.', lookFor:'Whether it was revised and whether the trend is accelerating or slowing.', think:'The direction of the series through time can matter as much as one new observation.' },
  { key:'revision', title:'Revision', meaning:'A change to a value that had already been published.', lookFor:'Size, direction and whether the revision changes the historical trend or the interpretation of the current release.', think:'A strong current print can be offset by a large negative revision to the prior period.' },
  { key:'bias confidence', title:'Bias Confidence', meaning:'How strongly the engine supports a bullish, bearish or neutral currency interpretation for a completed release.', lookFor:'The underlying evidence, sample size, calibration and whether different evidence groups agree.', think:'Confidence is not certainty and should be reduced when evidence is stale, contradictory or historically unstable.' },
  { key:'policy repricing', title:'Policy Repricing', meaning:'How market expectations for future central-bank policy have changed relative to the current policy path.', lookFor:'Changes in short-rate expectations, OIS or yield curves and whether base and quote currencies are repricing differently.', think:'FX often reacts to the expected future policy gap, not just today’s policy rate.' },
  { key:'cross asset', title:'Cross-Asset Confirmation', meaning:'Independent evidence from rates, equities, commodities, volatility or other markets that supports or contradicts the main macro view.', lookFor:'Number of usable factors, their freshness and whether they come from genuinely different risk channels.', think:'Cross-asset confirmation is valuable because it checks whether the broader market is transmitting the same macro message.' },
  { key:'release reaction calibration', title:'Release-Reaction Calibration', meaning:'A live adjustment based on how similar past releases actually affected the market after publication.', lookFor:'Sample count, agreement, reversal risk, regime transition risk and the confidence multiplier.', think:'The same economic surprise can behave differently in different regimes. This layer learns from realized reaction patterns.' },
  { key:'evidence completeness', title:'Evidence Completeness', meaning:'The percentage of expected research inputs currently available for a decision.', lookFor:'Mandatory missing inputs first, then optional missing inputs.', think:'Completeness tells you how much of the intended research case is present, not whether that evidence is bullish or bearish.' },
  { key:'structural stability', title:'Structural Stability', meaning:'Whether relationships used by the model still resemble the relationships seen in its historical calibration sample.', lookFor:'Break series, watch series, transition probability and post-break performance.', think:'When structure changes, old backtests can become less informative.' },
  { key:'break risk', title:'Structural Break Risk', meaning:'Estimated risk that an important economic or market relationship has changed enough to invalidate old assumptions.', lookFor:'A rising score, multiple break families and simultaneous regime transitions.', think:'High break risk should lower confidence even when the current directional evidence looks strong.' },
  { key:'decision change', title:'Decision Change', meaning:'How the current decision differs from the prior stored decision for the same instrument.', lookFor:'Direction flips, confidence changes, score deltas and the reasons recorded for the change.', think:'A sudden flip deserves more scrutiny than a stable decision that strengthened gradually.' },
  { key:'historical analogues', title:'Historical Analogues', meaning:'Past market states that were quantitatively similar to the current state.', lookFor:'Similarity, sample count, hit rate and signed market outcome after those states.', think:'Analogues are contextual evidence, not proof. Similar-looking macro states can still resolve differently.' },
  { key:'preferred horizon', title:'Preferred Horizon', meaning:'The forward period where the current model has the strongest combination of calibrated probability and historical evidence.', lookFor:'Sample size and whether other horizons show negative edge.', think:'A view can be right over 24 hours but noisy or wrong over 15 minutes. Horizon matters.' },
  { key:'negative edge', title:'Negative-Edge Horizon', meaning:'A forecast horizon where historical results have been worse than the required benchmark.', lookFor:'Whether the negative edge persists across enough samples.', think:'Do not force one macro view onto every time horizon.' },
  { key:'brier', title:'Brier Score', meaning:'A probability-forecast error score. It penalizes confident forecasts that turn out to be wrong.', lookFor:'Lower is better. Compare it with a simple benchmark and across the same type of forecast.', think:'A Brier score rewards honest probabilities, not just correct direction.', formula:'Mean squared difference between forecast probability and the realized 0/1 outcome.' },
  { key:'hit rate', title:'Hit Rate', meaning:'The percentage of realized decisions that resolved in the predicted direction.', lookFor:'Sample size, regime and horizon. A hit rate without those can be misleading.', think:'A 70% hit rate from ten observations is much weaker evidence than 60% from thousands of comparable observations.' },
  { key:'sample', title:'Sample Size', meaning:'The number of historical observations used to estimate a statistic.', lookFor:'Whether the sample is large enough and representative of the current regime.', think:'Small samples produce unstable percentages. Confidence should increase gradually as evidence accumulates.' },
  { key:'walk-forward', title:'Walk-Forward Validation', meaning:'A historical test that repeatedly trains or calibrates on the past and then evaluates on a later unseen period.', lookFor:'Consistency across windows rather than one excellent period.', think:'This is stronger than fitting and testing on the same historical data because it better approximates real-time use.' },
  { key:'rmse', title:'RMSE', meaning:'Root Mean Squared Error, a measure of typical forecast error that penalizes large misses more heavily.', lookFor:'Lower values relative to comparable models and stability out of sample.', think:'RMSE is useful for magnitude forecasts but does not by itself tell you whether directional probabilities are calibrated.' },
  { key:'model agreement', title:'Model Agreement', meaning:'How closely different models or methods agree on the current forecast.', lookFor:'Agreement together with independence. Closely related models can agree for the same wrong reason.', think:'High agreement reduces model uncertainty only when the models are sufficiently diverse.' },
  { key:'dispersion', title:'Model Dispersion', meaning:'How spread out the model forecasts are.', lookFor:'Sudden increases, especially around regime changes or incomplete data.', think:'Higher dispersion usually means the ensemble is less certain about the current state.' },
  { key:'uncertainty', title:'Forecast Uncertainty', meaning:'The range of plausible outcomes around the central estimate.', lookFor:'Interval width, coverage history and whether uncertainty expands during events or structural breaks.', think:'A wide interval is not a weakness if the world is genuinely uncertain. False precision is worse.' },
  { key:'regime', title:'Macro Regime', meaning:'A classified economic environment such as inflationary, disinflationary, expansionary, contractionary, tightening or easing.', lookFor:'Persistence, transition probability and whether several independent indicators agree.', think:'Relationships between data and markets can change across regimes, so calibration should be regime aware.' },
  { key:'transition', title:'Regime Transition Probability', meaning:'Estimated probability that the current macro state is moving into a different regime.', lookFor:'A rising transition probability across multiple families.', think:'Signals are often less stable near transitions because historical relationships are changing.' },
  { key:'source reliability', title:'Source Reliability', meaning:'A score for how dependable a provider has been based on availability, freshness, history, anomalies and successful collection.', lookFor:'Persistent failures, stale values, frequent fallback and sudden deterioration.', think:'A source can be official and still temporarily fail operationally, so authority and live reliability are both relevant.' },
  { key:'freshness', title:'Freshness', meaning:'How recent the current evidence is relative to how quickly that type of information normally changes.', lookFor:'Age versus expected release frequency and whether the evidence is inside a market-sensitive event window.', think:'A monthly macro observation can remain valid for weeks. A live market quote can become stale in seconds. Freshness must be context aware.' },
  { key:'risk state', title:'Portfolio Risk State', meaning:'A summary of event, liquidity, volatility and other risks that can reduce confidence in otherwise valid signals.', lookFor:'The highest risk categories and the confidence haircut they impose.', think:'Risk controls do not necessarily change the predicted direction. They change how aggressively that prediction should be trusted or acted on.' },
  { key:'confidence after risk', title:'Confidence After Risk Controls', meaning:'The model confidence remaining after event, structural, liquidity, uncertainty and other risk haircuts are applied.', lookFor:'How much confidence was removed and which risk family caused it.', think:'This is usually more decision relevant than raw model confidence.' },
  { key:'slo', title:'Service-Level Objective', meaning:'A measurable reliability target for the data or research service.', lookFor:'Target percentage, measurement window and error budget.', think:'SLOs turn operational reliability into something that can be monitored objectively.' },
  { key:'error budget', title:'Error Budget', meaning:'The amount of failure or unreliability allowed while still meeting an SLO.', lookFor:'How quickly the budget is being consumed.', think:'A nearly exhausted error budget means the system should prioritize reliability over new changes.' },
  { key:'high impact', title:'High-Impact Event', meaning:'An economic or policy event expected to have a comparatively large potential market effect.', lookFor:'Time to release, affected currency, consensus uncertainty and current positioning.', think:'Impact is potential, not guaranteed direction. The surprise and market context determine the reaction.' },
  { key:'buy', title:'BUY Direction', meaning:'The engine currently expects the base asset or currency pair to have positive directional edge over the stated horizon.', lookFor:'Calibrated probability, evidence quality, risk gate and invalidation conditions.', think:'BUY is a model conclusion, not certainty. It should be strongest when independent evidence and calibration agree.' },
  { key:'sell', title:'SELL Direction', meaning:'The engine currently expects the base asset or currency pair to have negative directional edge over the stated horizon.', lookFor:'Calibrated probability, evidence quality, risk gate and invalidation conditions.', think:'SELL is a model conclusion, not certainty. Contradictory evidence and weak calibration should reduce conviction.' },
  { key:'wait', title:'WAIT / Abstain', meaning:'The engine is deliberately refusing a directional call because evidence, calibration, edge or risk conditions are insufficient.', lookFor:'Which quality gate caused the abstention.', think:'WAIT is a valid research outcome. A system that can abstain is safer than one forced to predict every situation.' },
];

const familyExplanations: Explanation[] = QUALITY_FAMILIES.map((family) => ({
  key: family.id,
  title: family.label,
  meaning: family.description,
  lookFor: `Check the live family score, confidence, evidence count and whether the family is measured, partially supported, registered only or gated.`,
  think: `This family contains 50 registered controls. The dashboard does not claim all 50 are measured unless the required evidence is available.`,
  aliases: [family.label, family.shortLabel],
}));

export const EXPLANATIONS: Explanation[] = [...core, ...familyExplanations];

function normalize(value: string) {
  return value.toLowerCase().replace(/[↑↓×·:()/%+]/g, ' ').replace(/[_-]+/g, ' ').replace(/\s+/g, ' ').trim();
}

export function resolveExplanation(explicitKey: string | null | undefined, text: string): Explanation | null {
  if (explicitKey) {
    const explicit = EXPLANATIONS.find((item) => item.key === explicitKey);
    if (explicit) return explicit;
  }
  const normalized = normalize(text);
  if (!normalized) return null;
  const candidates = EXPLANATIONS.flatMap((item) => [item.key, item.title, ...(item.aliases ?? [])].map((alias) => ({ item, alias: normalize(alias) })))
    .filter(({ alias }) => alias.length >= 3 && normalized.includes(alias))
    .sort((a, b) => b.alias.length - a.alias.length);
  return candidates[0]?.item ?? null;
}

export function genericExplanation(text: string): Explanation {
  const clean = text.replace(/\s+/g, ' ').trim().slice(0, 90) || 'Dashboard information';
  return {
    key: 'generic-context',
    title: clean,
    meaning: 'This is a live dashboard value or research label. Its meaning depends on the surrounding unit, timestamp, source and comparison being shown.',
    lookFor: 'Check whether the value is current, what it is being compared with, how large the sample is and whether the relevant quality or evidence controls are healthy.',
    think: 'Do not judge one number in isolation. Read it together with direction, history, uncertainty, evidence quality and the current macro regime.',
    warning: 'A number without context, units, source quality or timing can be easy to misinterpret.',
  };
}
