import type { Explanation } from './explainability';

const entries: Explanation[] = [
  { key:'gdp', title:'GDP / Economic Growth', meaning:'Gross Domestic Product measures the value of goods and services produced by an economy. It is one of the broadest measures of economic activity.', lookFor:'Growth versus the previous quarter/year, revisions, real versus nominal growth and whether growth is accelerating or slowing.', think:'Stronger growth can support a currency if it raises expected interest rates, but very strong growth can also increase inflation risk.', aliases:['gross domestic product','real gdp','economic growth'] },
  { key:'cpi', title:'CPI Inflation', meaning:'The Consumer Price Index tracks changes in prices paid by households for a basket of goods and services.', lookFor:'Headline versus core CPI, monthly momentum, annual rate, shelter/services inflation and the surprise versus consensus.', think:'Persistent upside inflation surprises usually make rate cuts less likely or rate hikes more likely, which can support the currency through yields.', aliases:['consumer price index','headline cpi','inflation rate'] },
  { key:'core-cpi', title:'Core CPI', meaning:'Core CPI removes especially volatile categories, commonly food and energy, to reveal underlying inflation pressure.', lookFor:'Monthly core momentum and whether services inflation is broad or narrowing.', think:'Central banks often care about persistent underlying inflation more than one volatile headline move.', aliases:['core inflation'] },
  { key:'pce', title:'PCE Inflation', meaning:'Personal Consumption Expenditures inflation is a broad US inflation measure. The Federal Reserve closely follows the core PCE measure.', lookFor:'Core PCE monthly momentum, revisions and whether it is converging toward the Fed target.', think:'Unexpectedly persistent core PCE can push expected Fed easing further into the future.', aliases:['personal consumption expenditures','core pce','pce price index'] },
  { key:'ppi', title:'Producer Price Inflation', meaning:'PPI measures price changes received by producers. It can provide information about cost pressure earlier in the production chain.', lookFor:'Core components, pipeline pressures and whether producer inflation is feeding into consumer inflation.', think:'PPI matters most when it changes the expected path of consumer inflation or corporate margins.', aliases:['producer price index'] },
  { key:'unemployment', title:'Unemployment Rate', meaning:'The share of the labour force that is actively looking for work but does not currently have a job.', lookFor:'The trend, participation rate, payroll growth, hours worked and whether unemployment is rising quickly.', think:'A rapidly rising unemployment rate can signal weakening demand and increase the probability of easier monetary policy.', aliases:['jobless rate','unemployment'] },
  { key:'payrolls', title:'Nonfarm Payrolls / Employment Growth', meaning:'A major US labour report measuring the change in paid employment outside several excluded sectors such as farming.', lookFor:'Headline jobs, prior revisions, unemployment, wages, participation and average weekly hours together.', think:'One strong payroll number is less convincing if previous months are revised sharply lower or unemployment rises.', aliases:['nonfarm payrolls','nfp','payroll employment','employment change'] },
  { key:'wages', title:'Wage Growth', meaning:'Measures how quickly worker pay is increasing.', lookFor:'Monthly and annual growth, private-sector trends and whether wage growth is consistent with the inflation target.', think:'Fast wage growth can sustain services inflation; slowing wages can reduce inflation pressure without requiring a recession.', aliases:['average hourly earnings','earnings growth','labour cost'] },
  { key:'jobless-claims', title:'Jobless Claims', meaning:'Claims for unemployment benefits provide a relatively high-frequency view of labour-market layoffs.', lookFor:'Initial claims, continuing claims and the multi-week trend rather than one noisy observation.', think:'A sustained rise can signal labour weakening before slower monthly reports fully show it.', aliases:['initial claims','continuing claims','unemployment claims'] },
  { key:'jolts', title:'JOLTS / Job Openings', meaning:'The US Job Openings and Labor Turnover Survey measures vacancies, hiring, quits and separations.', lookFor:'Job openings relative to unemployed workers, quits rate and hiring rate.', think:'Falling vacancies with limited layoffs can indicate labour-market rebalancing rather than recession.', aliases:['job openings','jolts'] },
  { key:'pmi', title:'PMI Business Survey', meaning:'Purchasing Managers’ Index surveys businesses about activity such as output, new orders, employment and prices.', lookFor:'50 is the common expansion/contraction dividing line, but the direction and rate of change also matter.', think:'PMIs are timely. Markets often use them to anticipate harder official data.', aliases:['purchasing managers index','manufacturing pmi','services pmi','composite pmi'] },
  { key:'ism', title:'ISM Survey', meaning:'A widely followed US business survey covering manufacturing or services conditions.', lookFor:'Headline index, new orders, employment and prices-paid components.', think:'New orders and prices can provide early information about growth and inflation direction.', aliases:['ism manufacturing','ism services','ism prices paid'] },
  { key:'retail-sales', title:'Retail Sales', meaning:'Measures spending at retailers and is an important signal of household demand.', lookFor:'Control-group sales, revisions and whether gains are price-driven or volume-driven.', think:'Consumption is a major component of many economies, so persistent retail strength can keep growth and inflation firmer.', aliases:['retail sales','consumer spending'] },
  { key:'industrial-production', title:'Industrial Production', meaning:'Tracks output from factories, mines and utilities.', lookFor:'Manufacturing output, capacity utilization and the trend across several months.', think:'It is a cyclical indicator that can confirm or contradict business surveys.', aliases:['manufacturing production','factory output'] },
  { key:'housing', title:'Housing Activity', meaning:'Housing indicators track construction, transactions and affordability in the property sector.', lookFor:'Starts, permits, sales, mortgage rates, inventories and price momentum.', think:'Housing is interest-rate sensitive, so it can show the effect of monetary policy relatively early.', aliases:['housing starts','building permits','home sales','house prices'] },
  { key:'consumer-confidence', title:'Consumer Confidence', meaning:'Survey measures of how households feel about current and future economic conditions.', lookFor:'Expectations versus current conditions and whether sentiment changes are reflected in actual spending.', think:'Confidence can lead spending, but surveys can also diverge from real behaviour.', aliases:['consumer sentiment','confidence index','michigan sentiment'] },
  { key:'business-confidence', title:'Business Confidence', meaning:'Surveys of companies about demand, investment, employment or future activity.', lookFor:'New orders, investment plans, hiring intentions and price expectations.', think:'Business surveys are useful early signals but should be confirmed by actual production and spending data.', aliases:['business sentiment','business conditions'] },
  { key:'trade-balance', title:'Trade Balance', meaning:'Exports minus imports of goods and services.', lookFor:'Whether changes come from export strength, import weakness, commodity prices or domestic demand.', think:'A stronger trade balance can support a currency, but the reason for the improvement matters.', aliases:['trade deficit','trade surplus','balance of trade'] },
  { key:'current-account', title:'Current Account', meaning:'A broader external-balance measure covering trade plus income and transfers between a country and the rest of the world.', lookFor:'Deficit sustainability and how it is financed.', think:'Large persistent external deficits can increase sensitivity to foreign capital flows.', aliases:['current account balance'] },
  { key:'money-supply', title:'Money Supply', meaning:'Measures such as M1 or M2 approximate money and highly liquid deposits available in the economy.', lookFor:'Growth rate, real money growth and whether changes reflect policy, credit creation or unusual deposit shifts.', think:'Money growth can matter for liquidity and inflation, but the relationship changes across regimes.', aliases:['m1','m2','broad money','money growth'] },
  { key:'credit-growth', title:'Credit Growth', meaning:'Measures how quickly lending to households, businesses or governments is expanding.', lookFor:'Private credit, lending standards, delinquencies and real credit growth.', think:'Credit expansion can support growth, while tightening lending can transmit restrictive monetary policy.', aliases:['bank lending','loans','credit conditions'] },
  { key:'policy-rate', title:'Central Bank Policy Rate', meaning:'The benchmark short-term interest rate set or targeted by a central bank.', lookFor:'The current rate, expected future path, vote split, guidance and inflation/growth forecasts.', think:'FX reacts strongly to differences between what a central bank is expected to do and what markets had already priced.', aliases:['fed funds rate','bank rate','repo rate','cash rate','interest rate decision','policy interest rate'] },
  { key:'rate-cut', title:'Rate Cut', meaning:'A central bank lowers its policy rate.', lookFor:'Whether the cut was expected, the size, guidance about future cuts and the reason for easing.', think:'An expected cut may have little effect. A surprise or a more dovish future path can weaken the currency through lower yields.', aliases:['interest rate cut','easing'] },
  { key:'rate-hike', title:'Rate Hike', meaning:'A central bank raises its policy rate.', lookFor:'Whether it was priced, the vote, guidance and whether inflation risk remains elevated.', think:'Unexpectedly hawkish policy can support a currency, but recession fears can complicate the reaction.', aliases:['interest rate hike','tightening'] },
  { key:'yield', title:'Bond Yield', meaning:'The annualized return implied by the price of a government or corporate bond.', lookFor:'2-year versus 10-year yields, real yields and whether moves come from growth, inflation or policy expectations.', think:'Currencies often respond to changes in relative yields between countries rather than to one yield in isolation.', aliases:['treasury yield','government bond yield','gilt yield','bund yield','jgb yield'] },
  { key:'real-yield', title:'Real Yield', meaning:'A yield adjusted for expected inflation, approximating the real return investors receive.', lookFor:'Real-yield differentials across countries and changes around policy or inflation news.', think:'Higher real yields can support a currency and can pressure non-yielding assets such as gold, all else equal.', aliases:['real interest rate','inflation adjusted yield'] },
  { key:'yield-curve', title:'Yield Curve', meaning:'The relationship between interest rates on bonds with different maturities.', lookFor:'Slope between short and long maturities, inversions, steepening and whether the move is driven by the front end or long end.', think:'Curve shape contains information about policy expectations, growth and inflation risk.', aliases:['curve steepening','curve inversion','2s10s','10y2y'] },
  { key:'spread', title:'Interest-Rate / Yield Spread', meaning:'The difference between two rates or yields.', lookFor:'Which two instruments are being compared and whether the spread is widening or narrowing.', think:'For FX, relative rate spreads can approximate the changing return advantage of holding one currency over another.', aliases:['rate differential','yield differential','interest differential'] },
  { key:'inflation-expectations', title:'Inflation Expectations', meaning:'Market or survey estimates of future inflation.', lookFor:'Short-term versus long-term expectations and whether they remain anchored near the central-bank target.', think:'Rising expectations can push nominal yields higher and make policymakers more cautious about easing.', aliases:['breakeven inflation','5y5y','inflation expectation'] },
  { key:'central-bank-guidance', title:'Central Bank Guidance', meaning:'Statements that communicate how policymakers are thinking about future rates and risks.', lookFor:'Changes in language, balance of risks, conditionality and disagreement among policymakers.', think:'Future guidance can move markets more than the current rate decision when the rate itself was fully expected.', aliases:['forward guidance','monetary policy statement','central bank speech'] },
  { key:'dxy', title:'US Dollar Index', meaning:'An index measuring the US dollar against a basket of major currencies.', lookFor:'Broad dollar direction and whether individual pairs confirm the move.', think:'DXY is useful for broad USD context but its basket weights mean it is heavily influenced by EUR and other major currencies.', aliases:['dollar index','us dollar index'] },
  { key:'vix', title:'VIX Volatility Index', meaning:'A market measure derived from S&P 500 options that reflects expected near-term equity volatility.', lookFor:'Rapid spikes, persistence and confirmation from credit spreads or safe-haven assets.', think:'Higher VIX often signals risk aversion, but the FX response depends on funding flows and the specific regime.', aliases:['volatility index','fear index'] },
  { key:'gold', title:'Gold', meaning:'A globally traded precious metal influenced by real yields, the US dollar, inflation expectations, risk aversion and central-bank demand.', lookFor:'Real yields, DXY, geopolitical stress and whether gold is confirming or diverging from rates.', think:'Gold has no coupon, so rising real yields can be a headwind, while falling real yields or risk stress can support it.', aliases:['xauusd','xau'] },
  { key:'oil', title:'Crude Oil', meaning:'A major global commodity whose price reflects supply, demand, inventories, geopolitics and global growth.', lookFor:'Brent/WTI direction, inventories, OPEC policy and whether the move is supply-driven or demand-driven.', think:'Oil affects inflation and can have different currency effects for oil exporters versus importers.', aliases:['wti','brent','crude oil'] },
  { key:'equities', title:'Equity Market', meaning:'Shares in companies. Broad equity indices are often used as a real-time indicator of risk appetite and growth expectations.', lookFor:'Breadth, sector leadership, earnings expectations, yields and volatility.', think:'A rising index is not always pure “risk on”; sometimes a few large companies dominate the move.', aliases:['stocks','s&p 500','nasdaq','dow jones','ftse','dax','nikkei'] },
  { key:'credit-spread', title:'Credit Spread', meaning:'The extra yield borrowers pay above a safer benchmark such as government bonds.', lookFor:'Widening versus tightening spreads, especially in high-yield debt.', think:'Wider spreads usually mean markets demand more compensation for default/liquidity risk and can warn of financial stress.', aliases:['corporate spread','high yield spread'] },
  { key:'financial-conditions', title:'Financial Conditions', meaning:'A combined view of how easy or difficult it is for households and businesses to obtain financing.', lookFor:'Rates, credit spreads, equities, currency and lending standards.', think:'Conditions can tighten even without another central-bank hike if market yields or spreads rise sharply.', aliases:['financial conditions index'] },
  { key:'liquidity', title:'Market / Financial Liquidity', meaning:'How easily assets can be traded or financing can be obtained without causing large price changes.', lookFor:'Bid-ask spreads, funding stress, market depth and central-bank liquidity operations.', think:'Low liquidity can amplify price moves and make normal model relationships less reliable.', aliases:['funding liquidity','market liquidity'] },
  { key:'recession', title:'Recession Risk', meaning:'The probability or evidence that economic activity is contracting broadly and persistently.', lookFor:'Employment, income, production, spending, credit and leading indicators together.', think:'No single indicator defines the whole state in real time. Confirmation across several sectors is stronger.', aliases:['recession probability','economic contraction'] },
  { key:'leading-indicator', title:'Leading Indicator', meaning:'A measure intended to change before broader economic activity changes.', lookFor:'Whether several independent leading indicators turn together and whether the signal persists.', think:'Leading indicators sacrifice certainty for timeliness, so false signals are possible.', aliases:['leading economic index','leading indicators'] },
  { key:'lagging-indicator', title:'Lagging Indicator', meaning:'A measure that tends to confirm economic changes after they are already underway.', lookFor:'Whether it validates an earlier signal from faster indicators.', think:'Lagging indicators are slower but can provide stronger confirmation that a regime has actually changed.', aliases:['lagging indicators'] },
  { key:'seasonal-adjustment', title:'Seasonal Adjustment', meaning:'A statistical transformation intended to remove recurring seasonal patterns such as holidays or weather effects.', lookFor:'Large seasonal revisions and unusual periods where normal seasonal patterns may not apply.', think:'Adjusted data is easier to compare through time, but the adjustment itself is estimated and can be revised.', aliases:['seasonally adjusted'] },
  { key:'annualized', title:'Annualized Rate', meaning:'A short-period growth rate converted into the rate that would occur over a full year if the same pace continued.', lookFor:'The underlying quarter/month change because annualization can make small moves look large.', think:'Annualized does not mean the economy actually grew that amount over the past year.', aliases:['annualised'] },
  { key:'yoy', title:'Year-over-Year Change', meaning:'Compares a value with the same period one year earlier.', lookFor:'Base effects and whether recent monthly momentum tells a different story.', think:'YoY is smooth and intuitive but can react slowly to turning points.', aliases:['year over year','y/y'] },
  { key:'mom', title:'Month-over-Month Change', meaning:'Compares a value with the immediately previous month.', lookFor:'Noise, seasonality and whether several months confirm the direction.', think:'MoM reacts quickly to turning points but can be volatile.', aliases:['month over month','m/m'] },
  { key:'qoq', title:'Quarter-over-Quarter Change', meaning:'Compares a value with the immediately previous quarter.', lookFor:'Whether the rate is annualized and how revisions change the trend.', think:'QoQ is useful for identifying recent growth momentum.', aliases:['quarter over quarter','q/q'] },
  { key:'base-effects', title:'Base Effects', meaning:'Changes in annual growth rates caused partly by an unusually high or low comparison period a year earlier.', lookFor:'The underlying monthly level or shorter-term momentum.', think:'A falling YoY inflation rate can occur even when current monthly inflation remains firm if last year’s comparison was unusually high.', aliases:['base effect'] },
  { key:'nowcast', title:'Nowcast', meaning:'An estimate of current economic activity made before the official data is released, using faster indicators.', lookFor:'Model uncertainty, incoming-data revisions and how the estimate changes as new information arrives.', think:'A nowcast is an informed estimate, not an official observation.', aliases:['nowcasting'] },
];

const normalize = (value:string) => value.toLowerCase().replace(/[↑↓×·:()/%+]/g,' ').replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim();

export function resolveMacroExplanation(text:string): Explanation | null {
  const normalized=normalize(text);
  if(!normalized)return null;
  const matches=entries.flatMap(item=>[item.key,item.title,...(item.aliases??[])].map(alias=>({item,alias:normalize(alias)})))
    .filter(({alias})=>alias.length>=2&&normalized.includes(alias))
    .sort((a,b)=>b.alias.length-a.alias.length);
  return matches[0]?.item??null;
}

export const MACRO_EXPLANATIONS=entries;
