import type { Explanation } from './explainability';

const entries: Explanation[] = [
  {key:'tv-contextual-quality',title:'FXGA Contextual Quality',meaning:'A second score calculated in Google Cloud after a TradingView alert arrives. It combines the indicator method score with timeframe alignment, SMC evidence, risk/reward, exact method matches and signal freshness.',lookFor:'The total score, its grade and the component bars underneath it.',think:'The indicator remains the source of the BUY or SELL. This score only asks whether the surrounding evidence still supports acting on that signal now.',warning:'Do not read 90/100 as a 90% probability of winning.',aliases:['contextual quality','contextual score','fxga contextual view']},
  {key:'tv-smc-method-score',title:'SMC Method Score',meaning:'The confluence score produced inside your FXGA SMC2000 indicator for the exact method that generated the alert.',lookFor:'The score versus the indicator minimum score and the number of exact matching methods.',think:'This is the source indicator score. The Google contextual score is deliberately separate so the dashboard never rewrites the indicator telemetry.',aliases:['indicator method score','smc method score','method score']},
  {key:'tv-hierarchy',title:'H4 → M15 → M1 Hierarchy',meaning:'Your indicator uses H4 for major direction, M15 for confirmation and M1 for execution timing.',lookFor:'Whether all three point the same way, whether H4 has changed since the signal and whether the hierarchy remains fully aligned.',think:'A signal is structurally cleaner when execution follows the higher-timeframe direction and confirmation instead of fighting it.',aliases:['h4 direction','m15 confirmation','m1 execution','h4 m15 m1','timeframe hierarchy','hierarchy aligned']},
  {key:'tv-pd-array',title:'PD Array',meaning:'The price-delivery zone selected by the indicator as part of the setup, such as an order block, fair value gap or another SMC zone.',lookFor:'The selected type, zone boundaries and whether current price is still inside or respecting that zone.',think:'The zone explains where the setup expects institutional-style repricing or reaction. Leaving the relevant zone can weaken the setup.',aliases:['pd array','pd_array','selected type']},
  {key:'tv-limit-filled',title:'Limit Filled',meaning:'The indicator previously created a limit-entry setup and price has now traded through the planned entry level.',lookFor:'Entry price, structural stop, targets and whether the lifecycle changes to ACTIVE FILLED.',think:'Once filled, the dashboard treats the setup as a management state rather than advertising it as a fresh entry.',aliases:['limit filled','limit_filled','active filled']},
  {key:'tv-signal-new',title:'New TradingView Signal',meaning:'A fresh executable SMC2000 setup was confirmed by the indicator and sent to Google Cloud.',lookFor:'BUY or SELL direction, method code, confluence score, H4/M15/M1 hierarchy, entry type, stop and targets.',think:'This is the beginning of the setup lifecycle. Later lifecycle alerts update the same setup instead of creating unrelated trades.',aliases:['signal new','signal_new','new signal']},
  {key:'tv-tp1',title:'TP1 Hit',meaning:'Price reached the first take-profit level defined by the original indicator setup.',lookFor:'Whether the setup remains structurally valid, whether TP2/TP3 are still active and whether the major bias changed.',think:'TP1 is evidence the setup moved favorably, but it is not the same as the final target being completed.',aliases:['tp1 hit','tp1_hit','tp1']},
  {key:'tv-tp2',title:'TP2 Hit',meaning:'Price reached the second take-profit level from the original signal.',lookFor:'The remaining TP3 target, current hierarchy and invalidation state.',think:'A TP2 lifecycle state is an advanced trade-management phase, not a fresh signal to chase.',aliases:['tp2 hit','tp2_hit','tp2']},
  {key:'tv-tp3',title:'TP3 / Final Target',meaning:'The indicator reports that the final planned target was reached and the signal lifecycle is complete.',lookFor:'COMPLETED status and the original entry-to-target risk/reward.',think:'Once TP3 is reached, the dashboard returns the suggested signal to WAIT until a new indicator setup arrives.',aliases:['tp3 hit','tp3_hit','tp3','final target reached']},
  {key:'tv-pending-entry',title:'Pending Entry',meaning:'A valid setup exists, but the planned entry has not yet been filled.',lookFor:'Order type, entry level, distance from current price and the expiry/invalidation conditions.',think:'For a limit setup, pending entry means wait for the planned price geometry rather than chasing the market.',aliases:['pending entry','pending_entry','wait for limit','wait for entry']},
  {key:'tv-counter-trend',title:'Counter-Trend Setup',meaning:'The indicator marked the setup as trading against the larger directional context.',lookFor:'Higher-timeframe direction, confluence score, structural confirmation and whether the current H4 bias has changed.',think:'Counter-trend setups generally require stronger evidence because the broader directional force is not supporting the trade.',aliases:['counter trend','counter_trend','counter-trend']},
  {key:'tv-risk-reward',title:'Risk / Reward',meaning:'The planned reward to a target divided by the price distance from entry to structural stop.',lookFor:'RR to TP1, TP2 and TP3, plus whether current price has moved far away from the original entry.',think:'A 3R TP3 means the planned target distance is three times the planned risk distance. It does not describe the probability of reaching that target.',formula:'RR = |Target − Entry| ÷ |Entry − Stop|',aliases:['rr to tp3','rr tp1','rr tp2','rr tp3','risk reward','risk/reward']},
  {key:'tv-lifecycle',title:'Signal Lifecycle',meaning:'The sequence of events that updates one TradingView setup from creation to fill, targets, invalidation, expiry or completion.',lookFor:'SIGNAL_NEW → LIMIT_FILLED → TP1/TP2/TP3, or a cancellation event such as INVALIDATED, LIMIT_EXPIRED or LIMIT_MISSED.',think:'Lifecycle events belong to the same setup. They should update its status rather than be counted as separate independent trade ideas.',aliases:['signal lifecycle','lifecycle','event count']},
  {key:'tv-exact-matches',title:'Exact SMC Method Matches',meaning:'The number of SMC2000 methods that exactly matched the setup conditions when the signal fired.',lookFor:'Exact matches compared with the minimum matches required by the indicator.',think:'More independent exact matches can strengthen confluence, but duplicated or closely related conditions should not be treated as independent evidence.',aliases:['exact matches','exact matching methods']},
  {key:'tv-structural-stop',title:'Structural Stop / Invalidation',meaning:'The price level or structural condition that tells the indicator the setup is no longer valid.',lookFor:'Stop-loss level, zone boundaries and the explicit invalidation explanation.',think:'Invalidation is part of the setup definition. Once it occurs, the dashboard downgrades the setup to WAIT rather than defending an old signal.',aliases:['structural stop','setup invalidated','invalidation discipline']},
];

const normalize=(value:string)=>value.toLowerCase().replace(/[↑↓×·:()/%+]/g,' ').replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim();
export function resolveTradingViewExplanation(text:string):Explanation|null{
  const normalized=normalize(text);if(!normalized)return null;
  const matches=entries.flatMap(item=>[item.key,item.title,...(item.aliases??[])].map(alias=>({item,alias:normalize(alias)}))).filter(({alias})=>alias.length>=3&&normalized.includes(alias)).sort((a,b)=>b.alias.length-a.alias.length);
  return matches[0]?.item??null;
}
export const TRADINGVIEW_EXPLANATIONS=entries;
