version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Africa/Johannesburg
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
    labels:
      - dependencies
      - security

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:50"
      timezone: Africa/Johannesburg
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
