import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import './ElliottWaveReports.css';

const ALL_MT5_TIMEFRAMES=['M1','M2','M3','M4','M5','M6','M10','M12','M15','M20','M30','H1','H2','H3','H4','H6','H8','H12','D1','W1','MN1'];
const API_BASE=String((import.meta as ImportMeta & { env?: Record<string,string|undefined> }).env?.VITE_GOOGLE_CLOUD_API_BASE||'').trim().replace(/\/+$/,'');

type BridgeState={online:boolean;lastSeen:string|null;terminalId:string|null};
type ElliottReport={id:string;symbol:string;timeframes:string[];pageCount:number;createdAt:string|null;completedAt:string|null;fileName:string;pdfUrl:string;dossierVersion?:string;historyDays?:number;historyRows?:number;h1Rows?:number;eventCount?:number;evidenceCount?:number;aiInputMode?:string;historyCoverageComplete?:boolean;eventCoverageNote?:string|null};
type ElliottJob={id:string;status:string;symbol:string;timeframes:string[];uploadedTimeframes:string[];createdAt:string|null;updatedAt:string|null;error:string|null;reportId:string|null;historyUploaded?:boolean;historyDaysRequested?:number;dossierVersion?:string};
type ElliottDecision={status:'TRADE_SETUP'|'WAIT'|'NO_TRADE';direction:'BUY'|'SELL'|'NEUTRAL';confidence:number;entry:{type:string;price:number|null;zoneLow:number|null;zoneHigh:number|null;trigger:string};stopLoss:{price:number|null;basis:string};takeProfits:Array<{label:string;price:number|null;basis:string}>;elliott:{primaryCount:string;currentWave:string;higherTimeframeBias:string;microStructure:string;invalidation:number|null;alternateCount:string};riskReward:{tp1:number|null;tp2:number|null;tp3:number|null};indicatorPlanConsistency:boolean;deviationsFromIndicator:string[];evidenceSummary:string[];conflicts:string[];invalidationConditions:string[];missingEvidence:string[];summary:string};
type ElliottAiAnalysis={id:string;jobId:string;symbol:string;status:string;aiState:string;model:string|null;promptVersion:string;evidenceCount:number;evidenceExpected:number;dossierVersion?:string|null;inputMode?:string;generatedAt:string|null;updatedAt:string|null;error:string|null;decision:ElliottDecision|null};
type ElliottAiState={jobId:string;reportReady:boolean;evidenceCount:number;evidenceExpected:number;dossierVersion?:string|null;inputMode?:string;analysis:ElliottAiAnalysis|null};

function formatTime(value:string|null){if(!value)return '—';const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString();}
function formatPrice(value:number|null|undefined){return Number.isFinite(Number(value))&&Number(value)>0?Number(value).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:5}):'—';}
function formatRR(value:number|null|undefined){return Number.isFinite(Number(value))&&Number(value)>0?`${Number(value).toFixed(2)}R`:'—';}
function formatNum(value:number|null|undefined,digits=0){return Number.isFinite(Number(value))?Number(value).toLocaleString(undefined,{maximumFractionDigits:digits}):'—';}
function apiUrl(path:string){return API_BASE?`${API_BASE}${path}`:path;}
function absolutePdfUrl(path:string){return API_BASE?`${API_BASE}${path}`:new URL(path,window.location.origin).toString();}

export function ElliottWaveReports(){
  const [symbol,setSymbol]=useState('XAUUSD');
  const [bridge,setBridge]=useState<BridgeState>({online:false,lastSeen:null,terminalId:null});
  const [reports,setReports]=useState<ElliottReport[]>([]);
  const [activeJob,setActiveJob]=useState<ElliottJob|null>(null);
  const [selected,setSelected]=useState<ElliottReport|null>(null);
  const [aiState,setAiState]=useState<ElliottAiState|null>(null);
  const [aiLoading,setAiLoading]=useState(false);
  const [loading,setLoading]=useState(false);
  const [message,setMessage]=useState('');
  const autoAiJobRef=useRef<string>('');
  const progress=useMemo(()=>activeJob?.timeframes?.length?Math.round((activeJob.uploadedTimeframes?.length||0)/activeJob.timeframes.length*100):0,[activeJob]);
  const decision=aiState?.analysis?.decision||null;

  const refreshReports=useCallback(async()=>{const response=await fetch(apiUrl('/api/elliott-reports'),{headers:{Accept:'application/json','Cache-Control':'no-cache'}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||`Reports API ${response.status}`);setReports(Array.isArray(payload.reports)?payload.reports:[]);setBridge(payload.bridge||{online:false,lastSeen:null,terminalId:null});},[]);
  const refreshAi=useCallback(async(jobId:string)=>{const response=await fetch(apiUrl(`/api/elliott-ai/jobs/${encodeURIComponent(jobId)}`),{headers:{Accept:'application/json','Cache-Control':'no-cache'}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||`Elliott AI status ${response.status}`);setAiState(payload as ElliottAiState);return payload as ElliottAiState;},[]);
  const runAi=useCallback(async(jobId:string)=>{if(!jobId||aiLoading)return;setAiLoading(true);setMessage('Gemini is reading the single 60-day FXGA Elliott + Macro dossier PDF…');try{const response=await fetch(apiUrl(`/api/elliott-ai/analyze?jobId=${encodeURIComponent(jobId)}`),{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:'{}'});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||`Elliott AI ${response.status}`);const state=await refreshAi(jobId);const d=(payload.analysis?.decision||state.analysis?.decision) as ElliottDecision|undefined;setMessage(d?`AI Elliott decision ready: ${d.status.replace('_',' ')}${d.direction!=='NEUTRAL'?` · ${d.direction}`:''}.`:'AI Elliott analysis is ready.');}catch(error){setMessage(String((error as Error).message||error));await refreshAi(jobId).catch(()=>{});}finally{setAiLoading(false);}},[aiLoading,refreshAi]);

  useEffect(()=>{refreshReports().catch(error=>setMessage(String(error.message||error)));const timer=window.setInterval(()=>refreshReports().catch(()=>{}),10000);return()=>window.clearInterval(timer);},[refreshReports]);
  useEffect(()=>{if(!activeJob||['READY','FAILED'].includes(activeJob.status))return;let cancelled=false;const poll=async()=>{try{const response=await fetch(apiUrl(`/api/elliott-reports/jobs/${encodeURIComponent(activeJob.id)}`),{headers:{Accept:'application/json','Cache-Control':'no-cache'}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||`Job API ${response.status}`);if(cancelled)return;const job=payload.job as ElliottJob;setActiveJob(job);if(job.status==='READY'){setMessage('The 60-day Elliott + Macro dossier is ready. Gemini analysis will start automatically.');await refreshReports();}else if(job.status==='FAILED')setMessage(job.error||'MT5 dossier capture failed.');}catch(error){if(!cancelled)setMessage(String((error as Error).message||error));}};poll();const timer=window.setInterval(poll,2000);return()=>{cancelled=true;window.clearInterval(timer);};},[activeJob?.id,activeJob?.status,refreshReports]);
  useEffect(()=>{if(activeJob?.status!=='READY'||aiLoading||autoAiJobRef.current===activeJob.id)return;let cancelled=false;refreshAi(activeJob.id).then(state=>{if(cancelled)return;if(state.analysis?.status==='READY'){autoAiJobRef.current=activeJob.id;return;}autoAiJobRef.current=activeJob.id;runAi(activeJob.id);}).catch(error=>{if(!cancelled){autoAiJobRef.current='';setMessage(String(error.message||error));}});return()=>{cancelled=true;};},[activeJob?.id,activeJob?.status,aiLoading,refreshAi,runAi]);
  useEffect(()=>{if(!selected)return;refreshAi(selected.id).catch(()=>setAiState(null));},[selected?.id,refreshAi]);

  const analyze=async()=>{const clean=String(symbol||'XAUUSD').trim().toUpperCase().replace(/[^A-Z0-9._-]/g,'').slice(0,32)||'XAUUSD';setSymbol(clean);setLoading(true);setAiState(null);setSelected(null);autoAiJobRef.current='';setMessage('Queuing background MT5 capture, 60-day closed-bar history and Elliott evidence…');try{const response=await fetch(apiUrl('/api/elliott-reports/request'),{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({symbol:clean,timeframes:ALL_MT5_TIMEFRAMES,historyDays:60})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||`Analyze request ${response.status}`);setActiveJob(payload.job);setMessage(bridge.online?'MT5 is polling. EA Bridge will use a separate worker chart, keep your working chart untouched, export at least 60 days of closed-bar prices, and capture all 21 Elliott charts.':'Analyze job queued. MT5 is offline; capture starts automatically when EA Bridge reconnects.');}catch(error){setMessage(String((error as Error).message||error));}finally{setLoading(false);}};
  const selectReport=(report:ElliottReport)=>{setSelected(report);setAiState(null);refreshAi(report.id).catch(()=>{});};
  const viewed=selected||reports.find(r=>r.id===activeJob?.reportId)||null;

  return <section className="ewr-shell">
    <div className="ewr-head"><div><span className="eyebrow">FXGA · Single-PDF Evidence Intelligence</span><h2>60-Day Elliott + Macro AI Dossier</h2><p>One Analyze request builds a self-contained private dossier containing at least 60 days of closed-bar price history, real persisted economic events, event-to-price and event-to-Elliott mapping, strict non-repainting indicator evidence, and all 21 MT5 timeframe screenshots. Gemini reads that one PDF and returns the trade decision.</p></div><span className={`ewr-bridge ${bridge.online?'online':'offline'}`}><i></i>{bridge.online?'MT5 bridge online':'MT5 bridge offline'}</span></div>
    <div className="ewr-control panel"><label><span>Symbol</span><input value={symbol} onChange={event=>setSymbol(event.target.value.toUpperCase())} onKeyDown={event=>{if(event.key==='Enter'&&!loading)analyze();}} placeholder="XAUUSD" maxLength={32}/></label><div className="ewr-tf"><span>Dossier scope</span><strong>60+ days · M5/H1/H4/D1 price ledgers · 21 Elliott charts · economic events</strong><small>{ALL_MT5_TIMEFRAMES.join(' · ')}</small></div><button className="ewr-analyze" type="button" disabled={loading||Boolean(activeJob&&!['READY','FAILED'].includes(activeJob.status))} onClick={analyze}>{loading?'Queuing…':activeJob&&!['READY','FAILED'].includes(activeJob.status)?'Background dossier capture':'Build + Analyze Dossier'}</button></div>
    {activeJob&&<div className={`ewr-job ${activeJob.status.toLowerCase()}`}><div><span className="eyebrow">Current Request</span><strong>{activeJob.symbol} · {activeJob.status}</strong><small>{activeJob.uploadedTimeframes?.length||0}/{activeJob.timeframes?.length||21} charts uploaded · 60-day history {activeJob.historyUploaded?'uploaded':'preparing'} · working chart remains untouched</small></div><div className="ewr-progress"><span style={{width:`${activeJob.status==='READY'?100:progress}%`}}></span></div></div>}
    {message&&<div className="ewr-message">{message}</div>}
    {viewed&&<div className="ewr-dossier-meta panel"><div><span>PDF pages</span><strong>{formatNum(viewed.pageCount)}</strong></div><div><span>H1 history</span><strong>{formatNum(viewed.historyDays,1)} days</strong><small>{formatNum(viewed.h1Rows)} closed H1 bars</small></div><div><span>All price rows</span><strong>{formatNum(viewed.historyRows)}</strong><small>M5 + H1 + H4 + D1</small></div><div><span>Economic events</span><strong>{formatNum(viewed.eventCount)}</strong><small>mapped to price + pivots</small></div><div><span>Elliott evidence</span><strong>{formatNum(viewed.evidenceCount)}/21</strong><small>strict non-repaint snapshots</small></div><div><span>AI input</span><strong>ONE PDF</strong><small>{viewed.dossierVersion||'FXGA dossier'}</small></div></div>}

    <div className="ewr-ai panel"><div className="ewr-title"><div><span className="eyebrow">Gemini · PDF-Only Multimodal Audit</span><h3>Entry · Stop Loss · Take Profit · Elliott Thesis</h3></div><div className="ewr-ai-actions">{(selected||activeJob?.status==='READY')&&<button type="button" disabled={aiLoading} onClick={()=>runAi((selected?.id||activeJob?.id) as string)}>{aiLoading?'Reading dossier…':aiState?.analysis?'Refresh AI Decision':'Run AI Decision'}</button>}<span className={`ewr-ai-status ${(decision?.direction||decision?.status||'idle').toLowerCase()}`}>{decision?`${decision.status.replace('_',' ')} · ${decision.direction}`:aiLoading?'READING ONE PDF':'AWAITING DOSSIER'}</span></div></div>
      {!decision?<div className="ewr-empty ai">Gemini receives the completed FXGA dossier PDF as the only large evidence input. The PDF contains the numerical price series, economic chronology, Elliott evidence, theory/governance instructions and chart screenshots. Missing or contradictory evidence must produce WAIT / NO TRADE rather than invented levels.</div>:<><div className="ewr-trade-strip"><div><span>Direction</span><strong>{decision.direction}</strong><small>{decision.status.replace('_',' ')}</small></div><div><span>Entry</span><strong>{formatPrice(decision.entry.price)}</strong><small>{decision.entry.type}{decision.entry.zoneLow&&decision.entry.zoneHigh?` · ${formatPrice(decision.entry.zoneLow)}–${formatPrice(decision.entry.zoneHigh)}`:''}</small></div><div><span>Stop Loss</span><strong>{formatPrice(decision.stopLoss.price)}</strong><small>{decision.stopLoss.basis||'Elliott structural risk'}</small></div>{decision.takeProfits.slice(0,3).map((tp,index)=><div key={`${tp.label}-${index}`}><span>{tp.label||`TP${index+1}`}</span><strong>{formatPrice(tp.price)}</strong><small>{formatRR([decision.riskReward.tp1,decision.riskReward.tp2,decision.riskReward.tp3][index])}</small></div>)}<div><span>Confidence</span><strong>{Math.round(decision.confidence)}%</strong><small>{aiState?.analysis?.model||'Gemini'} · PDF-only evidence</small></div></div>
      <div className="ewr-thesis-grid"><article><span className="eyebrow">Primary Elliott Count</span><strong>{decision.elliott.primaryCount||'—'}</strong><p>Current wave: {decision.elliott.currentWave||'—'}</p><p>Higher timeframe: {decision.elliott.higherTimeframeBias||'—'}</p></article><article><span className="eyebrow">Execution + Invalidation</span><strong>{decision.elliott.microStructure||'—'}</strong><p>Elliott invalidation: {formatPrice(decision.elliott.invalidation)}</p><p>Trigger: {decision.entry.trigger||'—'}</p></article><article><span className="eyebrow">Alternate Count</span><strong>{decision.elliott.alternateCount||'None supplied'}</strong><p>Indicator-plan consistency: {decision.indicatorPlanConsistency?'Aligned':'Not fully aligned'}</p><p>{decision.summary}</p></article></div>
      <div className="ewr-evidence-grid"><article><h4>Strongest dossier evidence</h4>{decision.evidenceSummary.length?<ul>{decision.evidenceSummary.map((item,index)=><li key={index}>{item}</li>)}</ul>:<p>No evidence summary returned.</p>}</article><article><h4>Conflicts / missing evidence</h4>{[...decision.conflicts,...decision.missingEvidence].length?<ul>{[...decision.conflicts,...decision.missingEvidence].map((item,index)=><li key={index}>{item}</li>)}</ul>:<p>No material conflict reported.</p>}</article><article><h4>What cancels the thesis</h4>{decision.invalidationConditions.length?<ul>{decision.invalidationConditions.map((item,index)=><li key={index}>{item}</li>)}</ul>:<p>Use the dossier's confirmed Elliott invalidation and hard rule audit.</p>}</article></div></>}
    </div>

    <div className="ewr-grid"><div className="ewr-library panel"><div className="ewr-title"><div><span className="eyebrow">Private Dossier Library</span><h3>60-Day AI PDFs</h3></div><button type="button" onClick={()=>refreshReports().catch(error=>setMessage(String(error.message||error)))}>Refresh</button></div>{!reports.length?<div className="ewr-empty">No dossiers yet. Build the first 60-day Elliott + Macro evidence PDF.</div>:<div className="ewr-list">{reports.map(report=><article className={selected?.id===report.id?'selected':''} key={report.id}><div><strong>{report.symbol}</strong><span>{report.pageCount} pages · {formatNum(report.historyDays,1)} days · {formatNum(report.eventCount)} events · {formatTime(report.completedAt)}</span><small>{report.fileName}</small></div><div className="ewr-actions"><button type="button" onClick={()=>selectReport(report)}>View + AI</button><a href={absolutePdfUrl(report.pdfUrl)} target="_blank" rel="noreferrer">Open PDF</a></div></article>)}</div>}</div><div className="ewr-viewer panel"><div className="ewr-title"><div><span className="eyebrow">Canonical AI Evidence</span><h3>{selected?`${selected.symbol} 60-Day Dossier`:'Select a dossier'}</h3></div>{selected&&<a href={absolutePdfUrl(selected.pdfUrl)} target="_blank" rel="noreferrer">Full screen</a>}</div>{selected?<iframe title={`${selected.symbol} FXGA 60-Day Elliott Macro Dossier`} src={absolutePdfUrl(selected.pdfUrl)}/>:<div className="ewr-empty viewer">Choose View + AI to inspect the exact single PDF that Gemini reads.</div>}</div></div>
    <small className="ewr-foot">Last MT5 heartbeat: {formatTime(bridge.lastSeen)}{bridge.terminalId?` · ${bridge.terminalId}`:''}. Background worker charts never change the parent trading chart. The dossier uses persisted economic data only; missing historical events are identified as missing rather than synthesized.</small>
  </section>;
}
