import { useEffect,useMemo,useState } from 'react';
import { fetchEventPatternBacktests } from '../lib/api';
import { EVENT_STUDY_HORIZONS,type EventPatternBacktest,type EventPatternBacktestPayload,type EventStudyHorizon } from '../lib/event-study-types';
import './EventBacktestValidation.css';

const pct=(value:number|null|undefined,digits=2)=>typeof value==='number'&&Number.isFinite(value)?`${value>0?'+':''}${value.toFixed(digits)}%`:'—';
const ratio=(value:number|null|undefined,digits=1)=>typeof value==='number'&&Number.isFinite(value)?`${(value*100).toFixed(digits)}%`:'—';
const q=(value:number|null|undefined)=>typeof value==='number'&&Number.isFinite(value)?value.toFixed(3):'—';
function confidence(test:EventPatternBacktest){const stability=Number(test.temporalStability||0),holdout=Math.min(1,test.holdoutObservations/20),fdr=Math.max(0,1-Number(test.qValue??1)),ci=test.holdoutNet95Low!=null&&test.holdoutNet95Low>0?1:.35;return Math.round(100*(.30*stability+.25*holdout+.25*fdr+.20*ci));}
function ValidationCard({test}:{test:EventPatternBacktest}){const tone=test.promotionEligible?'validated':'research',score=confidence(test);return<article className={`event-oos-card ${tone}`}><header><div><span>{test.eventFamily} · {test.currency}</span><strong>{test.assetId} · {test.horizon}</strong></div><b>{test.promotionEligible?'Validated candidate':'Not promoted'}</b></header><div className="event-oos-grid"><span><small>Direction</small>{test.direction}</span><span><small>Holdout</small>{test.holdoutObservations}</span><span><small>Net mean</small>{pct(test.holdoutNetMeanPct)}</span><span><small>Win rate</small>{ratio(test.winRate)}</span><span><small>q-value</small>{q(test.qValue)}</span><span><small>Stability</small>{ratio(test.temporalStability)}</span></div><div className="event-oos-range"><span>95% net-mean interval</span><strong>{pct(test.holdoutNet95Low)} → {pct(test.holdoutNet95High)}</strong></div><footer><span>{test.prePattern} · {test.preDirection}</span><span>{test.costBps.toFixed(1)} bps cost assumption</span><span>evidence score {score}/100</span></footer></article>;}

export function EventBacktestValidation(){
  const[payload,setPayload]=useState<EventPatternBacktestPayload|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[validatedOnly,setValidatedOnly]=useState(false),[horizon,setHorizon]=useState<EventStudyHorizon|'all'>('all');
  useEffect(()=>{let cancelled=false;setLoading(true);void fetchEventPatternBacktests({validatedOnly,horizon:horizon==='all'?undefined:horizon,limit:120}).then(result=>{if(!cancelled){setPayload(result);setError('');}}).catch(caught=>{if(!cancelled)setError(caught instanceof Error?caught.message:'OOS validation is unavailable.');}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[validatedOnly,horizon]);
  const tests=useMemo(()=>payload?.tests??[],[payload]);
  const validated=payload?.summary?.validatedCandidates??tests.filter(test=>test.promotionEligible).length,total=payload?.summary?.tests??tests.length;
  return<section className="event-oos-workspace"><div className="event-oos-head"><div><span className="eyebrow">Out-of-Sample Validation</span><h3>Pattern evidence gate</h3><p>Chronological training and holdout samples prevent future releases from leaking into pattern discovery. Results apply instrument-level execution-cost assumptions, confidence intervals and Benjamini-Hochberg false-discovery-rate control.</p></div><div className="event-oos-kpis"><span><strong>{total}</strong> tested profiles</span><span><strong>{validated}</strong> validated candidates</span></div></div><div className="event-oos-controls"><button className={!validatedOnly?'active':''} onClick={()=>setValidatedOnly(false)}>All tests</button><button className={validatedOnly?'active':''} onClick={()=>setValidatedOnly(true)}>Validated only</button><select value={horizon} onChange={event=>setHorizon(event.target.value as EventStudyHorizon|'all')}><option value="all">All horizons</option>{EVENT_STUDY_HORIZONS.map(value=><option key={value} value={value}>{value}</option>)}</select></div>{loading&&!payload?<div className="event-reaction-empty">Loading chronological holdout validation…</div>:null}{error&&!payload?<div className="alert warn">{error}</div>:null}{!loading&&!tests.length?<div className="event-reaction-empty">No profile currently satisfies this filter. This is expected while the 60-day event sample develops; the engine does not manufacture validated edges.</div>:null}{tests.length?<div className="event-oos-list">{tests.slice(0,40).map(test=><ValidationCard key={`${test.profileKey}-${test.horizon}`} test={test}/>)}</div>:null}<p className="event-oos-policy">A “validated candidate” means the observed conditional relationship survived this defined historical holdout/FDR/cost screen. It is not a guarantee of future profitability and still requires continued walk-forward monitoring, slippage robustness and independent evidence.</p></section>;
}
