import { useEffect,useMemo,useState } from 'react';
import { fetchEventStudies } from '../lib/api';
import { EVENT_STUDY_HORIZONS,PRE_NEWS_WINDOWS,type EconomicEventStudy,type EventStudiesPayload,type EventStudyHorizon,type EventStudyMeasurement,type EventStudyReaction,type PreNewsAssetProfile,type PreNewsWindow } from '../lib/event-study-types';
import './EventStudyPanel.css';
import './EventStudySources.css';

type EvidenceSource={status:'live'|'warming'|'degraded'|string;role:string;generatedAt?:string|null;seriesCount?:number;assetCount?:number;eventCount?:number;studyCount?:number};
type EventStudySourceFusion={generatedAt:string;architecture:string;sources:{fred:EvidenceSource;cnbc:EvidenceSource;fxstreet:EvidenceSource;mt5:EvidenceSource};policy:{fred:string;cnbc:string;mt5:string;missingData:string}};

function ratioPct(value:number|null|undefined,digits=1){return typeof value==='number'&&Number.isFinite(value)?`${(value*100).toFixed(digits)}%`:'—';}
function move(value:number|null|undefined,digits=3){return typeof value==='number'&&Number.isFinite(value)?`${value>0?'+':''}${value.toFixed(digits)}%`:'—';}
function price(value:number|null|undefined){if(typeof value!=='number'||!Number.isFinite(value))return'—';return value.toLocaleString(undefined,{maximumFractionDigits:Math.abs(value)<10?5:3});}
function qualityLabel(measurement?:EventStudyMeasurement){if(!measurement)return'Pending';if(measurement.quality==='measured')return'Measured';if(measurement.quality==='baseline-too-old'||measurement.quality==='baseline-unavailable')return'Baseline unavailable';if(measurement.quality==='observation-delayed'||measurement.quality==='observation-unavailable')return'Observation unavailable';return'Market data unavailable';}
function measurementTone(measurement?:EventStudyMeasurement){if(!measurement||measurement.quality!=='measured')return'unavailable';if(typeof measurement.crossAssetBreadth==='number'){if(measurement.crossAssetBreadth>.15)return'aligned';if(measurement.crossAssetBreadth<-.15)return'opposed';return'muted';}if(Number(measurement.opposed||0)>Number(measurement.aligned||0))return'opposed';if(Number(measurement.aligned||0)>0)return'aligned';return'muted';}
function horizonHeadline(measurement:EventStudyMeasurement){if(measurement.quality!=='measured')return qualityLabel(measurement);if(typeof measurement.averageAbsoluteMovePct==='number')return`${move(measurement.averageAbsoluteMovePct)} avg |Δ|`;if(typeof measurement.directionalAgreement==='number')return`${ratioPct(measurement.directionalAgreement)} agreement`;return`${measurement.usableAssets} assets measured`;}
function horizonDetail(measurement:EventStudyMeasurement){if(measurement.quality!=='measured')return`${measurement.usableAssets||0} usable assets`;if(typeof measurement.crossAssetBreadth==='number')return`${measurement.usableAssets}/${measurement.totalAssets??16} assets · breadth ${ratioPct(measurement.crossAssetBreadth)}`;return`${move(measurement.meanBaseCurrencyMovePct)} base-currency move`;}
function sourceCount(id:string,source:EvidenceSource){if(id==='FRED')return`${source.seriesCount??0} macro series`;if(id==='CNBC')return`${source.assetCount??0} cross-asset quotes`;if(id==='FXStreet')return`${source.eventCount??0} calendar events`;return`${source.studyCount??0} stored studies`;}
function sourceAge(value?:string|null){if(!value)return'awaiting timestamp';const ms=Date.now()-Date.parse(value);if(!Number.isFinite(ms))return'latest state';const mins=Math.max(0,Math.round(ms/60000));return mins<60?`${mins}m old`:`${Math.floor(mins/60)}h old`;}

function HorizonCell({horizon,measurement,active,onSelect}:{horizon:EventStudyHorizon;measurement?:EventStudyMeasurement;active:boolean;onSelect:()=>void}){if(!measurement)return<button className={`event-horizon pending ${active?'active':''}`} onClick={onSelect}><b>{horizon}</b><strong>Pending</strong><span>Awaiting price path</span></button>;const tone=measurementTone(measurement);return<button className={`event-horizon ${tone} ${active?'active':''}`} title={`${measurement.usableAssets} usable assets`} onClick={onSelect}><b>{horizon}</b><strong>{horizonHeadline(measurement)}</strong><span>{horizonDetail(measurement)}</span></button>;}
function ReactionCard({reaction}:{reaction:EventStudyReaction}){const value=reaction.rawMovePct,tone=!reaction.available?'unavailable':Number(value||0)>0?'positive':Number(value||0)<0?'negative':'flat',observation=reaction.observationPrice??reaction.currentPrice;return<article className={`event-price-reaction ${tone}`}><header><strong>{reaction.assetId}</strong><span>{reaction.available?move(value):'Unavailable'}</span></header><div><span><small>Before</small>{price(reaction.baselinePrice)}</span><span><small>After</small>{price(observation)}</span></div>{reaction.available?<footer><span>↑ max {move(reaction.maxUpsidePct)}</span><span>↓ max {move(reaction.maxDownsidePct)}</span><span>range {move(reaction.rangePct)}</span></footer>:<footer><span>{reaction.quality||'No verified M1 observation'}</span></footer>}</article>;}
function PreNewsCard({profile,window}:{profile:PreNewsAssetProfile;window:PreNewsWindow}){const row=profile.windows?.[window],tone=!row?.available?'unavailable':Number(row.movePct||0)>0?'positive':Number(row.movePct||0)<0?'negative':'flat';return<article className={`event-pre-card ${tone}`}><header><strong>{profile.assetId}</strong><span>{row?.available?move(row.movePct):'Unavailable'}</span></header>{row?.available?<><div className="event-pre-stats"><span><small>Range</small>{move(row.rangePct)}</span><span><small>ATR</small>{move(row.atrPct)}</span><span><small>R²</small>{row.trendR2?.toFixed(2)??'—'}</span><span><small>Efficiency</small>{row.efficiencyRatio?.toFixed(2)??'—'}</span></div><p>{(row.patterns||[]).join(' · ')||'no dominant pattern'}</p><footer><span>{row.bars} M1 bars</span><span>close loc {row.closeLocation==null?'—':`${(row.closeLocation*100).toFixed(0)}%`}</span></footer></>:<p>{row?.quality||'No verified pre-release M1 history'}</p>}</article>;}
function preferredHorizon(study:EconomicEventStudy):EventStudyHorizon{if(study.horizons?.['1h'])return'1h';return EVENT_STUDY_HORIZONS.find(horizon=>study.horizons?.[horizon])??'1h';}

function StudyRow({study}:{study:EconomicEventStudy}){
  const[selected,setSelected]=useState<EventStudyHorizon>(()=>preferredHorizon(study)),[preWindow,setPreWindow]=useState<PreNewsWindow>('1h'),[expanded,setExpanded]=useState(false),measurement=study.horizons?.[selected],measuredAssets=measurement?.reactions?.filter(reaction=>reaction.available).length??0,preAssets=study.preNews?.assets??[],preMeasured=preAssets.filter(asset=>asset.windows?.[preWindow]?.available).length,time=study.timeSignature;
  return<article className={`event-study-row ${expanded?'expanded':''}`}>
    <div className="event-study-release"><span className="eyebrow">{study.currency} · {new Date(study.releaseAt).toLocaleString([],{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}</span><strong>{study.event}</strong><small>Actual {study.actual??'—'} · Consensus {study.forecast??'—'} · Previous {study.previous??'—'}</small><small>{time?`${time.weekday} · W${time.isoWeek} · ${time.sessionUtc.replaceAll('_',' ')} · ${String(time.hourUtc).padStart(2,'0')}:${String(time.minuteUtc).padStart(2,'0')} UTC`:study.releaseDateUtc??''}</small><small>{study.priceSource||'Verified market history'} · {study.sourceTimeframe||'snapshot'} source</small></div>
    <div className={`event-study-bias ${study.currencyBias}`}><strong>{study.currencyBias}</strong><span>{study.biasConfidence??'—'}% release confidence</span><button onClick={()=>setExpanded(value=>!value)}>{expanded?'Hide research':'View price action'}</button></div>
    <div className="event-study-horizons">{EVENT_STUDY_HORIZONS.map(horizon=><HorizonCell key={horizon} horizon={horizon} measurement={study.horizons?.[horizon]} active={selected===horizon} onSelect={()=>{setSelected(horizon);setExpanded(true);}}/>)}</div>
    {expanded?<div className="event-reaction-detail">
      <section className="event-pre-news"><div className="event-reaction-head"><div><span className="eyebrow">Pre News Price Action · {preWindow}</span><strong>{preMeasured}/{study.priceUniverse?.length??16} verified asset profiles</strong></div><span>{study.preNews?.crossAsset?`${study.preNews.crossAsset.state.replaceAll('-',' ')} · ${study.preNews.crossAsset.volatilityState.replaceAll('-',' ')}`:'Profile building'}</span></div><div className="event-pre-window-tabs">{PRE_NEWS_WINDOWS.map(window=><button key={window} className={preWindow===window?'active':''} onClick={()=>setPreWindow(window)}>{window} before</button>)}</div>{preAssets.length?<div className="event-pre-grid">{preAssets.map(profile=><PreNewsCard key={`${study.eventId}-${preWindow}-${profile.assetId}`} profile={profile} window={preWindow}/>)}</div>:<div className="event-reaction-empty">No verified pre-news profile is stored for this release yet.</div>}<div className="event-profile-signature"><span>Profile signature</span><code>{study.profileSignature||study.preNews?.crossAsset?.profileSignature||'building'}</code></div></section>
      <section><div className="event-reaction-head"><div><span className="eyebrow">Post Release Cross Asset Reaction · {selected}</span><strong>{measuredAssets}/{study.priceUniverse?.length??measurement?.totalAssets??16} verified asset paths</strong></div><span>{measurement?.quality==='measured'?`Average absolute move ${move(measurement.averageAbsoluteMovePct)}`:qualityLabel(measurement)}</span></div>{measurement?.reactions?.length?<div className="event-price-reaction-grid">{measurement.reactions.map(reaction=><ReactionCard key={`${study.eventId}-${selected}-${reaction.assetId}`} reaction={reaction}/>)}</div>:<div className="event-reaction-empty">No verified price reactions are stored for this horizon yet.</div>}</section>
    </div>:null}
  </article>;
}

export function EventStudyPanel(){
  const[payload,setPayload]=useState<EventStudiesPayload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const[sourceFusion,setSourceFusion]=useState<EventStudySourceFusion|null>(null),[sourceError,setSourceError]=useState('');
  useEffect(()=>{let cancelled=false;setLoading(true);void fetchEventStudies(60).then(result=>{if(!cancelled){setPayload(result);setError('');}}).catch(caught=>{if(!cancelled)setError(caught instanceof Error?caught.message:'Release reaction history is unavailable.');}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[]);
  useEffect(()=>{let cancelled=false;const controller=new AbortController(),timer=window.setTimeout(()=>controller.abort(),30_000);void fetch('/api/event-study-sources',{headers:{Accept:'application/json','Cache-Control':'no-cache'},cache:'no-store',signal:controller.signal}).then(async response=>{const text=await response.text();if(!response.ok)throw new Error(`Evidence source health ${response.status}`);return JSON.parse(text) as EventStudySourceFusion;}).then(result=>{if(!cancelled){setSourceFusion(result);setSourceError('');}}).catch(caught=>{if(!cancelled)setSourceError(caught instanceof Error?caught.message:'Evidence-source health unavailable');}).finally(()=>window.clearTimeout(timer));return()=>{cancelled=true;window.clearTimeout(timer);controller.abort();};},[]);
  const studies=useMemo(()=>[...(payload?.studies??[])].sort((a,b)=>Date.parse(b.releaseAt)-Date.parse(a.releaseAt)).slice(0,120),[payload]),days=payload?.days??60;
  const sourceEntries=sourceFusion?[['FRED',sourceFusion.sources.fred],['CNBC',sourceFusion.sources.cnbc],['FXStreet',sourceFusion.sources.fxstreet],['MT5',sourceFusion.sources.mt5]] as Array<[string,EvidenceSource]>:[];
  return<section className="event-study-workspace"><div className="section-head event-study-title"><div><span className="eyebrow">Event Study & Backtesting</span><h2>Price action before and after every economic release</h2><p>Each completed release is profiled against canonical MT5 M1 history before the announcement and then followed across the full Cross Asset universe after release. FRED supplies macro-series evidence, FXStreet supplies release history, CNBC supplies an independent current cross-asset cross-check, and MT5 remains the historical price-path authority.</p></div><span>{days}-day study window · {payload?.summary?.assetMeasurements??payload?.summary?.measuredHorizons??0} asset measurements</span></div>
    {sourceEntries.length?<><div className="event-study-source-grid">{sourceEntries.map(([id,source])=><article key={id} className={`event-study-source-card ${source.status}`}><header><strong>{id}</strong><span>{source.status}</span></header><p>{source.role}</p><footer><span>{sourceCount(id,source)}</span><span>{sourceAge(source.generatedAt)}</span></footer></article>)}</div><p className="event-study-source-policy">Source discipline: {sourceFusion?.policy.fred} {sourceFusion?.policy.cnbc} {sourceFusion?.policy.mt5} {sourceFusion?.policy.missingData}</p></>:sourceError?<div className="alert warn">Event-study source health: {sourceError}. Stored MT5 event studies remain available.</div>:<div className="loading-panel">Checking FRED, CNBC, FXStreet and MT5 evidence sources…</div>}
    <div className="event-study-summary">{EVENT_STUDY_HORIZONS.map(horizon=>{const summary=payload?.summary?.byHorizon?.[horizon];return<article key={horizon}><span>{horizon}</span><strong>{summary?.observations??0}</strong><small>{summary?.observations?`${summary.meanAbsoluteMovePct!=null?`${move(summary.meanAbsoluteMovePct)} mean |Δ|`:`${ratioPct(summary.meanDirectionalAgreement)} mean agreement`} · ${summary.assetObservations??0} asset paths`:'Building sample'}</small></article>;})}</div>{loading&&!payload?<div className="loading-panel">Loading economic release price history…</div>:null}{error&&!payload?<div className="alert warn">{error}</div>:null}{!loading&&!studies.length?<div className="panel event-study-empty"><strong>Market-reaction history is accumulating.</strong><span>Price action is only profiled when real M1 evidence exists. Missing pre-news or post-news observations remain unavailable rather than synthesized.</span></div>:null}{studies.length?<div className="event-study-list">{studies.map(study=><StudyRow key={study.eventId} study={study}/>)}</div>:null}</section>;
}
