import { useEffect, useMemo, useRef, useState, type CSSProperties } from 'react';
import './TradingViewSignalIntelligence.css';

type Side='BUY'|'SELL'|'WAIT';
type SourceFilter='ALL'|'MT5'|'TRADINGVIEW'|'TESTS';
type SignalIntelligence={score:number;grade:string;suggestedSignal:Side;sourceSignal:Side;action:string;label:string;explanation:string;components:Record<string,number>;policy:string};
type TradePlan={side?:Side;tradeMode?:string;orderType?:string;filled?:boolean;entry:number|null;stopLoss:number|null;tp1:number|null;tp2:number|null;tp3:number|null;primaryTargetType?:string|null};
type HierarchyNode={h4_major?:string;h4?:string;m15_confirmation?:string;m15?:string;m1_execution?:string;m1?:string;fully_aligned?:boolean;trade_mode?:string;major_bias_changed_since_signal?:boolean};
type Signal={
  id:string;schema?:string;source?:string;platform?:string;engine?:string;stream?:string;symbol:string;tickerId?:string;exchange?:string;timeframe:string;side:Side;status:string;methodId?:number|null;methodCode?:string|null;methodFamily?:string|null;methodScore?:number|null;exactMatches?:number|null;signalTime?:string|null;updatedAt:string;lastEvent:string;lastReason?:string|null;lastMeaning?:string|null;marketPrice?:number|null;lastEventPrice?:number|null;eventCount?:number;
  tradePlan:TradePlan;riskReward:{riskPriceDistance?:number|null;rrTp1?:number|null;rrTp2?:number|null;rrTp3?:number|null};lifecycle:{barsSinceSignal?:number|null;entryFilled?:boolean;tp1Hit?:boolean;tp2Hit?:boolean;finalTargetHit?:boolean};
  timeframeHierarchy?:{model?:string;at_signal?:HierarchyNode;current?:HierarchyNode};
  smcEvidenceAtSignal?:Record<string,unknown>;currentMarketEvidence?:Record<string,unknown>;dealingRange?:Record<string,unknown>;pdArray?:{selected_type?:string;zone_top?:number;zone_bottom?:number;current_price_inside_zone?:boolean};invalidation?:{structural_stop?:number;explanation?:string};intelligence:SignalIntelligence;
};
type SignalList={generatedAt:string;count:number;signals:Signal[]};
type Metrics={totalSignals?:number;totalEvents?:number;mt5Signals?:number;mt5Events?:number;buySignals?:number;sellSignals?:number;filled?:number;tp1Hits?:number;tp2Hits?:number;tp3Hits?:number;completed?:number;invalidated?:number;expired?:number;missed?:number;completionRate?:number;tp1Rate?:number;tp2Rate?:number;tp3Rate?:number;updatedAt?:string;latest?:{updatedAt?:string;lastEvent?:string;symbol?:string;side?:string;status?:string;intelligenceScore?:number;source?:string;platform?:string}};
type SignalEvent={id:string;eventId?:string;event:string;receivedAt:string;payload:Record<string,unknown>};
type SignalDetail={signal:Signal;events:SignalEvent[]};

const fmt=(value:number|null|undefined)=>value==null||!Number.isFinite(value)?'—':Math.abs(value)>=100?value.toLocaleString(undefined,{maximumFractionDigits:2}):value.toLocaleString(undefined,{maximumFractionDigits:5});
const pct=(value:number|null|undefined)=>`${Math.round(Number(value)||0)}%`;
const age=(date?:string|null)=>{if(!date)return '—';const ms=Date.now()-Date.parse(date);if(!Number.isFinite(ms))return '—';const mins=Math.max(0,Math.floor(ms/60000));return mins<1?'just now':mins<60?`${mins}m ago`:mins<1440?`${Math.floor(mins/60)}h ${mins%60}m ago`:`${Math.floor(mins/1440)}d ago`;};
const sideClass=(side?:string)=>String(side||'WAIT').toLowerCase();
const isActive=(signal:Signal)=>signal.status==='PENDING_ENTRY'||signal.status==='ACTIVE_FILLED';
const sourceKind=(signal:Signal)=>String(signal.platform||signal.source||'TradingView').toUpperCase().includes('MT5')||String(signal.source||'').toUpperCase().includes('METATRADER')?'MT5':'TRADINGVIEW';
const isTestSignal=(signal:Signal)=>String(signal.stream||'').toLowerCase().includes('_test')||String(signal.methodCode||'').toUpperCase()==='SYSTEM_TEST'||String(signal.symbol||'').startsWith('FXGA_TEST_');
const cleanSymbol=(signal:Signal)=>signal.symbol.replace(/^FXGA_TEST_/,'');
const sourceLabel=(signal:Signal)=>isTestSignal(signal)?'PIPELINE TEST':sourceKind(signal)==='MT5'?'MT5 LIVE':'TRADINGVIEW LIVE';
const record=(value:unknown):Record<string,unknown>=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{};
const boolEntries=(value:unknown)=>Object.entries(record(value)).filter(([,v])=>typeof v==='boolean');
const words=(value:unknown)=>String(value??'—').replaceAll('_',' ');
const num=(value:unknown)=>typeof value==='number'&&Number.isFinite(value)?value:null;
const text=(value:unknown)=>typeof value==='string'?value:'';
const parseMaybeJson=(value:unknown):Record<string,unknown>=>{if(value&&typeof value==='object'&&!Array.isArray(value))return value as Record<string,unknown>;if(typeof value==='string'){try{const parsed=JSON.parse(value);return record(parsed);}catch{return {};}}return {};};
const hValue=(node:HierarchyNode|undefined,key:'h4'|'m15'|'m1')=>key==='h4'?(node?.h4_major??node?.h4):key==='m15'?(node?.m15_confirmation??node?.m15):(node?.m1_execution??node?.m1);

async function getJson<T>(path:string):Promise<T>{const response=await fetch(path,{headers:{Accept:'application/json','Cache-Control':'no-cache'}});const body=await response.text();if(!response.ok)throw new Error(body||`${path} failed with ${response.status}`);return JSON.parse(body) as T;}

function ScoreRing({score}:{score:number}){return <div className="tv-score-ring" style={{'--score':`${Math.max(0,Math.min(100,score))}%`} as CSSProperties}><div><strong>{score}</strong><span>/100</span></div></div>;}
function SourceBadge({signal}:{signal:Signal}){const kind=sourceKind(signal);return <span className={`tv-source-badge ${kind.toLowerCase()} ${isTestSignal(signal)?'test':''}`}><i></i>{sourceLabel(signal)}</span>;}

function TradePlanVisual({signal}:{signal:Signal}){
  const levels=[['TP3',signal.tradePlan.tp3],['TP2',signal.tradePlan.tp2],['TP1',signal.tradePlan.tp1],['ENTRY',signal.tradePlan.entry],['STOP',signal.tradePlan.stopLoss]] as const;
  const numeric=levels.map(([,v])=>v).filter((v):v is number=>typeof v==='number'&&Number.isFinite(v));
  const min=numeric.length?Math.min(...numeric):0,max=numeric.length?Math.max(...numeric):1,span=Math.max(max-min,Number.EPSILON);
  const current=signal.marketPrice;
  return <div className="tv-plan-visual" data-explain-key="risk reward"><div className="tv-plan-scale">{levels.map(([label,value])=>value==null?null:<div key={label} className={`tv-level ${label.toLowerCase()}`} style={{bottom:`${8+((value-min)/span)*84}%`}}><span>{label}</span><i></i><strong>{fmt(value)}</strong></div>)}{typeof current==='number'&&<div className="tv-current" style={{bottom:`${8+((Math.max(min,Math.min(max,current))-min)/span)*84}%`}}><b></b><span>NOW {fmt(current)}</span></div>}</div><div className="tv-plan-facts"><div><span>Order</span><strong>{signal.tradePlan.orderType||'—'}</strong></div><div><span>Mode</span><strong>{words(signal.tradePlan.tradeMode)}</strong></div><div><span>Target</span><strong>{words(signal.tradePlan.primaryTargetType)}</strong></div><div><span>RR to TP3</span><strong>{signal.riskReward.rrTp3?.toFixed(2)??'—'}R</strong></div></div></div>;
}

function Hierarchy({signal}:{signal:Signal}){const at=signal.timeframeHierarchy?.at_signal,cur=signal.timeframeHierarchy?.current;return <div className="tv-hierarchy" data-explain-key="market bias">{([['H4 Direction','h4'],['M15 Confirmation','m15'],['M1 Execution','m1']] as const).map(([label,key])=>{const start=hValue(at,key),now=hValue(cur,key);return <div key={label}><span>{label}</span><strong className={sideClass(String(now))}>{String(now||'—')}</strong><small>{start===now?'unchanged':`signal: ${start||'—'}`}</small></div>;})}<div><span>Hierarchy</span><strong className={cur?.fully_aligned?'buy':'wait'}>{cur?.fully_aligned?'ALIGNED':'MIXED'}</strong><small>{cur?.major_bias_changed_since_signal?'H4 changed':'H4 stable'}</small></div></div>;}

function LifecycleRail({signal,events}:{signal:Signal;events:SignalEvent[]}){const ordered=['SIGNAL_NEW','LIMIT_FILLED','TP1_HIT','TP2_HIT','TP3_HIT'];const reached=new Set(events.map(x=>x.event));const terminal=[...events].reverse().find(x=>['INVALIDATED','LIMIT_EXPIRED','LIMIT_MISSED'].includes(x.event));return <div className="tv-lifecycle-panel tv-panel"><div className="tv-panel-head"><div><span className="eyebrow">Lifecycle engine</span><h3>Signal progression</h3></div><span>{signal.eventCount??events.length} events</span></div><div className="tv-lifecycle-rail">{ordered.map((event,index)=>{const hit=reached.has(event)||index===0&&signal.lastEvent==='SIGNAL_NEW';return <div key={event} className={`${hit?'done':''} ${signal.lastEvent===event?'current':''}`}><i>{hit?'✓':index+1}</i><strong>{words(event)}</strong><small>{events.find(x=>x.event===event)?.receivedAt?age(events.find(x=>x.event===event)?.receivedAt):'waiting'}</small></div>;})}{terminal&&<div className="terminal"><i>×</i><strong>{words(terminal.event)}</strong><small>{age(terminal.receivedAt)}</small></div>}</div></div>;}

function SignalCard({signal,selected,onSelect}:{signal:Signal;selected:boolean;onSelect:()=>void}){return <button className={`tv-feed-card ${sideClass(signal.side)} ${selected?'selected':''} ${isTestSignal(signal)?'test':''}`} onClick={onSelect}><div className="tv-feed-top"><span className={`tv-side ${sideClass(signal.side)}`}>{signal.side}</span><div><strong>{cleanSymbol(signal)}</strong><small>{signal.timeframe} · {signal.methodCode||`Method ${signal.methodId??'—'}`}</small></div><time>{age(signal.updatedAt)}</time></div><div className="tv-feed-source"><SourceBadge signal={signal}/><span>{words(signal.lastEvent)}</span></div><div className="tv-feed-bottom"><span>{isTestSignal(signal)?'Infrastructure verification':signal.intelligence.label}</span><strong>{isTestSignal(signal)?'TEST':signal.intelligence.score}</strong></div>{!isTestSignal(signal)&&<div className="tv-feed-progress"><i style={{width:`${signal.intelligence.score}%`}} /></div>}</button>;}
function FlagGrid({title,value}:{title:string;value:unknown}){const entries=boolEntries(value);if(!entries.length)return null;return <div className="tv-flag-group"><strong>{title}</strong><div>{entries.map(([key,on])=><span key={key} className={on?'on':'off'}><i></i>{words(key)}</span>)}</div></div>;}

function TelemetryPanel({payload}:{payload:Record<string,unknown>}){const telemetry=record(payload.telemetry);const current=parseMaybeJson(telemetry.current_snapshot);const signal=parseMaybeJson(telemetry.signal_snapshot);const snapshot=Object.keys(current).length?current:signal;const orderFlow=record(snapshot.order_flow);const indicator=record(snapshot.indicator_data);const structure=record(indicator.structure);const objects=record(indicator.objects);const currentEvidence=record(indicator.current_evidence);const priceData=record(snapshot.price_data);const candle=record(priceData.current);const mtf=record(priceData.mtf);if(!Object.keys(snapshot).length)return <div className="tv-mini-empty">No full telemetry snapshot is stored for this event.</div>;return <div className="tv-telemetry-grid"><div className="tv-telemetry-card"><span>Order flow proxy</span><strong>{words(orderFlow.dominance)}</strong><small>{words(orderFlow.quality)}</small><div className="tv-telemetry-numbers"><b>Δ {fmt(num(orderFlow.estimated_delta))}</b><b>Δ% {fmt(num(orderFlow.estimated_delta_pct))}</b><b>Vol {fmt(num(orderFlow.total_volume))}</b></div><p>{text(orderFlow.explanation)||'MT5 tick-volume derived diagnostic.'}</p></div><div className="tv-telemetry-card"><span>Structure snapshot</span><strong>{words(structure.signal_bias)}</strong><div className="tv-telemetry-numbers"><b>Internal {words(structure.internal_trend)}</b><b>Swing {words(structure.swing_trend)}</b><b>H4 {words(structure.h4)}</b><b>M15 {words(structure.m15)}</b><b>M1 {words(structure.m1)}</b></div></div><div className="tv-telemetry-card"><span>Object inventory</span><strong>Chart state</strong><div className="tv-telemetry-numbers"><b>Internal OB {String(objects.internal_ob_count??'—')}</b><b>Swing OB {String(objects.swing_ob_count??'—')}</b><b>Liquidity {String(objects.liquidity_level_count??'—')}</b><b>Zones {String(objects.advanced_zone_count??'—')}</b></div></div><div className="tv-telemetry-card"><span>Current candle</span><strong>{words(candle.direction)}</strong><div className="tv-telemetry-numbers"><b>O {fmt(num(candle.open))}</b><b>H {fmt(num(candle.high))}</b><b>L {fmt(num(candle.low))}</b><b>C {fmt(num(candle.close))}</b><b>Ticks {fmt(num(candle.tick_volume))}</b></div></div><div className="tv-telemetry-card wide"><span>Multi-timeframe price snapshot</span><div className="tv-mtf-bars">{(['h4','m15','m1'] as const).map(key=>{const bar=record(mtf[key]);return <div key={key}><strong>{key.toUpperCase()}</strong><span>{words(bar.direction)}</span><b>{fmt(num(bar.close))}</b></div>;})}</div></div><div className="tv-telemetry-card wide"><span>Live evidence inside MT5</span><FlagGrid title="Current evidence" value={currentEvidence}/></div></div>;}

export function TradingViewSignalIntelligence(){
  const [live,setLive]=useState<Signal[]>([]),[history,setHistory]=useState<Signal[]>([]),[metrics,setMetrics]=useState<Metrics>({});
  const [selectedId,setSelectedId]=useState(''),[detail,setDetail]=useState<SignalDetail|null>(null),[detailLoading,setDetailLoading]=useState(false);
  const [error,setError]=useState(''),[loading,setLoading]=useState(true),[socketState,setSocketState]=useState<'connecting'|'live'|'offline'>('connecting');
  const [symbol,setSymbol]=useState('ALL'),[timeframe,setTimeframe]=useState('ALL'),[side,setSide]=useState('ALL'),[source,setSource]=useState<SourceFilter>('ALL');
  const reloadRef=useRef<number|null>(null);
  const load=async()=>{try{const [l,h,m]=await Promise.all([getJson<SignalList>('/api/tradingview/signals/live?limit=120'),getJson<SignalList>('/api/tradingview/signals?limit=250'),getJson<Metrics>('/api/tradingview/signals/metrics')]);setLive(l.signals);setHistory(h.signals);setMetrics(m);setError('');setSelectedId(current=>current||l.signals.find(x=>!isTestSignal(x))?.id||h.signals.find(x=>!isTestSignal(x))?.id||h.signals[0]?.id||'');}catch(caught){setError(caught instanceof Error?caught.message:'FXGA live signal feed unavailable');}finally{setLoading(false);}};
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),15_000);return()=>window.clearInterval(timer);},[]);
  useEffect(()=>{if(!selectedId){setDetail(null);return;}let cancelled=false;setDetailLoading(true);void getJson<SignalDetail>(`/api/tradingview/signals/${selectedId}`).then(value=>{if(!cancelled)setDetail(value);}).catch(()=>{if(!cancelled)setDetail(null);}).finally(()=>{if(!cancelled)setDetailLoading(false);});return()=>{cancelled=true;};},[selectedId,history]);
  useEffect(()=>{let stopped=false,socket:WebSocket|null=null,retry:number|undefined;const connect=()=>{if(stopped)return;setSocketState('connecting');const protocol=location.protocol==='https:'?'wss:':'ws:';socket=new WebSocket(`${protocol}//${location.host}/api/live`);socket.onopen=()=>setSocketState('live');socket.onmessage=event=>{try{const message=JSON.parse(String(event.data));if(message.type==='tradingview-signal'){if(reloadRef.current)window.clearTimeout(reloadRef.current);reloadRef.current=window.setTimeout(()=>void load(),250);}}catch{}};socket.onclose=()=>{if(stopped)return;setSocketState('offline');retry=window.setTimeout(connect,3000);};socket.onerror=()=>socket?.close();};connect();return()=>{stopped=true;if(retry)window.clearTimeout(retry);if(reloadRef.current)window.clearTimeout(reloadRef.current);socket?.close();};},[]);
  const all=history;const symbols=useMemo(()=>['ALL',...Array.from(new Set(all.filter(x=>!isTestSignal(x)).map(x=>x.symbol))).sort()],[all]);const timeframes=useMemo(()=>['ALL',...Array.from(new Set(all.map(x=>x.timeframe))).sort()],[all]);const filtered=useMemo(()=>all.filter(x=>{const sourceMatch=source==='ALL'?true:source==='TESTS'?isTestSignal(x):!isTestSignal(x)&&sourceKind(x)===source;return (symbol==='ALL'||x.symbol===symbol)&&(timeframe==='ALL'||x.timeframe===timeframe)&&(side==='ALL'||x.side===side)&&sourceMatch;}),[all,symbol,timeframe,side,source]);
  const selected=all.find(x=>x.id===selectedId)||live.find(x=>!isTestSignal(x))||all.find(x=>!isTestSignal(x))||all[0]||null;const events=detail?.signal.id===selected?.id?detail.events:[];const latestPayload=events.length?record(events[events.length-1].payload):{};const method=record(latestPayload.smc_method);const evidence=record(latestPayload.smc_evidence_at_signal);const currentEvidence=record(latestPayload.current_market_evidence);const dealing=record(latestPayload.dealing_range);const dealingCurrent=record(dealing.current);const pd=record(latestPayload.pd_array);const testMeta=record(latestPayload.test_metadata);
  const realHistory=all.filter(x=>!isTestSignal(x));const tests=all.filter(isTestSignal);const mt5=realHistory.filter(x=>sourceKind(x)==='MT5');const tradingview=realHistory.filter(x=>sourceKind(x)==='TRADINGVIEW');const active=live.filter(x=>!isTestSignal(x)&&isActive(x));const liveMT5=active.filter(x=>sourceKind(x)==='MT5').length,liveTV=active.filter(x=>sourceKind(x)==='TRADINGVIEW').length;const sourceScore=selected?.methodScore??0;
  if(loading&&!all.length)return <section className="tv-shell"><div className="tv-empty"><span className="tv-pulse"></span><h2>Connecting to FXGA Live Signal Intelligence</h2><p>Google Cloud is opening the shared TradingView + MT5 SMC2000 ledger and real-time WebSocket channel.</p></div></section>;
  return <section className="tv-shell"><div className="tv-command-bar tv-command-upgraded"><div><span className="eyebrow">FXGA SMC2000 · MULTI-SOURCE LIVE DESK · fxga.smc.signal.v3</span><h2>Live Signal Intelligence</h2><p>One institutional view of every SMC2000 setup received from MetaTrader 5 and TradingView: source telemetry, lifecycle, trade geometry, hierarchy, evidence, order-flow proxy and full audit trail.</p><div className="tv-source-strip"><span className="mt5"><i></i>MT5 {liveMT5?'LIVE':'CONNECTED'} · {mt5.length} records</span><span className="tradingview"><i></i>TradingView {liveTV?'LIVE':'READY'} · {tradingview.length} records</span><span className="test"><i></i>Pipeline checks · {tests.length}</span></div></div><div className={`tv-live-state ${socketState}`}><span></span><strong>{socketState==='live'?'REALTIME':'CONNECTING'}</strong><small>{active.length} active · {metrics.totalEvents??0} events</small></div></div>{error&&<div className="alert error">{error}</div>}
    <div className="tv-source-kpis"><button className={source==='ALL'?'active':''} onClick={()=>setSource('ALL')}><span>All real signals</span><strong>{realHistory.length}</strong><small>MT5 + TradingView</small></button><button className={source==='MT5'?'active mt5':''} onClick={()=>setSource('MT5')}><span>MetaTrader 5</span><strong>{mt5.length}</strong><small>{liveMT5} active now</small></button><button className={source==='TRADINGVIEW'?'active tradingview':''} onClick={()=>setSource('TRADINGVIEW')}><span>TradingView</span><strong>{tradingview.length}</strong><small>{liveTV} active now</small></button><button className={source==='TESTS'?'active test':''} onClick={()=>setSource('TESTS')}><span>Pipeline tests</span><strong>{tests.length}</strong><small>infrastructure only</small></button><div><span>Lifecycle performance</span><strong>{metrics.tp3Rate??0}%</strong><small>TP3 · TP1 {metrics.tp1Rate??0}%</small></div></div>
    {!selected?<div className="tv-empty"><span className="tv-pulse"></span><h2>Signal infrastructure is ready</h2><p>MT5 and TradingView records will appear here as soon as the SMC2000 engines emit lifecycle events.</p></div>:<>{isTestSignal(selected)&&<div className="tv-test-banner"><div><span>PIPELINE VERIFICATION</span><strong>MT5 → Google Cloud Run → Firestore → FXGA Website</strong></div><b>NON-TRADING · CANCELLED · SAFE TEST</b><small>{text(testMeta.purpose)||'Synthetic infrastructure check'} · {age(selected.updatedAt)}</small></div>}
      <div className={`tv-hero ${sideClass(selected.side)} ${sourceKind(selected).toLowerCase()} ${isTestSignal(selected)?'test':''}`}><div className="tv-hero-main"><div className="tv-hero-heading"><div><span className={`tv-side large ${sideClass(isTestSignal(selected)?'WAIT':selected.intelligence.suggestedSignal)}`}>{isTestSignal(selected)?'TEST':selected.intelligence.suggestedSignal}</span><span className="tv-source-signal">Source {selected.side}</span></div><div><SourceBadge signal={selected}/><h2>{cleanSymbol(selected)} <em>{selected.timeframe}</em></h2><p>{selected.methodFamily||text(method.family)||'SMC2000'} · {selected.methodCode||text(method.code)||`Method ${selected.methodId??'—'}`}</p></div></div><div className="tv-guidance"><span className="eyebrow">{isTestSignal(selected)?'Infrastructure status':'FXGA contextual view'}</span><h3>{isTestSignal(selected)?'Production pipeline verified':selected.intelligence.label}</h3><p>{isTestSignal(selected)?'This record is synthetic and cancelled by design. It verifies transport, authentication, schema validation, Firestore persistence and website retrieval without representing a trade.':selected.intelligence.explanation}</p><div className="tv-state-row"><span>{words(selected.status)}</span><span>{words(selected.lastEvent)}</span><span>{age(selected.signalTime)}</span><span>{selected.eventCount??1} events</span></div></div>{!isTestSignal(selected)&&<Hierarchy signal={selected}/>}</div><div className="tv-hero-score" data-explain-key="confidence">{isTestSignal(selected)?<div className="tv-test-orb"><strong>200</strong><span>HTTP OK</span></div>:<ScoreRing score={selected.intelligence.score}/>}<div><span>{isTestSignal(selected)?'Pipeline state':'Contextual quality'}</span><strong>{isTestSignal(selected)?'VERIFIED':selected.intelligence.grade}</strong><small>{isTestSignal(selected)?sourceLabel(selected):`Method score ${pct(sourceScore)}`}</small></div></div>{isTestSignal(selected)?<div className="tv-test-facts"><div><span>Source</span><strong>MetaTrader 5</strong></div><div><span>Transport</span><strong>HTTPS POST</strong></div><div><span>Schema</span><strong>{selected.schema||'fxga.smc.signal.v3'}</strong></div><div><span>Status</span><strong>CANCELLED TEST</strong></div></div>:<TradePlanVisual signal={selected}/>}</div>
      {!isTestSignal(selected)&&<div className="tv-metrics tv-metrics-source"><div><span>Entry state</span><strong>{selected.lifecycle.entryFilled?'FILLED':'PENDING'}</strong><small>{words(selected.tradePlan.orderType)}</small></div><div><span>TP1</span><strong>{selected.lifecycle.tp1Hit?'HIT':'WAIT'}</strong><small>{fmt(selected.tradePlan.tp1)}</small></div><div><span>TP2</span><strong>{selected.lifecycle.tp2Hit?'HIT':'WAIT'}</strong><small>{fmt(selected.tradePlan.tp2)}</small></div><div><span>TP3</span><strong>{selected.lifecycle.finalTargetHit?'HIT':'WAIT'}</strong><small>{fmt(selected.tradePlan.tp3)}</small></div><div><span>Current price</span><strong>{fmt(selected.marketPrice)}</strong><small>{words(dealingCurrent.price_location)}</small></div></div>}
      <LifecycleRail signal={selected} events={events}/>
      <div className="tv-grid tv-grid-3"><div className="tv-panel tv-feed-panel"><div className="tv-panel-head"><div><span className="eyebrow">Live stream</span><h3>Source-aware feed</h3></div><span>{live.filter(x=>!isTestSignal(x)).length} active</span></div><div className="tv-feed">{live.filter(x=>!isTestSignal(x)).length?live.filter(x=>!isTestSignal(x)).map(item=><SignalCard key={item.id} signal={item} selected={item.id===selected.id} onSelect={()=>setSelectedId(item.id)}/>):<div className="tv-mini-empty">No active setups. Lifecycle history remains available below.</div>}</div>{tests.slice(0,2).map(item=><SignalCard key={item.id} signal={item} selected={item.id===selected.id} onSelect={()=>setSelectedId(item.id)}/>)}</div>
        <div className="tv-panel tv-method-panel"><div className="tv-panel-head"><div><span className="eyebrow">SMC2000 method DNA</span><h3>Why this setup exists</h3></div><span>{selected.exactMatches??num(method.exact_matching_methods)??'—'} exact</span></div><div className="tv-method-grid"><div><span>Family</span><strong>{selected.methodFamily||text(method.family)||'—'}</strong></div><div><span>Method</span><strong>{selected.methodCode||text(method.code)||selected.methodId||'—'}</strong></div><div><span>Context</span><strong>{words(method.context)}</strong></div><div><span>Liquidity event</span><strong>{words(method.liquidity_event)}</strong></div><div><span>Structure trigger</span><strong>{words(method.structure_trigger)}</strong></div><div><span>PD array</span><strong>{words(method.pd_array??pd.selected_type)}</strong></div><div><span>Confirmation</span><strong>{words(method.confirmation)}</strong></div><div><span>Primary target</span><strong>{words(method.primary_target??selected.tradePlan.primaryTargetType)}</strong></div></div>{text(method.logic_explanation)&&<p className="tv-logic">{text(method.logic_explanation)}</p>}<div className="tv-component-bars">{Object.entries(selected.intelligence.components).map(([key,value])=><div key={key}><span>{key.replace(/([A-Z])/g,' $1')}</span><i><b style={{width:`${value}%`}}/></i><strong>{Math.round(value)}</strong></div>)}</div></div>
        <div className="tv-panel tv-evidence-panel"><div className="tv-panel-head"><div><span className="eyebrow">Evidence matrix</span><h3>Signal + current state</h3></div><span>{detailLoading?'syncing':'live'}</span></div><FlagGrid title="Context" value={record(evidence.context_flags)}/><FlagGrid title="Liquidity" value={record(evidence.liquidity_flags)}/><FlagGrid title="Trigger" value={record(evidence.trigger_flags)}/><FlagGrid title="PD Array" value={record(evidence.pd_array_flags)}/><FlagGrid title="Confirmation" value={record(evidence.confirmation_flags)}/><FlagGrid title="Fresh execution" value={record(evidence.fresh_execution_flags)}/><FlagGrid title="Current market" value={currentEvidence}/></div></div>
      {sourceKind(selected)==='MT5'&&<div className="tv-panel tv-telemetry-panel"><div className="tv-panel-head"><div><span className="eyebrow">MetaTrader 5 full telemetry</span><h3>Terminal snapshot received by Google Cloud</h3></div><span>{text(record(latestPayload.telemetry).snapshot_contract)||'PRICE · ORDER FLOW · INDICATOR'}</span></div><TelemetryPanel payload={latestPayload}/></div>}
      {!isTestSignal(selected)&&<div className="tv-grid"><div className="tv-panel"><div className="tv-panel-head"><div><span className="eyebrow">Price geometry</span><h3>Dealing range & PD array</h3></div><span>{words(dealingCurrent.price_location)}</span></div><div className="tv-range-grid"><div><span>Range high</span><strong>{fmt(num(dealingCurrent.high))}</strong></div><div><span>Equilibrium</span><strong>{fmt(num(dealingCurrent.equilibrium))}</strong></div><div><span>Range low</span><strong>{fmt(num(dealingCurrent.low))}</strong></div><div><span>Zone top</span><strong>{fmt(num(pd.zone_top))}</strong></div><div><span>Zone bottom</span><strong>{fmt(num(pd.zone_bottom))}</strong></div><div><span>Price in zone</span><strong>{pd.current_price_inside_zone===true?'YES':'NO'}</strong></div></div></div><div className="tv-panel"><div className="tv-panel-head"><div><span className="eyebrow">Invalidation discipline</span><h3>When this setup is dead</h3></div><span>{fmt(selected.invalidation?.structural_stop)}</span></div><p className="tv-invalidation-copy">{selected.invalidation?.explanation||`Structural stop ${fmt(selected.tradePlan.stopLoss)} defines where the SMC2000 setup is no longer valid.`}</p><div className="tv-state-row"><span>SL {fmt(selected.tradePlan.stopLoss)}</span><span>Zone {fmt(num(pd.zone_bottom))} → {fmt(num(pd.zone_top))}</span><span>{words(selected.lastReason)}</span></div></div></div>}
      <div className="tv-panel tv-history-panel"><div className="tv-panel-head"><div><span className="eyebrow">Unified audit trail</span><h3>MT5 + TradingView signal history</h3></div><div className="tv-filters"><select value={source} onChange={e=>setSource(e.target.value as SourceFilter)}><option>ALL</option><option>MT5</option><option>TRADINGVIEW</option><option>TESTS</option></select><select value={symbol} onChange={e=>setSymbol(e.target.value)}>{symbols.map(x=><option key={x}>{x}</option>)}</select><select value={timeframe} onChange={e=>setTimeframe(e.target.value)}>{timeframes.map(x=><option key={x}>{x}</option>)}</select><select value={side} onChange={e=>setSide(e.target.value)}><option>ALL</option><option>BUY</option><option>SELL</option></select></div></div><div className="tv-table"><div className="tv-table-row head upgraded"><span>Source</span><span>Signal</span><span>Method</span><span>Entry</span><span>SL</span><span>TP3</span><span>RR</span><span>FXGA score</span><span>Status</span><span>Updated</span></div>{filtered.map(item=><button key={item.id} className={`tv-table-row upgraded ${item.id===selected.id?'active':''} ${isTestSignal(item)?'test':''}`} onClick={()=>setSelectedId(item.id)}><span><SourceBadge signal={item}/></span><span><b className={sideClass(item.side)}>{isTestSignal(item)?'TEST':item.side}</b> {cleanSymbol(item)} · {item.timeframe}</span><span>{item.methodCode||item.methodId||'—'}</span><span>{isTestSignal(item)?'—':fmt(item.tradePlan.entry)}</span><span>{isTestSignal(item)?'—':fmt(item.tradePlan.stopLoss)}</span><span>{isTestSignal(item)?'—':fmt(item.tradePlan.tp3)}</span><span>{isTestSignal(item)?'—':`${item.riskReward.rrTp3?.toFixed(2)??'—'}R`}</span><span>{isTestSignal(item)?<strong>PIPELINE</strong>:<><strong>{item.intelligence.score}</strong> {item.intelligence.grade}</>}</span><span>{words(item.status)}</span><span>{age(item.updatedAt)}</span></button>)}</div></div>
      {Object.keys(latestPayload).length>0&&<details className="tv-raw-panel"><summary><span>Raw event inspector</span><strong>{events.length} lifecycle payloads · latest {words(selected.lastEvent)}</strong></summary><div className="tv-raw-meta"><span>Schema {text(latestPayload.schema)||selected.schema}</span><span>Source {text(latestPayload.source)||selected.source}</span><span>Engine {text(latestPayload.engine)||selected.engine}</span><span>Stream {text(latestPayload.stream)||selected.stream}</span></div><pre>{JSON.stringify(latestPayload,null,2)}</pre></details>}
      <div className="tv-risk-note"><strong>Decision-support boundary</strong><span>MT5 and TradingView are shown as source telemetry exactly as received, with Google Cloud contextualization layered separately.</span><small>Pipeline-test records are visibly isolated and non-trading. Live signals remain research/decision support; the website does not place broker orders or guarantee outcomes.</small></div>
    </>}</section>;
}
