from pathlib import Path


def replace_once(text,old,new,label):
    c=text.count(old)
    if c!=1: raise SystemExit(f'{label}: expected 1 anchor, found {c}')
    return text.replace(old,new,1)

path=Path('cloud-run-collector/src/institutional-research.js')
text=path.read_text(encoding='utf-8')
anchor="function buildFeatures(observations=[]){\n"
fn="""function correlation(a,b){
  const n=Math.min(a.length,b.length);if(n<6)return null;const x=a.slice(-n),y=b.slice(-n),mx=mean(x),my=mean(y),sx=Math.sqrt(x.reduce((s,v)=>s+(v-mx)**2,0)),sy=Math.sqrt(y.reduce((s,v)=>s+(v-my)**2,0));if(sx<1e-12||sy<1e-12)return null;return x.reduce((s,v,i)=>s+(v-mx)*(y[i]-my),0)/(sx*sy);
}
function seriesChanges(item){const values=(item?.history||[]).map(x=>num(x?.value)).filter(Number.isFinite),diffs=[];for(let i=1;i<values.length;i++)diffs.push(values[i]-values[i-1]);return diffs.slice(-16);}
function buildEvidenceIndependence(observations=[],sourceReliability=[]){
  const reliability=new Map((sourceReliability||[]).map(x=>[String(x.source||''),Number(x.score||0)])),groups=new Map();
  for(const item of observations){const economy=item?.economy||item?.economies?.[0]||'GLOBAL',family=macroFamily(item),changes=seriesChanges(item);if(changes.length<6)continue;const key=`${economy}:${family}`,arr=groups.get(key)||[];arr.push({seriesId:item.seriesId,title:item.title,source:String(item.source||'Unknown'),changes,historyDepth:Array.isArray(item.history)?item.history.length:0});groups.set(key,arr);}
  const rows=[];
  for(const [key,items] of groups){const [economy,family]=key.split(':'),parent=items.map((_,i)=>i),find=i=>{while(parent[i]!==i){parent[i]=parent[parent[i]];i=parent[i];}return i;},union=(a,b)=>{a=find(a);b=find(b);if(a!==b)parent[b]=a;},links=[];for(let i=0;i<items.length;i++)for(let j=i+1;j<items.length;j++){const r=correlation(items[i].changes,items[j].changes);if(Number.isFinite(r)&&Math.abs(r)>=.92){union(i,j);links.push({a:items[i].seriesId,b:items[j].seriesId,correlation:Number(r.toFixed(3))});}}const clustersMap=new Map();items.forEach((item,i)=>{const root=find(i),arr=clustersMap.get(root)||[];arr.push(item);clustersMap.set(root,arr);});const clusters=[...clustersMap.values()].map(cluster=>{const ranked=[...cluster].sort((a,b)=>(reliability.get(b.source)||0)-(reliability.get(a.source)||0)||b.historyDepth-a.historyDepth),representative=ranked[0];return {representative:representative.seriesId,representativeSource:representative.source,series:cluster.map(x=>x.seriesId),size:cluster.length};}).sort((a,b)=>b.size-a.size),rawSignals=items.length,effectiveSignals=clusters.length,independenceRatio=rawSignals?effectiveSignals/rawSignals:1,redundancyRatio=1-independenceRatio;rows.push({economy,family,rawSignals,effectiveSignals,independenceRatio:Number(independenceRatio.toFixed(3)),redundancyRatio:Number(redundancyRatio.toFixed(3)),status:independenceRatio<.5?'high-redundancy':independenceRatio<.72?'overlapping':'independent',clusters:clusters.slice(0,12),highCorrelationLinks:links.slice(0,30)});}
  const economyMap=new Map();for(const row of rows){const arr=economyMap.get(row.economy)||[];arr.push(row);economyMap.set(row.economy,arr);}const economies=[...economyMap.entries()].map(([economy,items])=>{const raw=items.reduce((s,x)=>s+x.rawSignals,0),effective=items.reduce((s,x)=>s+x.effectiveSignals,0),ratio=raw?effective/raw:1;return {economy,rawSignals:raw,effectiveSignals:effective,independenceRatio:Number(ratio.toFixed(3)),redundancyRatio:Number((1-ratio).toFixed(3)),status:ratio<.5?'high-redundancy':ratio<.72?'overlapping':'independent',families:items.sort((a,b)=>a.independenceRatio-b.independenceRatio)};}).sort((a,b)=>a.independenceRatio-b.independenceRatio);
  const rawTotal=rows.reduce((s,x)=>s+x.rawSignals,0),effectiveTotal=rows.reduce((s,x)=>s+x.effectiveSignals,0),ratio=rawTotal?effectiveTotal/rawTotal:1;return {generatedAt:iso(),rawSignals:rawTotal,effectiveSignals:effectiveTotal,independenceRatio:Number(ratio.toFixed(3)),redundancyRatio:Number((1-ratio).toFixed(3)),economies,rows:rows.sort((a,b)=>a.independenceRatio-b.independenceRatio),correlationThreshold:.92};
}

"""
text=replace_once(text,anchor,fn+anchor,'evidence independence function')
text=replace_once(text,
"  const sourceReliability=buildSourceReliability(observations);\n  const features=buildFeatures(observations);\n",
"  const sourceReliability=buildSourceReliability(observations);\n  const evidenceIndependence=buildEvidenceIndependence(observations,sourceReliability);\n  const features=buildFeatures(observations);\n",
'independence build')
text=replace_once(text,
"    dataQuality,sourceReliability,modelHealth,turningPoints,catalystSequence,features:features.slice(0,220),forecasts,releaseAnalytics,marketAnalytics,regimes,risk,scenarios,\n",
"    dataQuality,sourceReliability,evidenceIndependence,modelHealth,turningPoints,catalystSequence,features:features.slice(0,220),forecasts,releaseAnalytics,marketAnalytics,regimes,risk,scenarios,\n",
'independence output')
text=text.replace("'feature-engineering','walk-forward-model-calibration'","'feature-engineering','correlated-evidence-clustering','effective-independent-coverage','walk-forward-model-calibration'",1)
path.write_text(text,encoding='utf-8')

path=Path('cloud-run-collector/src/decision-intelligence-core.js')
text=path.read_text(encoding='utf-8')
anchor="function transitionRiskControls(research,symbol){\n"
fn="""function evidenceIndependenceControls(research,symbol){
  const [base,quote]=currenciesForSymbol(symbol),lookup=currency=>research?.evidenceIndependence?.economies?.find(x=>x.economy===ECONOMY_BY_CURRENCY[currency])||null,baseRow=base==='XAU'?null:lookup(base),quoteRow=lookup(quote),ratios=[baseRow?.independenceRatio,quoteRow?.independenceRatio].filter(Number.isFinite),ratio=ratios.length?mean(ratios):Number(research?.evidenceIndependence?.independenceRatio||1),factor=clamp(.72+.28*ratio,.72,1),status=ratio<.5?'high-redundancy':ratio<.72?'overlapping':'independent';return {status,independenceRatio:Number(ratio.toFixed(3)),factor:Number(factor.toFixed(3)),base:baseRow,quote:quoteRow,globalRatio:Number(research?.evidenceIndependence?.independenceRatio||1)};
}
"""
text=replace_once(text,anchor,fn+anchor,'independence control function')
text=replace_once(text,
"  const scenarioFactor=Number(controls?.scenario?.factor||.88),riskPenalty=Number(controls?.risk?.riskPenalty||.82),researchQuality=Number(controls?.risk?.qualityFactor||.82),modelFactor=Number(controls?.modelHealth?.factor||.82),historyFactor=Number(controls?.historicalCalibration?.factor||1),counterfactualFactor=Number(controls?.counterfactual?.factor||1),temporalFactor=Number(controls?.temporal?.factor||1),transitionFactor=Number(controls?.transitionRisk?.factor||1),uncertaintyPenalty=clamp(1-Number(controls?.uncertainty?.total||.5)*.35,.62,1);\n  const confidence=Math.round(100*Math.min(maxDirectional,Number(opportunity.confidence||0)/100||maxDirectional)*contradictions.penalty*Math.max(.45,quality.score/100)*scenarioFactor*riskPenalty*researchQuality*modelFactor*historyFactor*counterfactualFactor*temporalFactor*transitionFactor*uncertaintyPenalty);\n",
"  const scenarioFactor=Number(controls?.scenario?.factor||.88),riskPenalty=Number(controls?.risk?.riskPenalty||.82),researchQuality=Number(controls?.risk?.qualityFactor||.82),modelFactor=Number(controls?.modelHealth?.factor||.82),historyFactor=Number(controls?.historicalCalibration?.factor||1),counterfactualFactor=Number(controls?.counterfactual?.factor||1),temporalFactor=Number(controls?.temporal?.factor||1),transitionFactor=Number(controls?.transitionRisk?.factor||1),independenceFactor=Number(controls?.evidenceIndependence?.factor||1),uncertaintyPenalty=clamp(1-Number(controls?.uncertainty?.total||.5)*.35,.62,1);\n  const confidence=Math.round(100*Math.min(maxDirectional,Number(opportunity.confidence||0)/100||maxDirectional)*contradictions.penalty*Math.max(.45,quality.score/100)*scenarioFactor*riskPenalty*researchQuality*modelFactor*historyFactor*counterfactualFactor*temporalFactor*transitionFactor*independenceFactor*uncertaintyPenalty);\n",
'independence confidence factor')
old="""    const marketSignal=marketAssetSignal(opportunity.symbol,marketData),expectationGap=expectationGapForPair(opportunity,events,marketData,nowMs),bayesian=bayesianPosterior(opportunity,marketSignal,expectationGap,quality),contradictions=contradictionAudit(opportunity,bayesian.posterior,marketSignal,expectationGap),refined=refinedPairScore(opportunity,expectationGap,marketSignal,contradictions),causalTransmission=causalTransmissionForPair(opportunity,economies,marketSignal),counterfactual=counterfactualSensitivity(refined),temporal=temporalIntelligenceForPair(opportunity,events,news,economies,nowMs),transitionRisk=transitionRiskControls(research,opportunity.symbol),catalysts=nearestCatalysts(events,opportunity.symbol,nowMs),preferred=bayesian.posterior.buy>=bayesian.posterior.sell?'BUY':'SELL',scenario=scenarioRobustness(research,opportunity.symbol,preferred),risk=researchRiskControls(research),modelHealth=modelHealthControls(research),historicalCalibration=historicalCalibrationControls(decisionMemory,opportunity.symbol),uncertainty=uncertaintyDecomposition(bayesian.posterior,contradictions,quality,expectationGap,scenario,risk),premortem=buildPremortem(opportunity,contradictions,expectationGap,scenario,risk,quality),thesis=thesisForPair(opportunity,bayesian.posterior,refined,contradictions,catalysts,quality,expectationGap),final=finalDecision(opportunity,bayesian.posterior,refined,contradictions,quality,{scenario,risk,modelHealth,historicalCalibration,counterfactual,temporal,transitionRisk,uncertainty});\n    return {symbol:opportunity.symbol,originalDirection:opportunity.direction,originalScore:Number(opportunity.score||0),quality,bayesian,expectationGap,marketSignal,contradictions,refined,causalTransmission,counterfactual,temporalIntelligence:temporal,transitionRisk,scenarioRobustness:scenario,riskControls:risk,modelHealth,historicalCalibration,uncertainty,premortem,thesis,final};\n"""
new="""    const marketSignal=marketAssetSignal(opportunity.symbol,marketData),expectationGap=expectationGapForPair(opportunity,events,marketData,nowMs),bayesian=bayesianPosterior(opportunity,marketSignal,expectationGap,quality),contradictions=contradictionAudit(opportunity,bayesian.posterior,marketSignal,expectationGap),refined=refinedPairScore(opportunity,expectationGap,marketSignal,contradictions),causalTransmission=causalTransmissionForPair(opportunity,economies,marketSignal),counterfactual=counterfactualSensitivity(refined),temporal=temporalIntelligenceForPair(opportunity,events,news,economies,nowMs),transitionRisk=transitionRiskControls(research,opportunity.symbol),evidenceIndependence=evidenceIndependenceControls(research,opportunity.symbol),catalysts=nearestCatalysts(events,opportunity.symbol,nowMs),preferred=bayesian.posterior.buy>=bayesian.posterior.sell?'BUY':'SELL',scenario=scenarioRobustness(research,opportunity.symbol,preferred),risk=researchRiskControls(research),modelHealth=modelHealthControls(research),historicalCalibration=historicalCalibrationControls(decisionMemory,opportunity.symbol),uncertainty=uncertaintyDecomposition(bayesian.posterior,contradictions,quality,expectationGap,scenario,risk),premortem=buildPremortem(opportunity,contradictions,expectationGap,scenario,risk,quality),thesis=thesisForPair(opportunity,bayesian.posterior,refined,contradictions,catalysts,quality,expectationGap),final=finalDecision(opportunity,bayesian.posterior,refined,contradictions,quality,{scenario,risk,modelHealth,historicalCalibration,counterfactual,temporal,transitionRisk,evidenceIndependence,uncertainty});\n    return {symbol:opportunity.symbol,originalDirection:opportunity.direction,originalScore:Number(opportunity.score||0),quality,bayesian,expectationGap,marketSignal,contradictions,refined,causalTransmission,counterfactual,temporalIntelligence:temporal,transitionRisk,evidenceIndependence,scenarioRobustness:scenario,riskControls:risk,modelHealth,historicalCalibration,uncertainty,premortem,thesis,final};\n"""
text=replace_once(text,old,new,'pair independence output')
text=text.replace("'common-currency concentration is governed separately from single-pair conviction'","'common-currency concentration is governed separately from single-pair conviction','highly correlated macro series are clustered so apparent breadth cannot masquerade as independent evidence'",1)
path.write_text(text,encoding='utf-8')
print('Evidence independence upgrade applied.')
