from pathlib import Path


def replace_once(text,old,new,label):
    c=text.count(old)
    if c!=1: raise SystemExit(f'{label}: expected 1 anchor, found {c}')
    return text.replace(old,new,1)

path=Path('cloud-run-collector/src/decision-intelligence-core.js')
text=path.read_text(encoding='utf-8')
anchor="function evidenceGraph(pairDecisions,quality){\n"
fn="""function recentReleaseSequence(events,currency,nowMs){
  const rows=(events||[]).filter(e=>String(e?.currency||'').toUpperCase()===currency).map(e=>({...e,t:Date.parse(e?.date||'')})).filter(e=>Number.isFinite(e.t)&&e.t<=nowMs&&e.t>=nowMs-7*86400000&&e.actual!==undefined&&e.actual!=='').sort((a,b)=>b.t-a.t).slice(0,12);
  let num=0,den=0;for(const e of rows){const bias=Number(e.currencyBiasScore??(e.currencyBias==='bullish'?1:e.currencyBias==='bearish'?-1:0)),impact=Math.max(1,Math.min(3,Number(e.importance||1)))/3,ageHours=(nowMs-e.t)/3600000,decay=Math.exp(-Math.log(2)*ageHours/48),w=impact*decay;num+=bias*w;den+=w;}
  const score=den?Math.round(100*num/den):0,nonNeutral=rows.map(e=>Number(e.currencyBiasScore??(e.currencyBias==='bullish'?1:e.currencyBias==='bearish'?-1:0))).filter(Boolean);let streak=0,streakSign=nonNeutral[0]||0;for(const value of nonNeutral){if(value===streakSign)streak++;else break;}
  const latest=rows.slice(0,3),prior=rows.slice(3,6),avg=(xs)=>xs.length?mean(xs.map(e=>Number(e.currencyBiasScore??(e.currencyBias==='bullish'?1:e.currencyBias==='bearish'?-1:0)))):0,acceleration=Math.round(100*(avg(latest)-avg(prior)));
  return {currency,score,count:rows.length,streak:streakSign===0?0:streak*streakSign,acceleration,consistency:Number((Math.abs(num)/Math.max(den,1e-9)).toFixed(4)),latest:rows.slice(0,5).map(e=>({event:e.event,date:e.date,importance:Number(e.importance||1),bias:e.currencyBias||'neutral',biasScore:Number(e.currencyBiasScore||0)})),status:rows.length<2?'insufficient':score>=25?'bullish-sequence':score<=-25?'bearish-sequence':'mixed'};
}
function revisionSequence(events,currency,nowMs){
  const items=[];for(const e of events||[]){if(String(e?.currency||'').toUpperCase()!==currency)continue;const t=Date.parse(e?.date||'');if(!Number.isFinite(t)||t>nowMs||t<nowMs-14*86400000)continue;const revised=numeric(e?.revised),previous=numeric(e?.previous);if(revised==null||previous==null||Math.abs(revised-previous)<1e-12)continue;const orientation=eventOrientation(e),raw=(revised-previous),scale=Math.max(Math.abs(previous)*.005,Math.abs(raw),1e-9),score=clamp(raw/scale,-1,1)*orientation;items.push({event:e.event,date:e.date,previous,revised,score});}
  items.sort((a,b)=>Date.parse(b.date)-Date.parse(a.date));const recent=items.slice(0,8),score=recent.length?Math.round(100*mean(recent.map((x,i)=>x.score*Math.exp(-Math.log(2)*i/3)))):0;
  return {currency,score,count:recent.length,status:recent.length<2?'insufficient':score>=20?'supportive-revisions':score<=-20?'adverse-revisions':'mixed',items:recent.slice(0,5)};
}
const NEWS_CURRENCY={"United States":'USD','Euro Area':'EUR','United Kingdom':'GBP','South Africa':'ZAR','Japan':'JPY'};
function policyCommunication(news,currency,nowMs){
  const items=(news||[]).filter(item=>NEWS_CURRENCY[item?.region]===currency&&item?.policyTone&&Date.parse(item?.publishedAt||'')<=nowMs&&Date.parse(item?.publishedAt||'')>=nowMs-7*86400000).map(item=>{const ageHours=(nowMs-Date.parse(item.publishedAt))/3600000,w=Math.max(.2,Number(item.policyTone?.confidence||20)/100)*Math.exp(-Math.log(2)*ageHours/72);return {title:item.title,publishedAt:item.publishedAt,score:Number(item.policyTone?.score||0),stance:item.policyTone?.stance||'balanced',confidence:Number(item.policyTone?.confidence||0),weight:w};}).sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt));
  const den=items.reduce((s,x)=>s+x.weight,0),score=den?Math.round(items.reduce((s,x)=>s+x.score*x.weight,0)/den):0;return {currency,score,count:items.length,status:items.length<1?'insufficient':score>=18?'hawkish':score<=-18?'dovish':'balanced',items:items.slice(0,5)};
}
function temporalIntelligenceForPair(opportunity,events,news,economies,nowMs){
  const [base,quote]=currenciesForSymbol(opportunity.symbol),baseSeq=base==='XAU'?{score:0,count:0,status:'not-applicable'}:recentReleaseSequence(events,base,nowMs),quoteSeq=recentReleaseSequence(events,quote,nowMs),baseRev=base==='XAU'?{score:0,count:0,status:'not-applicable'}:revisionSequence(events,base,nowMs),quoteRev=revisionSequence(events,quote,nowMs),baseComm=base==='XAU'?{score:0,count:0,status:'not-applicable'}:policyCommunication(news,base,nowMs),quoteComm=policyCommunication(news,quote,nowMs),releaseDifferential=(base==='XAU'?-quoteSeq.score:baseSeq.score-quoteSeq.score),revisionDifferential=(base==='XAU'?-quoteRev.score:baseRev.score-quoteRev.score),direction=Math.sign(Number(opportunity?.score||0))||1;
  const baseState=economyStateForCurrency(economies,base),quoteState=economyStateForCurrency(economies,quote),stanceScore=s=>s?.policyStance==='hawkish'?65:s?.policyStance==='dovish'?-65:0,baseGap=base==='XAU'?0:baseComm.score-stanceScore(baseState),quoteGap=quoteComm.score-stanceScore(quoteState),communicationGap=Math.max(Math.abs(baseGap),Math.abs(quoteGap));
  const related=(events||[]).filter(e=>[base,quote].includes(String(e?.currency||'').toUpperCase())).map(e=>({...e,t:Date.parse(e?.date||'')})).filter(e=>Number.isFinite(e.t));const completed=related.filter(e=>e.t<=nowMs).sort((a,b)=>b.t-a.t),upcoming=related.filter(e=>e.t>nowMs).sort((a,b)=>a.t-b.t),lastHigh=completed.find(e=>Number(e.importance||1)>=3),nextHigh=upcoming.find(e=>Number(e.importance||1)>=3),catalystAgeHours=lastHigh?Math.round((nowMs-lastHigh.t)/3600000):null;
  const releaseConflict=Math.abs(releaseDifferential)>=30&&Math.sign(releaseDifferential)!==direction,revisionConflict=Math.abs(revisionDifferential)>=30&&Math.sign(revisionDifferential)!==direction,communicationConflict=communicationGap>=45,staleCatalyst=catalystAgeHours!=null&&catalystAgeHours>96&&!nextHigh;
  const factor=clamp(1-(releaseConflict?.09:0)-(revisionConflict?.06:0)-(communicationConflict?.07:0)-(staleCatalyst?.05:0),.73,1),conflicts=[releaseConflict?'release-sequence':null,revisionConflict?'revision-sequence':null,communicationConflict?'policy-communication-gap':null,staleCatalyst?'stale-catalyst':null].filter(Boolean);
  return {symbol:opportunity.symbol,factor:Number(factor.toFixed(3)),status:conflicts.length>=3?'contested':conflicts.length?'mixed':'aligned',conflicts,releaseDifferential,revisionDifferential,communicationGap,base:{release:baseSeq,revisions:baseRev,communication:baseComm,policyCommunicationGap:baseGap},quote:{release:quoteSeq,revisions:quoteRev,communication:quoteComm,policyCommunicationGap:quoteGap},catalysts:{lastHighImpact:lastHigh?{event:lastHigh.event,currency:lastHigh.currency,date:lastHigh.date}:null,nextHighImpact:nextHigh?{event:nextHigh.event,currency:nextHigh.currency,date:nextHigh.date,minutes:Math.round((nextHigh.t-nowMs)/60000)}:null,catalystAgeHours}};
}
"""
text=replace_once(text,anchor,fn+anchor,'temporal intelligence functions')
text=replace_once(text,
"  const scenarioFactor=Number(controls?.scenario?.factor||.88),riskPenalty=Number(controls?.risk?.riskPenalty||.82),researchQuality=Number(controls?.risk?.qualityFactor||.82),modelFactor=Number(controls?.modelHealth?.factor||.82),historyFactor=Number(controls?.historicalCalibration?.factor||1),counterfactualFactor=Number(controls?.counterfactual?.factor||1),uncertaintyPenalty=clamp(1-Number(controls?.uncertainty?.total||.5)*.35,.62,1);\n  const confidence=Math.round(100*Math.min(maxDirectional,Number(opportunity.confidence||0)/100||maxDirectional)*contradictions.penalty*Math.max(.45,quality.score/100)*scenarioFactor*riskPenalty*researchQuality*modelFactor*historyFactor*counterfactualFactor*uncertaintyPenalty);\n",
"  const scenarioFactor=Number(controls?.scenario?.factor||.88),riskPenalty=Number(controls?.risk?.riskPenalty||.82),researchQuality=Number(controls?.risk?.qualityFactor||.82),modelFactor=Number(controls?.modelHealth?.factor||.82),historyFactor=Number(controls?.historicalCalibration?.factor||1),counterfactualFactor=Number(controls?.counterfactual?.factor||1),temporalFactor=Number(controls?.temporal?.factor||1),uncertaintyPenalty=clamp(1-Number(controls?.uncertainty?.total||.5)*.35,.62,1);\n  const confidence=Math.round(100*Math.min(maxDirectional,Number(opportunity.confidence||0)/100||maxDirectional)*contradictions.penalty*Math.max(.45,quality.score/100)*scenarioFactor*riskPenalty*researchQuality*modelFactor*historyFactor*counterfactualFactor*temporalFactor*uncertaintyPenalty);\n",
'temporal confidence factor')
text=replace_once(text,
"  if(controls?.counterfactual?.fragility==='high'&&Number(controls.counterfactual.minimumAdverseShift||99)<=10){direction='WAIT';reason.push('The thesis is too sensitive to a small adverse change in a key assumption.');}\n",
"  if(controls?.counterfactual?.fragility==='high'&&Number(controls.counterfactual.minimumAdverseShift||99)<=10){direction='WAIT';reason.push('The thesis is too sensitive to a small adverse change in a key assumption.');}\n  if(controls?.temporal?.status==='contested'&&Number(controls.temporal.factor||1)<=.80){direction='WAIT';reason.push('Recent release, revision and policy-communication timing evidence materially contests the thesis.');}\n",
'temporal veto')
old="""    const marketSignal=marketAssetSignal(opportunity.symbol,marketData),expectationGap=expectationGapForPair(opportunity,events,marketData,nowMs),bayesian=bayesianPosterior(opportunity,marketSignal,expectationGap,quality),contradictions=contradictionAudit(opportunity,bayesian.posterior,marketSignal,expectationGap),refined=refinedPairScore(opportunity,expectationGap,marketSignal,contradictions),causalTransmission=causalTransmissionForPair(opportunity,economies,marketSignal),counterfactual=counterfactualSensitivity(refined),catalysts=nearestCatalysts(events,opportunity.symbol,nowMs),preferred=bayesian.posterior.buy>=bayesian.posterior.sell?'BUY':'SELL',scenario=scenarioRobustness(research,opportunity.symbol,preferred),risk=researchRiskControls(research),modelHealth=modelHealthControls(research),historicalCalibration=historicalCalibrationControls(decisionMemory,opportunity.symbol),uncertainty=uncertaintyDecomposition(bayesian.posterior,contradictions,quality,expectationGap,scenario,risk),premortem=buildPremortem(opportunity,contradictions,expectationGap,scenario,risk,quality),thesis=thesisForPair(opportunity,bayesian.posterior,refined,contradictions,catalysts,quality,expectationGap),final=finalDecision(opportunity,bayesian.posterior,refined,contradictions,quality,{scenario,risk,modelHealth,historicalCalibration,counterfactual,uncertainty});
    return {symbol:opportunity.symbol,originalDirection:opportunity.direction,originalScore:Number(opportunity.score||0),quality,bayesian,expectationGap,marketSignal,contradictions,refined,causalTransmission,counterfactual,scenarioRobustness:scenario,riskControls:risk,modelHealth,historicalCalibration,uncertainty,premortem,thesis,final};
"""
new="""    const marketSignal=marketAssetSignal(opportunity.symbol,marketData),expectationGap=expectationGapForPair(opportunity,events,marketData,nowMs),bayesian=bayesianPosterior(opportunity,marketSignal,expectationGap,quality),contradictions=contradictionAudit(opportunity,bayesian.posterior,marketSignal,expectationGap),refined=refinedPairScore(opportunity,expectationGap,marketSignal,contradictions),causalTransmission=causalTransmissionForPair(opportunity,economies,marketSignal),counterfactual=counterfactualSensitivity(refined),temporal=temporalIntelligenceForPair(opportunity,events,news,economies,nowMs),catalysts=nearestCatalysts(events,opportunity.symbol,nowMs),preferred=bayesian.posterior.buy>=bayesian.posterior.sell?'BUY':'SELL',scenario=scenarioRobustness(research,opportunity.symbol,preferred),risk=researchRiskControls(research),modelHealth=modelHealthControls(research),historicalCalibration=historicalCalibrationControls(decisionMemory,opportunity.symbol),uncertainty=uncertaintyDecomposition(bayesian.posterior,contradictions,quality,expectationGap,scenario,risk),premortem=buildPremortem(opportunity,contradictions,expectationGap,scenario,risk,quality),thesis=thesisForPair(opportunity,bayesian.posterior,refined,contradictions,catalysts,quality,expectationGap),final=finalDecision(opportunity,bayesian.posterior,refined,contradictions,quality,{scenario,risk,modelHealth,historicalCalibration,counterfactual,temporal,uncertainty});
    return {symbol:opportunity.symbol,originalDirection:opportunity.direction,originalScore:Number(opportunity.score||0),quality,bayesian,expectationGap,marketSignal,contradictions,refined,causalTransmission,counterfactual,temporalIntelligence:temporal,scenarioRobustness:scenario,riskControls:risk,modelHealth,historicalCalibration,uncertainty,premortem,thesis,final};
"""
text=replace_once(text,old,new,'pair temporal output')
text=text.replace("'small counterfactual shocks can veto fragile theses'","'small counterfactual shocks can veto fragile theses','release sequences, revisions, communications and catalyst age are governed as temporal evidence without double-counting them in the posterior'",1)
path.write_text(text,encoding='utf-8')

path=Path('cloud-run-collector/src/super-economist.js')
text=path.read_text(encoding='utf-8')
text=text.replace("'historical-decision-calibration','thesis-invalidation'","'historical-decision-calibration','release-sequence','revision-intelligence','policy-communication-gap','catalyst-decay','thesis-invalidation'",1)
path.write_text(text,encoding='utf-8')
print('Temporal intelligence upgrade applied.')
