from pathlib import Path


def replace_once(path, old, new):
    p=Path(path)
    text=p.read_text()
    if new in text:
        return False
    if old not in text:
        raise SystemExit(f'Anchor missing in {path}: {old[:180]!r}')
    p.write_text(text.replace(old,new,1))
    return True

schedule_module = r'''import { load as loadHtml } from 'cheerio';
import { policyDecisionKey } from './policy-catalyst-horizon.js';

const MONTHS={january:1,february:2,march:3,april:4,may:5,june:6,july:7,august:8,september:9,october:10,november:11,december:12,jan:1,feb:2,mar:3,apr:4,jun:6,jul:7,aug:8,sep:9,sept:9,oct:10,nov:11,dec:12};
const SOURCE_DEFS=[
  {id:'federal-reserve',currency:'USD',bank:'Federal Reserve',title:'Federal Reserve Interest Rate Decision',url:'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',parser:'fed'},
  {id:'ecb',currency:'EUR',bank:'European Central Bank',title:'ECB Interest Rate Decision',url:'https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html',parser:'ecb'},
  {id:'bank-of-england',currency:'GBP',bank:'Bank of England',title:'Bank of England Bank Rate Decision',url:'https://www.bankofengland.co.uk/news/2025/september/monetary-policy-committee-dates-for-2026',parser:'boe'},
  {id:'sarb',currency:'ZAR',bank:'South African Reserve Bank',title:'SARB Repo Rate Decision',url:'https://www.resbank.co.za/en/home/what-we-do/monetary-policy/MPC-announcement-webcasts',parser:'sarb'},
  {id:'bank-of-japan',currency:'JPY',bank:'Bank of Japan',title:'Bank of Japan Interest Rate Decision',url:'https://www.boj.or.jp/en/mopo/mpmsche_minu/index.htm',parser:'boj'},
];
const FALLBACK_2026={
  'federal-reserve':['2026-01-28','2026-03-18','2026-04-29','2026-06-17','2026-07-29','2026-09-16','2026-10-28','2026-12-09'],
  ecb:['2026-02-05','2026-03-19','2026-04-30','2026-06-11','2026-07-23','2026-09-10','2026-10-29','2026-12-17'],
  'bank-of-england':['2026-02-05','2026-03-19','2026-04-30','2026-06-18','2026-07-30','2026-09-17','2026-11-05','2026-12-17'],
  sarb:['2026-01-29','2026-03-26','2026-05-28','2026-07-23','2026-09-23','2026-11-19'],
  'bank-of-japan':['2026-01-23','2026-03-19','2026-04-28','2026-06-16','2026-07-31','2026-09-18','2026-10-30','2026-12-18'],
};
function cleanText(html){const $=loadHtml(html);$('script,style,noscript,svg').remove();return $('body').text().replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim();}
function dateOnlyIso(date){return `${date}T12:00:00.000Z`;}
function dateString(year,month,day){return `${String(year).padStart(4,'0')}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`;}
function zonedIso(year,month,day,hour,minute,timeZone){
  const target=Date.UTC(year,month-1,day,hour,minute,0),fmt=new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'});let utc=target;
  for(let i=0;i<4;i++){const parts=Object.fromEntries(fmt.formatToParts(new Date(utc)).filter(x=>x.type!=='literal').map(x=>[x.type,Number(x.value)])),rendered=Date.UTC(parts.year,parts.month-1,parts.day,parts.hour,parts.minute,parts.second||0),delta=target-rendered;utc+=delta;if(Math.abs(delta)<1000)break;}
  return new Date(utc).toISOString();
}
function uniqueDates(rows){const seen=new Set();return rows.filter(row=>{if(!row?.decisionDate||seen.has(row.decisionDate))return false;seen.add(row.decisionDate);return true;}).sort((a,b)=>a.decisionDate.localeCompare(b.decisionDate));}
function sectionForYear(text,year,marker){const needle=marker(year),start=text.indexOf(needle);if(start<0)return '';let end=text.length;for(const other of [year-1,year+1]){const idx=text.indexOf(marker(other),start+needle.length);if(idx>start&&idx<end)end=idx;}return text.slice(start,end);}
export function parseFedSchedule(html,year){const text=cleanText(html),section=sectionForYear(text,year,y=>`${y} FOMC Meetings`),rows=[],re=/(January|February|March|April|May|June|July|August|September|October|November|December)\s+(\d{1,2})\s*[-–]\s*(\d{1,2})\*?/gi;let m;while((m=re.exec(section))){const month=MONTHS[m[1].toLowerCase()],day=Number(m[3]),decisionDate=dateString(year,month,day);rows.push({decisionDate,date:zonedIso(year,month,day,14,0,'America/New_York'),timePrecision:'exact',scheduledLocalTime:'14:00',timeZone:'America/New_York'});}return uniqueDates(rows);}
export function parseEcbSchedule(html,year){const text=cleanText(html),matches=[...text.matchAll(/\b(\d{2})\/(\d{2})\/(\d{4})\b/g)],rows=[];for(let i=0;i<matches.length;i++){const m=matches[i],segment=text.slice(m.index,i+1<matches.length?matches[i+1].index:Math.min(text.length,m.index+350));if(Number(m[3])!==year||!/Governing Council of the ECB:\s*monetary policy meeting/i.test(segment)||!/\(Day 2\)/i.test(segment))continue;const decisionDate=dateString(Number(m[3]),Number(m[2]),Number(m[1]));rows.push({decisionDate,date:dateOnlyIso(decisionDate),timePrecision:'date-only',scheduledLocalTime:null,timeZone:'Europe/Frankfurt'});}return uniqueDates(rows);}
export function parseBoeSchedule(html,year){const text=cleanText(html),start=Math.max(text.indexOf('MPC Announcement and Minutes publication'),text.indexOf('provisional dates')),end=text.indexOf('Notes to editors',Math.max(0,start)),section=text.slice(Math.max(0,start),end>start?end:text.length),rows=[],re=/(\d{1,2})\s+(January|February|March|April|May|June|July|August|September|October|November|December)\s+(20\d{2})/gi;let m;while((m=re.exec(section))){if(Number(m[3])!==year)continue;const decisionDate=dateString(Number(m[3]),MONTHS[m[2].toLowerCase()],Number(m[1]));rows.push({decisionDate,date:dateOnlyIso(decisionDate),timePrecision:'date-only',scheduledLocalTime:null,timeZone:'Europe/London'});}return uniqueDates(rows);}
export function parseSarbSchedule(html,year){const text=cleanText(html),rows=[],re=/(20\d{2})\/(\d{2})\/(\d{2})\s*-\s*(\d{1,2}):(\d{2})/g;let m;while((m=re.exec(text))){if(Number(m[1])!==year)continue;const y=Number(m[1]),month=Number(m[2]),day=Number(m[3]),hour=Number(m[4]),minute=Number(m[5]),decisionDate=dateString(y,month,day);rows.push({decisionDate,date:zonedIso(y,month,day,hour,minute,'Africa/Johannesburg'),timePrecision:'exact',scheduledLocalTime:`${String(hour).padStart(2,'0')}:${String(minute).padStart(2,'0')}`,timeZone:'Africa/Johannesburg'});}return uniqueDates(rows);}
function parseBojRowText(text,year){const re=/(Jan\.|Feb\.|Mar\.|Apr\.|May|June|July|Aug\.|Sept\.|Sep\.|Oct\.|Nov\.|Dec\.)\s*(\d{1,2})\s*\([^)]*\),\s*(\d{1,2})\s*\([^)]*\)/gi,rows=[];let m;while((m=re.exec(text))){const month=MONTHS[m[1].toLowerCase().replace('.','')],decisionDate=dateString(year,month,Number(m[3]));rows.push({decisionDate,date:dateOnlyIso(decisionDate),timePrecision:'date-only',scheduledLocalTime:null,timeZone:'Asia/Tokyo'});}return rows;}
export function parseBojSchedule(html,year){const $=loadHtml(html),rows=[];$('h1,h2,h3,h4').filter((_,node)=>$(node).text().trim()===String(year)).each((_,heading)=>{const table=$(heading).nextAll('table').first();table.find('tr').each((__,row)=>rows.push(...parseBojRowText($(row).text().replace(/\s+/g,' '),year)));});if(!rows.length){const text=cleanText(html),section=sectionForYear(text,year,y=>String(y));rows.push(...parseBojRowText(section,year));}return uniqueDates(rows);}
const PARSERS={fed:parseFedSchedule,ecb:parseEcbSchedule,boe:parseBoeSchedule,sarb:parseSarbSchedule,boj:parseBojSchedule};
function fallbackRows(source,year){return (year===2026?(FALLBACK_2026[source.id]||[]):[]).map(decisionDate=>{const [y,m,d]=decisionDate.split('-').map(Number);if(source.id==='federal-reserve')return {decisionDate,date:zonedIso(y,m,d,14,0,'America/New_York'),timePrecision:'exact',scheduledLocalTime:'14:00',timeZone:'America/New_York'};if(source.id==='sarb')return {decisionDate,date:zonedIso(y,m,d,15,0,'Africa/Johannesburg'),timePrecision:'exact',scheduledLocalTime:'15:00',timeZone:'Africa/Johannesburg'};return {decisionDate,date:dateOnlyIso(decisionDate),timePrecision:'date-only',scheduledLocalTime:null,timeZone:source.id==='ecb'?'Europe/Frankfurt':source.id==='bank-of-england'?'Europe/London':'Asia/Tokyo'};});}
async function fetchHtml(url,timeoutMs=7000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(url,{headers:{Accept:'text/html,application/xhtml+xml','User-Agent':'FXGA-Official-Policy-Schedule/1.0'},redirect:'follow',signal:controller.signal});if(!response.ok)throw new Error(`HTTP ${response.status}`);return {html:await response.text(),status:response.status};}finally{clearTimeout(timer);}}
function eventFrom(source,row,retrievedAt,fallbackUsed){const key=policyDecisionKey({currency:source.currency,policyDecisionDate:row.decisionDate,date:row.date});return {id:`official-policy-${source.currency}-${row.decisionDate}`,date:row.date,policyDecisionDate:row.decisionDate,policyDecisionKey:key,currency:source.currency,country:source.currency,event:source.title,category:'Monetary Policy',importance:3,providers:[source.id],sourceCount:1,source:source.bank,policyCatalyst:true,policyCatalystHorizonOnly:true,policyScheduleOnly:true,timePrecision:row.timePrecision,scheduledLocalTime:row.scheduledLocalTime,timeZone:row.timeZone,policyProvenance:{provider:source.id,source:source.bank,sourceUrl:source.url,retrievedAt,parser:source.parser,fallbackUsed:Boolean(fallbackUsed),timePrecision:row.timePrecision,decisionDate:row.decisionDate}};}
export async function collectOfficialPolicySchedule({from=new Date(),to=new Date(Date.now()+75*86400000)}={}){const fromMs=from instanceof Date?from.getTime():Date.parse(from),toMs=to instanceof Date?to.getTime():Date.parse(to),years=[];for(let year=new Date(fromMs).getUTCFullYear();year<=new Date(toMs).getUTCFullYear();year++)years.push(year);const retrievedAt=new Date().toISOString(),settled=await Promise.allSettled(SOURCE_DEFS.map(async source=>{let html=null,httpStatus=null,error=null,rows=[],fallbackUsed=false;try{const result=await fetchHtml(source.url);html=result.html;httpStatus=result.status;for(const year of years)rows.push(...PARSERS[source.parser](html,year));rows=uniqueDates(rows);if(!rows.length)throw new Error('Official page parsed zero scheduled decisions');}catch(caught){error=String(caught?.message||caught).slice(0,240);fallbackUsed=true;rows=uniqueDates(years.flatMap(year=>fallbackRows(source,year)));}const inWindow=rows.filter(row=>{const t=Date.parse(row.date);return Number.isFinite(t)&&t>=fromMs&&t<=toMs;}).map(row=>eventFrom(source,row,retrievedAt,fallbackUsed));return {source,rows,inWindow,httpStatus,error,fallbackUsed};}));const events=[],sources={};for(let i=0;i<settled.length;i++){const source=SOURCE_DEFS[i],result=settled[i];if(result.status==='rejected'){sources[source.id]={ok:false,currency:source.currency,bank:source.bank,sourceUrl:source.url,parsedTotal:0,events:0,liveFetch:false,fallbackUsed:false,error:String(result.reason?.message||result.reason).slice(0,240)};continue;}const value=result.value;events.push(...value.inWindow);sources[source.id]={ok:value.rows.length>0,currency:source.currency,bank:source.bank,sourceUrl:source.url,httpStatus:value.httpStatus,parsedTotal:value.rows.length,events:value.inWindow.length,liveFetch:!value.fallbackUsed,fallbackUsed:value.fallbackUsed,error:value.error};}const deduped=[];for(const event of events.sort((a,b)=>Date.parse(a.date)-Date.parse(b.date))){if(deduped.some(x=>x.policyDecisionKey===event.policyDecisionKey))continue;deduped.push(event);}const list=Object.values(sources),okSources=list.filter(x=>x.ok).length,liveSources=list.filter(x=>x.ok&&x.liveFetch).length,fallbackSources=list.filter(x=>x.ok&&x.fallbackUsed).length,failedSources=list.length-okSources;return {generatedAt:retrievedAt,events:deduped,health:{ok:okSources>=3,architecture:'official-five-bank-policy-schedule-ensemble',requestedSources:list.length,okSources,liveSources,fallbackSources,failedSources,events:deduped.length,windowStart:new Date(fromMs).toISOString(),windowEnd:new Date(toMs).toISOString(),sources}};}
export const officialPolicyScheduleParsers={parseFedSchedule,parseEcbSchedule,parseBoeSchedule,parseSarbSchedule,parseBojSchedule};
'''
Path('cloud-run-collector/src/official-policy-schedule.js').write_text(schedule_module)

horizon = r'''const DAY_MS=86_400_000;
const POLICY_CURRENCIES=new Set(['USD','EUR','GBP','ZAR','JPY']);
const POLICY_DECISION_RE=/\b(?:interest rate decision|rate decision|bank rate decision|repo rate decision|policy rate decision|cash rate decision|refinancing rate decision|deposit facility rate decision|fed funds rate decision|monetary policy decision)\b/i;
const normalize=value=>String(value||'').toLowerCase().replace(/&/g,' and ').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();

export function isPolicyDecisionEvent(event){const currency=String(event?.currency||'').toUpperCase();if(!POLICY_CURRENCIES.has(currency))return false;return Boolean(event?.policyDecisionKey||event?.policyScheduleOnly||POLICY_DECISION_RE.test(`${event?.event||''} ${event?.category||''}`));}
export function policyDecisionDate(event){if(/^\d{4}-\d{2}-\d{2}$/.test(String(event?.policyDecisionDate||'')))return String(event.policyDecisionDate);const t=Date.parse(event?.date||'');return Number.isFinite(t)?new Date(t).toISOString().slice(0,10):null;}
export function policyDecisionKey(event){const currency=String(event?.currency||'').toUpperCase(),date=policyDecisionDate(event);return POLICY_CURRENCIES.has(currency)&&date?`${currency}:${date}`:null;}
export function policyCatalystSegments(from,to,maxDays=30){const start=from instanceof Date?from.getTime():Date.parse(from),end=to instanceof Date?to.getTime():Date.parse(to),span=Math.max(1,Math.min(30,Number(maxDays)||30))*DAY_MS;if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)return [];const segments=[];let cursor=start;while(cursor<end){const segmentEnd=Math.min(end,cursor+span);segments.push({from:new Date(cursor),to:new Date(segmentEnd)});cursor=segmentEnd+1000;}return segments;}
function sameEvent(a,b){if(String(a?.currency||'')!==String(b?.currency||''))return false;const ka=policyDecisionKey(a),kb=policyDecisionKey(b);if(ka&&kb&&ka===kb&&(isPolicyDecisionEvent(a)||isPolicyDecisionEvent(b)))return true;const ta=Date.parse(a?.date||''),tb=Date.parse(b?.date||'');if(!Number.isFinite(ta)||!Number.isFinite(tb)||Math.abs(ta-tb)>5*60_000)return false;const na=normalize(a?.event),nb=normalize(b?.event);return na===nb||na.includes(nb)||nb.includes(na);}
function precisionRank(event){if(!event?.policyScheduleOnly)return 4;return event?.timePrecision==='exact'?3:event?.timePrecision==='minute'?2:event?.timePrecision==='date-only'?1:0;}
function provenanceList(event){const values=[];if(event?.policyProvenance)values.push(event.policyProvenance);for(const item of event?.policyProvenanceSources||[])if(item)values.push(item);const seen=new Set();return values.filter(item=>{const key=`${item?.provider||''}|${item?.sourceUrl||''}|${item?.decisionDate||''}`;if(seen.has(key))return false;seen.add(key);return true;});}
export function mergePolicyCatalystEvents(primary=[],policyEvents=[]){const merged=(primary||[]).map(event=>({...event,policyDecisionKey:event.policyDecisionKey||policyDecisionKey(event)}));for(const candidateRaw of policyEvents||[]){const candidate={...candidateRaw,policyDecisionKey:candidateRaw.policyDecisionKey||policyDecisionKey(candidateRaw)},match=merged.find(event=>sameEvent(event,candidate));if(!match){merged.push(candidate);continue;}const primaryRank=precisionRank(match),candidateRank=precisionRank(candidate);if(candidateRank>primaryRank&&Boolean(match.policyCatalystHorizonOnly)){match.date=candidate.date;match.timePrecision=candidate.timePrecision;match.scheduledLocalTime=candidate.scheduledLocalTime;match.timeZone=candidate.timeZone;}match.providers=[...new Set([...(match.providers||[]),...(candidate.providers||[])])];match.sourceCount=match.providers.length;match.policyCatalyst=Boolean(match.policyCatalyst||candidate.policyCatalyst);match.policyCatalystHorizonOnly=Boolean(match.policyCatalystHorizonOnly)&&Boolean(candidate.policyCatalystHorizonOnly);match.policyScheduleOnly=Boolean(match.policyScheduleOnly)&&Boolean(candidate.policyScheduleOnly);match.policyDecisionDate=match.policyDecisionDate||candidate.policyDecisionDate||policyDecisionDate(match);match.policyDecisionKey=match.policyDecisionKey||candidate.policyDecisionKey||policyDecisionKey(match);const provenance=[...provenanceList(match),...provenanceList(candidate)];match.policyProvenanceSources=provenanceList({policyProvenanceSources:provenance});if(!match.policyProvenance&&provenance.length)match.policyProvenance=provenance[0];match.actual??=candidate.actual;match.forecast??=candidate.forecast;match.previous??=candidate.previous;match.revised??=candidate.revised;}return merged.sort((a,b)=>Date.parse(a.date)-Date.parse(b.date));}
'''
Path('cloud-run-collector/src/policy-catalyst-horizon.js').write_text(horizon)

path='cloud-run-collector/src/server-v2.js'
replace_once(path,"import { isPolicyDecisionEvent, mergePolicyCatalystEvents, policyCatalystSegments } from './policy-catalyst-horizon.js';\n", "import { isPolicyDecisionEvent, mergePolicyCatalystEvents, policyCatalystSegments, policyDecisionKey } from './policy-catalyst-horizon.js';\nimport { collectOfficialPolicySchedule } from './official-policy-schedule.js';\n")
replace_once(path,"  return { ...event, ...bias, outcome, betterThanExpected:bias.currencyBias === 'bullish', worseThanExpected:bias.currencyBias === 'bearish' };\n", "  const decisionKey=isPolicyDecisionEvent(event)?event.policyDecisionKey||policyDecisionKey(event):event.policyDecisionKey;\n  return { ...event, ...bias, outcome, betterThanExpected:bias.currencyBias === 'bullish', worseThanExpected:bias.currencyBias === 'bearish', ...(decisionKey?{policyDecisionKey:decisionKey,policyDecisionDate:event.policyDecisionDate||decisionKey.split(':')[1]}:{}) };\n")
replace_once(path,"  const [fxstreetResult,myfxbook,cnbc,policyHorizonResult]=await Promise.allSettled([fetchFxstreet(from,to),scrapeMyfxbook(),scrapeCnbc(),fetchPolicyCatalystHorizon(new Date(to.getTime()+1000),policyTo)]);\n", "  const [fxstreetResult,myfxbook,cnbc,policyHorizonResult,officialPolicyResult]=await Promise.allSettled([fetchFxstreet(from,to),scrapeMyfxbook(),scrapeCnbc(),fetchPolicyCatalystHorizon(new Date(to.getTime()+1000),policyTo),collectOfficialPolicySchedule({from:now,to:policyTo})]);\n")
replace_once(path,"  const policyHorizon=policyHorizonResult.status==='fulfilled'?policyHorizonResult.value:{events:[],health:{ok:false,source:'FXStreet public calendar feed',segments:0,failedSegments:1,events:0,error:String(policyHorizonResult.reason?.message||policyHorizonResult.reason).slice(0,220)}};\n", "  const policyHorizon=policyHorizonResult.status==='fulfilled'?policyHorizonResult.value:{events:[],health:{ok:false,source:'FXStreet public calendar feed',segments:0,failedSegments:1,events:0,error:String(policyHorizonResult.reason?.message||policyHorizonResult.reason).slice(0,220)}};\n  const officialPolicy=officialPolicyResult.status==='fulfilled'?officialPolicyResult.value:{events:[],health:{ok:false,architecture:'official-five-bank-policy-schedule-ensemble',requestedSources:5,okSources:0,liveSources:0,fallbackSources:0,failedSources:5,events:0,error:String(officialPolicyResult.reason?.message||officialPolicyResult.reason).slice(0,220)}};\n")
replace_once(path,"  const policyEvents=(policyHorizon.events||[]).map(enrichCalendarEvent).filter((event)=>Date.parse(event.date)>to.getTime()&&Date.parse(event.date)<=policyTo.getTime());\n  const events=mergePolicyCatalystEvents(normalEvents,policyEvents);\n", "  const fxPolicyEvents=(policyHorizon.events||[]).map(enrichCalendarEvent).filter((event)=>Date.parse(event.date)>to.getTime()&&Date.parse(event.date)<=policyTo.getTime());\n  const officialPolicyEvents=(officialPolicy.events||[]).map(enrichCalendarEvent).filter((event)=>Date.parse(event.date)>now.getTime()&&Date.parse(event.date)<=policyTo.getTime());\n  const policyEvents=mergePolicyCatalystEvents(fxPolicyEvents,officialPolicyEvents);\n  const events=mergePolicyCatalystEvents(normalEvents,policyEvents);\n  const extendedPolicyEvents=events.filter((event)=>event.policyCatalystHorizonOnly===true);\n")
replace_once(path,"  const sourceHealth={fxstreet:{ok:fxstreet.length>0,events:fxstreet.length},myfxbook:{ok:Boolean(myfx.ok),events:(myfx.events||[]).length,mode:myfx.mode,error:myfx.error},cnbc:{ok:Boolean(cnbcResult.ok),items:(cnbcResult.items||[]).length,error:cnbcResult.error},policyCatalysts:policyHorizon.health};\n", "  const sourceHealth={fxstreet:{ok:fxstreet.length>0,events:fxstreet.length},myfxbook:{ok:Boolean(myfx.ok),events:(myfx.events||[]).length,mode:myfx.mode,error:myfx.error},cnbc:{ok:Boolean(cnbcResult.ok),items:(cnbcResult.items||[]).length,error:cnbcResult.error},policyCatalysts:{ok:Boolean(policyHorizon.health?.ok||officialPolicy.health?.ok),source:'FXStreet plus official central-bank schedule ensemble',events:extendedPolicyEvents.length,fxstreet:policyHorizon.health,official:officialPolicy.health}};\n")
replace_once(path,"  const snapshot={generatedAt:new Date().toISOString(),days:cfg.calendarDays,historyDays:CALENDAR_HISTORY_DAYS,windowStart:from.toISOString(),windowEnd:to.toISOString(),policyCatalystDays:cfg.policyCatalystDays,policyWindowEnd:policyTo.toISOString(),policyCatalystCount:policyEvents.length,targetEconomies:TARGET_ECONOMIES,events,sourceHealth,cnbcContext:cnbcResult.items||[]};\n", "  const snapshot={generatedAt:new Date().toISOString(),days:cfg.calendarDays,historyDays:CALENDAR_HISTORY_DAYS,windowStart:from.toISOString(),windowEnd:to.toISOString(),policyCatalystDays:cfg.policyCatalystDays,policyWindowEnd:policyTo.toISOString(),policyCatalystCount:extendedPolicyEvents.length,officialPolicyScheduleCount:officialPolicyEvents.length,targetEconomies:TARGET_ECONOMIES,events,sourceHealth,cnbcContext:cnbcResult.items||[]};\n")

path='cloud-run-collector/src/policy-path-research.js'
replace_once(path,"function futureMeetings(events,currency,nowMs){return (events||[]).filter(e=>policyEvent(e,currency)&&Date.parse(e.date)>nowMs).sort((a,b)=>Date.parse(a.date)-Date.parse(b.date)).slice(0,3);}\n", "function futureMeetings(events,currency,nowMs){return (events||[]).filter(e=>policyEvent(e,currency)&&Date.parse(e.date)>nowMs).sort((a,b)=>Date.parse(a.date)-Date.parse(b.date)).slice(0,3);}\nfunction meetingDescriptor(x){return {id:x.id,event:x.event,date:x.date,policyDecisionKey:x.policyDecisionKey??null,policyDecisionDate:x.policyDecisionDate??null,forecast:x.forecast??null,previous:x.previous??null,source:x.source??null,providers:x.providers??[],policyCatalystHorizonOnly:Boolean(x.policyCatalystHorizonOnly),policyScheduleOnly:Boolean(x.policyScheduleOnly),timePrecision:x.timePrecision??null,scheduledLocalTime:x.scheduledLocalTime??null,timeZone:x.timeZone??null,policyProvenance:x.policyProvenance??null,policyProvenanceSources:x.policyProvenanceSources??[]};}\n")
replace_once(path,"nextMeeting:meeting?{id:meeting.id,event:meeting.event,date:meeting.date,forecast:meeting.forecast??null,previous:meeting.previous??null,source:meeting.source??null,providers:meeting.providers??[],policyCatalystHorizonOnly:Boolean(meeting.policyCatalystHorizonOnly),policyProvenance:meeting.policyProvenance??null}:null,scheduledDecisionEvents:meetings.map(x=>({id:x.id,event:x.event,date:x.date,forecast:x.forecast??null,previous:x.previous??null,source:x.source??null,providers:x.providers??[],policyCatalystHorizonOnly:Boolean(x.policyCatalystHorizonOnly),policyProvenance:x.policyProvenance??null}))", "nextMeeting:meeting?meetingDescriptor(meeting):null,scheduledDecisionEvents:meetings.map(meetingDescriptor)")
replace_once(path,"eventId:meetings[depth]?.id||null,date:meetings[depth]?.date||null", "eventId:meetings[depth]?.id||null,policyDecisionKey:meetings[depth]?.policyDecisionKey||null,date:meetings[depth]?.date||null")
replace_once(path,"Scheduled decision provenance is retained, including policy-only extended-horizon calendar observations when present.", "Scheduled decision provenance is retained, including official central-bank schedules and policy-only extended-horizon observations when present. Schedule-only date precision is explicit and is never presented as an exact release timestamp unless the official source supplies one.")

path='cloud-run-collector/src/policy-calibration.js'
replace_once(path,"function idFor(currency,eventId,leadBucket='legacy'){return crypto.createHash('sha256').update(`${currency}|${eventId}|${leadBucket}`).digest('hex');}\n", "function idFor(currency,decisionKey,leadBucket='legacy'){return crypto.createHash('sha256').update(`${currency}|${decisionKey}|${leadBucket}`).digest('hex');}\n")
replace_once(path,"function leadHoursForRow(row){if(Number.isFinite(Number(row?.leadHours)))return Number(row.leadHours);const release=Date.parse(row?.releaseAt||''),frozen=Date.parse(row?.frozenAt||'');return Number.isFinite(release)&&Number.isFinite(frozen)?Math.max(0,(release-frozen)/3600000):null;}\n", "function leadHoursForRow(row){if(Number.isFinite(Number(row?.leadHours)))return Number(row.leadHours);const release=Date.parse(row?.releaseAt||''),frozen=Date.parse(row?.frozenAt||'');return Number.isFinite(release)&&Number.isFinite(frozen)?Math.max(0,(release-frozen)/3600000):null;}\nfunction policyKeyForRow(row){if(/^([A-Z]{3}):\\d{4}-\\d{2}-\\d{2}$/.test(String(row?.policyDecisionKey||'')))return String(row.policyDecisionKey);const currency=String(row?.currency||'').toUpperCase(),release=Date.parse(row?.releaseAt||'');return /^[A-Z]{3}$/.test(currency)&&Number.isFinite(release)?`${currency}:${new Date(release).toISOString().slice(0,10)}`:String(row?.eventId||'');}\n")
replace_once(path,"export function enrichLeadMetadata(row){const leadHours=leadHoursForRow(row),bucket=row?.leadBucket?POLICY_LEAD_BUCKETS.find(x=>x.id===row.leadBucket)||null:bucketForLeadHours(leadHours);return {...row,leadHours:leadHours==null?null:Number(leadHours.toFixed(3)),derivedLeadBucket:bucket?.id||row?.leadBucket||'outside-window',derivedLeadBucketLabel:bucket?.label||row?.leadBucketLabel||'Outside lead windows'};}\n", "export function enrichLeadMetadata(row){const leadHours=leadHoursForRow(row),bucket=row?.leadBucket?POLICY_LEAD_BUCKETS.find(x=>x.id===row.leadBucket)||null:bucketForLeadHours(leadHours),derivedPolicyDecisionKey=policyKeyForRow(row);return {...row,leadHours:leadHours==null?null:Number(leadHours.toFixed(3)),derivedPolicyDecisionKey,derivedLeadBucket:bucket?.id||row?.leadBucket||'outside-window',derivedLeadBucketLabel:bucket?.label||row?.leadBucketLabel||'Outside lead windows'};}\n")
replace_once(path,"uniqueDecisions:new Set(enriched.map(x=>x.eventId).filter(Boolean)).size", "uniqueDecisions:new Set(enriched.map(x=>x.derivedPolicyDecisionKey).filter(Boolean)).size")
replace_once(path,"from=new Map(enriched.filter(x=>x.derivedLeadBucket===fromBucket).map(x=>[x.eventId,x])),to=new Map(enriched.filter(x=>x.derivedLeadBucket===toBucket).map(x=>[x.eventId,x])),pairs=[];for(const [eventId,a] of from){const b=to.get(eventId);if(!b)continue;pairs.push({eventId,currency:b.currency", "from=new Map(enriched.filter(x=>x.derivedLeadBucket===fromBucket).map(x=>[x.derivedPolicyDecisionKey,x])),to=new Map(enriched.filter(x=>x.derivedLeadBucket===toBucket).map(x=>[x.derivedPolicyDecisionKey,x])),pairs=[];for(const [decisionKey,a] of from){const b=to.get(decisionKey);if(!b)continue;pairs.push({eventId:b.eventId,policyDecisionKey:decisionKey,currency:b.currency")
replace_once(path,"existingKeys=new Set(existing.map(x=>`${x.currency}|${x.eventId}|${x.derivedLeadBucket}`));let frozen=0,skipped=0;const frozenByLead={};", "existingKeys=new Set(existing.map(x=>`${x.currency}|${x.derivedPolicyDecisionKey}|${x.derivedLeadBucket}`));let frozen=0,skipped=0,precisionSkipped=0;const frozenByLead={};")
replace_once(path,"const leadHours=(t-nowMs)/3600000,bucket=bucketForLeadHours(leadHours);if(!bucket){skipped++;continue;}const key=`${row.currency}|${meeting.id}|${bucket.id}`;if(existingKeys.has(key))", "const leadHours=(t-nowMs)/3600000,bucket=bucketForLeadHours(leadHours);if(!bucket){skipped++;continue;}const timePrecision=meeting.timePrecision||event.timePrecision||null;if(Boolean(meeting.policyScheduleOnly||event.policyScheduleOnly)&&timePrecision==='date-only'&&leadHours<=24){skipped++;precisionSkipped++;continue;}const decisionKey=meeting.policyDecisionKey||event.policyDecisionKey||`${row.currency}:${new Date(t).toISOString().slice(0,10)}`,key=`${row.currency}|${decisionKey}|${bucket.id}`;if(existingKeys.has(key))")
replace_once(path,"const ref=audit.doc(idFor(row.currency,meeting.id,bucket.id))", "const ref=audit.doc(idFor(row.currency,decisionKey,bucket.id))")
replace_once(path,"basis={eventId:meeting.id,currency:row.currency,releaseAt:meeting.date,leadBucket:bucket.id,leadHours:Number(leadHours.toFixed(3)),probabilities", "basis={eventId:meeting.id,policyDecisionKey:decisionKey,currency:row.currency,releaseAt:meeting.date,leadBucket:bucket.id,leadHours:Number(leadHours.toFixed(3)),timePrecision,policyScheduleOnly:Boolean(meeting.policyScheduleOnly||event.policyScheduleOnly),source:meeting.source||event.source||null,probabilities")
replace_once(path,"  return {frozen,skipped,frozenByLead};\n", "  return {frozen,skipped,precisionSkipped,frozenByLead};\n")
replace_once(path,"  const byId=new Map((events||[]).map(event=>[event.id,event])),pending=await audit.where('scored','==',false).limit(240).get();let scored=0;const scoredByLead={};\n  for(const doc of pending.docs){const row=enrichLeadMetadata(doc.data()),event=byId.get(row.eventId),outcome=outcomeForEvent(event);", "  const byId=new Map((events||[]).map(event=>[event.id,event])),byPolicyKey=new Map();for(const event of events||[]){const key=event.policyDecisionKey||(/^[A-Z]{3}$/.test(String(event.currency||''))&&Number.isFinite(Date.parse(event.date||''))?`${String(event.currency).toUpperCase()}:${new Date(Date.parse(event.date)).toISOString().slice(0,10)}`:null);if(key&&outcomeForEvent(event))byPolicyKey.set(key,event);}const pending=await audit.where('scored','==',false).limit(240).get();let scored=0;const scoredByLead={};\n  for(const doc of pending.docs){const row=enrichLeadMetadata(doc.data()),event=byId.get(row.eventId)||byPolicyKey.get(row.derivedPolicyDecisionKey),outcome=outcomeForEvent(event);")
replace_once(path,"await doc.ref.set({scored:true,scoredAt:new Date().toISOString(),outcome,assignedProbability", "await doc.ref.set({scored:true,scoredAt:new Date().toISOString(),scoredFromEventId:event?.id||null,scoredFromPolicyDecisionKey:row.derivedPolicyDecisionKey,outcome,assignedProbability")
replace_once(path,"Missing earlier lead windows are never backfilled. Every snapshot is scored only after a real policy-rate outcome is reported.", "Missing earlier lead windows are never backfilled. Official schedule-only rows with date-only precision cannot create 24-hour or final snapshots; those require a precise normal-calendar release time. Every snapshot is scored only after a real policy-rate outcome is reported, with canonical currency-date matching used when the official schedule and realized calendar have different event IDs.")
replace_once(path,"export const policyCalibrationMath={normalizeProbabilities,outcomeForEvent,scoreForecast,bucketForLeadHours,enrichLeadMetadata,summarizeRows,pairedLeadComparison};", "export const policyCalibrationMath={normalizeProbabilities,outcomeForEvent,scoreForecast,bucketForLeadHours,enrichLeadMetadata,policyKeyForRow,summarizeRows,pairedLeadComparison};")

path='cloud-run-collector/package.json'
replace_once(path,"node --check src/policy-catalyst-horizon.js && node --check src/decision-quality-attribution.js", "node --check src/policy-catalyst-horizon.js && node --check src/official-policy-schedule.js && node --check src/decision-quality-attribution.js")

path='src/components/PolicyEventResearchPanel.tsx'
replace_once(path,"type PolicyMeeting={id?:string;event:string;date:string;forecast:string|null;previous:string|null;source?:string|null;providers?:string[];policyCatalystHorizonOnly?:boolean;policyProvenance?:{provider?:string;source?:string;retrievedAt?:string;windowStart?:string;windowEnd?:string}|null};", "type PolicyMeeting={id?:string;event:string;date:string;policyDecisionKey?:string|null;policyDecisionDate?:string|null;forecast:string|null;previous:string|null;source?:string|null;providers?:string[];policyCatalystHorizonOnly?:boolean;policyScheduleOnly?:boolean;timePrecision?:string|null;scheduledLocalTime?:string|null;timeZone?:string|null;policyProvenance?:{provider?:string;source?:string;sourceUrl?:string;retrievedAt?:string;windowStart?:string;windowEnd?:string;fallbackUsed?:boolean;timePrecision?:string}|null;policyProvenanceSources?:Array<{provider?:string;source?:string;sourceUrl?:string;fallbackUsed?:boolean}>};")
replace_once(path,"<small>Next scheduled policy catalyst{row.nextMeeting.policyCatalystHorizonOnly?' · extended policy horizon':''}</small><span>{row.nextMeeting.event} · {new Date(row.nextMeeting.date).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}{row.nextMeeting.source?` · ${row.nextMeeting.source}`:''}</span>", "<small>Next scheduled policy catalyst{row.nextMeeting.policyCatalystHorizonOnly?' · extended policy horizon':''}{row.nextMeeting.policyScheduleOnly?' · official schedule':''}</small><span>{row.nextMeeting.event} · {row.nextMeeting.timePrecision==='date-only'?new Date(row.nextMeeting.date).toLocaleDateString([], {month:'short',day:'numeric'}):new Date(row.nextMeeting.date).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}{row.nextMeeting.source?` · ${row.nextMeeting.source}`:''}{row.nextMeeting.timePrecision==='date-only'?' · time not asserted':''}</span>")

print('v4.20 official five-bank policy schedule ensemble patch applied')
