const finite=values=>values.filter(Number.isFinite);
const mean=values=>{const x=finite(values);return x.length?x.reduce((a,b)=>a+b,0)/x.length:null;};
const std=values=>{const x=finite(values);if(x.length<2)return null;const m=mean(x);return Math.sqrt(x.reduce((s,v)=>s+(v-m)**2,0)/(x.length-1));};
const round=(value,d=6)=>Number.isFinite(Number(value))?Number(Number(value).toFixed(d)):null;
function seedOf(text='fxga'){let h=2166136261;for(const char of String(text)){h^=char.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
function rng(seed){let s=seed||1;return()=>{s^=s<<13;s^=s>>>17;s^=s<<5;return(s>>>0)/4294967296;};}
function quantile(values,q){const x=finite(values).sort((a,b)=>a-b);if(!x.length)return null;const p=(x.length-1)*Math.min(1,Math.max(0,q)),i=Math.floor(p),f=p-i;return x[i+1]===undefined?x[i]:x[i]+f*(x[i+1]-x[i]);}
export function equityStats(returns=[]){const x=finite(returns),wins=x.filter(v=>v>0),losses=x.filter(v=>v<0),grossProfit=wins.reduce((a,b)=>a+b,0),grossLoss=Math.abs(losses.reduce((a,b)=>a+b,0));let equity=0,peak=0,maxDrawdown=0,maxDrawdownPct=0,drawdownDuration=0,maxDrawdownDuration=0,underwater=0;for(const r of x){equity+=r;if(equity>=peak){peak=equity;underwater=0;}else{underwater+=1;const dd=peak-equity;maxDrawdown=Math.max(maxDrawdown,dd);const base=Math.max(Math.abs(peak),1);maxDrawdownPct=Math.max(maxDrawdownPct,dd/base*100);maxDrawdownDuration=Math.max(maxDrawdownDuration,underwater);}}drawdownDuration=underwater;const avgWin=mean(wins),avgLoss=losses.length?Math.abs(mean(losses)):null,vol=std(x),downside=std(x.filter(v=>v<0)),expectancy=mean(x),sharpeLike=vol&&expectancy!=null?expectancy/vol*Math.sqrt(x.length):null,sortinoLike=downside&&expectancy!=null?expectancy/downside*Math.sqrt(x.length):null;return{observations:x.length,totalNetPct:round(equity),expectancyPct:round(expectancy),winRate:x.length?round(wins.length/x.length,4):null,averageWinPct:round(avgWin),averageLossPct:round(avgLoss),payoffRatio:avgWin!=null&&avgLoss?round(avgWin/avgLoss,4):null,profitFactor:grossLoss?round(grossProfit/grossLoss,4):grossProfit>0?null:0,volatilityPct:round(vol),downsideDeviationPct:round(downside),sharpeLike:round(sharpeLike,4),sortinoLike:round(sortinoLike,4),maxDrawdownPctPoints:round(maxDrawdown),maxDrawdownRelativePct:round(maxDrawdownPct,4),maxDrawdownDuration,maxCurrentDrawdownDuration:drawdownDuration};}
export function bootstrapExpectancy(returns=[],{iterations=1000,seed='fxga'}={}){const x=finite(returns);if(x.length<3)return{iterations:0,mean:null,low95:null,high95:null,positiveProbability:null};const random=rng(seedOf(seed)),means=[];for(let i=0;i<iterations;i++){let sum=0;for(let n=0;n<x.length;n++)sum+=x[Math.floor(random()*x.length)];means.push(sum/x.length);}return{iterations,mean:round(mean(means)),low95:round(quantile(means,.025)),high95:round(quantile(means,.975)),positiveProbability:round(means.filter(v=>v>0).length/means.length,4)};}
export function permutationSignificance(trainDirection,holdoutReturns=[],{iterations=1000,seed='fxga-permutation'}={}){const x=finite(holdoutReturns);if(x.length<3||![-1,1].includes(Number(trainDirection)))return{iterations:0,pValue:null};const observed=mean(x.map(v=>Number(trainDirection)*v)),random=rng(seedOf(seed));let extreme=0;for(let i=0;i<iterations;i++){const shuffled=x.map(v=>(random()<.5?-1:1)*v),score=mean(shuffled);if(Math.abs(score||0)>=Math.abs(observed||0))extreme++;}return{iterations,pValue:round((extreme+1)/(iterations+1),6),observedDirectionalMeanPct:round(observed)};}
export function stressCosts(returns=[],baseCostPct=0){const multipliers=[1,1.5,2,3];return multipliers.map(multiplier=>{const net=finite(returns).map(v=>v-baseCostPct*multiplier),stats=equityStats(net);return{costMultiplier:multiplier,costPct:round(baseCostPct*multiplier),expectancyPct:stats.expectancyPct,totalNetPct:stats.totalNetPct,winRate:stats.winRate,maxDrawdownPctPoints:stats.maxDrawdownPctPoints,positive:Number(stats.expectancyPct)>0};});}
