const DAY_MS=86_400_000;
const clamp=(value,min=0,max=1)=>Math.max(min,Math.min(max,Number(value)||0));
const finite=value=>typeof value==='number'&&Number.isFinite(value);
const parseTime=value=>{const ms=Date.parse(value||'');return Number.isFinite(ms)?ms:null;};

export const QUALITY_STATES=['live','fresh','delayed','stale','last-known-good','disputed','missing','invalid'];
export function freshnessClass({timestamp,now=Date.now(),slaMs=15*60_000,maxAgeMs=7*DAY_MS}={}){const ms=parseTime(timestamp);if(ms==null)return{state:'missing',ageMs:null,score:0};const age=Math.max(0,now-ms);if(age<=slaMs)return{state:'live',ageMs:age,score:1};if(age<=slaMs*4)return{state:'fresh',ageMs:age,score:.9};if(age<=Math.min(maxAgeMs,slaMs*24))return{state:'delayed',ageMs:age,score:.7};if(age<=maxAgeMs)return{state:'stale',ageMs:age,score:.4};return{state:'invalid',ageMs:age,score:.1};}
export function completenessScore(value,required=[]){if(!value||typeof value!=='object')return 0;if(!required.length)return 1;const present=required.filter(key=>{const current=value[key];return current!==null&&current!==undefined&&current!=='';}).length;return present/required.length;}
export function agreementScore(values,tolerancePct=.15){const x=values.filter(finite);if(x.length<2)return null;const center=x.slice().sort((a,b)=>a-b)[Math.floor(x.length/2)],scale=Math.max(Math.abs(center),1e-9),deviations=x.map(value=>Math.abs(value-center)/scale*100),inside=deviations.filter(value=>value<=tolerancePct).length;return inside/x.length;}
export function qualityScore({timestamp,slaMs,maxAgeMs,completeness=1,sourceConfidence=1,agreement=null,staleFallback=false,disputed=false,invalid=false}={}){const freshness=freshnessClass({timestamp,slaMs,maxAgeMs});if(invalid)return{score:0,state:'invalid',freshness,components:{freshness:0,completeness:clamp(completeness),sourceConfidence:clamp(sourceConfidence),agreement:agreement==null?null:clamp(agreement)}};const components={freshness:freshness.score,completeness:clamp(completeness),sourceConfidence:clamp(sourceConfidence),agreement:agreement==null?null:clamp(agreement)};const agreementWeight=agreement==null?0:.15,base=.45*components.freshness+.25*components.completeness+(agreementWeight? .15:.30)*components.sourceConfidence+agreementWeight*(components.agreement??0);const score=clamp(staleFallback?base*.78:disputed?base*.65:base);const state=disputed?'disputed':staleFallback?'last-known-good':freshness.state;return{score:Number((score*100).toFixed(1)),state,freshness,components};}
export function provenance({source,sourceUrl=null,collectedAt=null,providerTimestamp=null,storedAt=null,transforms=[],fallbackSource=null,seriesId=null,symbol=null,eventId=null}={}){return{schema:'fxga.provenance.v1',source:source||'unknown',sourceUrl,seriesId,symbol,eventId,collectedAt,providerTimestamp,storedAt:storedAt||new Date().toISOString(),fallbackSource,transforms:Array.isArray(transforms)?transforms:[]};}
export function attachEvidenceQuality(observation,{timestampField='date',requiredFields=['value'],slaMs=45*DAY_MS,maxAgeMs=730*DAY_MS,sourceConfidence=.95,agreement=null}={}){const timestamp=observation?.[timestampField]||observation?.lastUpdated||observation?.collectedAt||null,completeness=completenessScore(observation,requiredFields),quality=qualityScore({timestamp,slaMs,maxAgeMs,completeness,sourceConfidence,agreement,staleFallback:Boolean(observation?.staleFallback),disputed:Boolean(observation?.disputed),invalid:Boolean(observation?.invalid)});return{...observation,evidenceQuality:quality,provenance:observation?.provenance||provenance({source:observation?.source,sourceUrl:observation?.sourceUrl||null,collectedAt:observation?.collectedAt||null,providerTimestamp:observation?.providerTimestamp||timestamp,fallbackSource:observation?.fallbackSource||null,seriesId:observation?.seriesId||null,symbol:observation?.symbol||observation?.id||null})};}
export function summarizeEvidenceQuality(rows=[]){const quality=rows.map(row=>Number(row?.evidenceQuality?.score)).filter(Number.isFinite);const counts={};for(const row of rows){const state=row?.evidenceQuality?.state||'unscored';counts[state]=(counts[state]||0)+1;}return{observations:rows.length,scored:quality.length,averageScore:quality.length?Number((quality.reduce((a,b)=>a+b,0)/quality.length).toFixed(1)):null,minScore:quality.length?Math.min(...quality):null,maxScore:quality.length?Math.max(...quality):null,states:counts};}
