import { clamp, mean, num, sigmoid } from './super-economist-core.js';

const PAIRS=[['EURUSD','EUR','USD'],['GBPUSD','GBP','USD'],['USDJPY','USD','JPY'],['EURGBP','EUR','GBP'],['USDZAR','USD','ZAR'],['EURZAR','EUR','ZAR'],['GBPZAR','GBP','ZAR'],['XAUUSD','XAU','USD']];
const SESSION_DEFS=[['sydney','Sydney','21:00-06:00',h=>h>=21||h<6],['tokyo','Tokyo','23:00-08:00',h=>h>=23||h<8],['london','London','07:00-16:00',h=>h>=7&&h<16],['new-york','New York','12:00-21:00',h=>h>=12&&h<21],['overlap','London/New York Overlap','12:00-16:00',h=>h>=12&&h<16]];
const ECONOMY_BY_CURRENCY={USD:'USA',EUR:'EUROPE',GBP:'UK',ZAR:'SOUTH_AFRICA',JPY:'JAPAN'};
const POLICY_COEFFICIENTS={
  USD:{inflation:.34,labour:.18,growth:.12,policy:.26,financial:.10},
  EUR:{inflation:.36,labour:.10,growth:.15,policy:.29,financial:.10},
  GBP:{inflation:.35,labour:.15,growth:.14,policy:.26,financial:.10},
  ZAR:{inflation:.34,labour:.08,growth:.14,policy:.26,financial:.18},
  JPY:{inflation:.30,labour:.12,growth:.14,policy:.30,financial:.14},
};
const COMPONENT_WEIGHTS={structure:.44,policy:.26,release:.18,narrative:.12};
const HAWKISH=/hawk|tighten|restrictive|raise(?:d|s)? rates?|rate hike|inflation(?:ary)? pressure|price pressure|persistent inflation|upside inflation|overheat|strong demand|wage pressure|higher for longer|normalization/i;
const DOVISH=/dovish|eas(?:e|ing)|rate cut|cut rates?|disinflation|deflation|downside risk|weak demand|slowdown|recession|labou?r slack|unemployment rise|support growth|accommodative/i;
const POSITIVE=/accelerat|strong|resilien|expan|improv|surge|rise|gain|beat|above expectation|record high/i;
const NEGATIVE=/contract|weak|deterior|declin|fall|drop|miss|below expectation|stress|crisis|recession/i;

function dim(state,id){return Number(state?.dimensions?.find(x=>x.id===id)?.score||0);}
function orientation(event){const t=`${event?.event||''} ${event?.category||''}`.toLowerCase();return /unemployment|jobless|claims|deficit|inventor(?:y|ies)|delinquen|default|layoff/.test(t)?-1:1;}
function eventEconomy(event){return ECONOMY_BY_CURRENCY[String(event?.currency||'').toUpperCase()]||null;}
function ageDecay(ageMinutes,halfLifeMinutes){return Math.exp(-Math.log(2)*Math.max(0,ageMinutes)/halfLifeMinutes);}
function weightedAverage(items){const den=items.reduce((s,x)=>s+x.weight,0);return den?items.reduce((s,x)=>s+x.value*x.weight,0)/den:0;}
function softmax3(a,b,c){const m=Math.max(a,b,c),ea=Math.exp(a-m),eb=Math.exp(b-m),ec=Math.exp(c-m),s=ea+eb+ec;return {buy:ea/s,sell:eb/s,wait:ec/s};}
function directionFrom(score,confidence,threshold,hardLock=false){if(hardLock||confidence<38||Math.abs(score)<threshold)return 'WAIT';return score>0?'BUY':'SELL';}
function scoreScenario(components){return COMPONENT_WEIGHTS.structure*components.structure+COMPONENT_WEIGHTS.policy*components.policy+COMPONENT_WEIGHTS.release*components.release+COMPONENT_WEIGHTS.narrative*components.narrative;}
function newsEconomy(item){const text=`${item?.region||''} ${item?.sourceName||''}`.toLowerCase();if(/south africa|reserve bank|sarb|statssa|statistics south africa/.test(text))return 'SOUTH_AFRICA';if(/japan|bank of japan|boj|statistics bureau/.test(text))return 'JAPAN';if(/euro|european central bank|ecb|eurostat/.test(text))return 'EUROPE';if(/united kingdom|bank of england|boe|ons/.test(text))return 'UK';if(/united states|federal reserve|bls|bea|treasury/.test(text))return 'USA';return null;}
function narrativeScore(items,economy,nowMs){const evidence=[];for(const item of items||[]){if(newsEconomy(item)!==economy)continue;const published=Date.parse(item.publishedAt||'');if(!Number.isFinite(published))continue;const ageHours=Math.max(0,(nowMs-published)/3600000);if(ageHours>120)continue;const text=`${item.title||''} ${item.summary||''}`;let raw=0;if(HAWKISH.test(text))raw+=1;if(DOVISH.test(text))raw-=1;if(POSITIVE.test(text))raw+=.35;if(NEGATIVE.test(text))raw-=.35;if(raw===0)continue;const authority=/central bank|federal reserve|bank of england|european central bank|bank of japan|reserve bank/i.test(`${item.category||''} ${item.sourceName||''}`)?1.25:1;const weight=authority*ageDecay(ageHours*60,36*60);evidence.push({value:clamp(raw,-1.5,1.5)*66.7,weight,title:item.title,source:item.sourceName,publishedAt:item.publishedAt});}const score=clamp(weightedAverage(evidence)/100,-1,1)*100;return {score:Math.round(score),evidence:evidence.sort((a,b)=>b.weight-a.weight).slice(0,5)};}
function releaseScore(events,currency,nowMs){const evidence=[];for(const event of events||[]){if(String(event.currency||'').toUpperCase()!==currency)continue;const t=Date.parse(event.date||'');if(!Number.isFinite(t)||t>nowMs||t<nowMs-12*3600000)continue;const actual=num(event.actual),forecast=num(event.forecast),previous=num(event.previous);if(actual==null||forecast==null)continue;const scale=Math.max(Math.abs(forecast)*.008,previous!=null?Math.abs(forecast-previous)*.5:0,1e-6);const standardized=clamp((actual-forecast)/scale,-3,3)*orientation(event);const ageMinutes=(nowMs-t)/60000,impact=Math.max(1,Number(event.importance||1)),weight=(.6+.4*impact/3)*ageDecay(ageMinutes,150);evidence.push({value:standardized/3*100,weight,event:event.event,actual,forecast,ageMinutes:Math.round(ageMinutes),importance:impact});}const score=clamp(weightedAverage(evidence)/100,-1,1)*100;return {score:Math.round(score),evidence:evidence.sort((a,b)=>b.weight-a.weight).slice(0,6)};}
function policyReaction(state,narrative){const currency=state.currency,coef=POLICY_COEFFICIENTS[currency]||POLICY_COEFFICIENTS.USD;const raw=coef.inflation*dim(state,'inflation')+coef.labour*dim(state,'labour')+coef.growth*dim(state,'growth')+coef.policy*dim(state,'policy')+coef.financial*dim(state,'financial');return Math.round(clamp((raw*.88+narrative*.12)/100,-1,1)*100);}
function qualityState(state){const dimensionsCovered=(state.dimensions||[]).filter(d=>Number(d.coverage||0)>0).length,observations=Number(state.observationCount||0),confidence=Number(state.confidence||0),structural=observations>=8&&dimensionsCovered>=3&&confidence>=35;return {dimensionsCovered,observations,confidence,quality:structural?'structural':'provisional',factor:clamp((confidence/100)*Math.min(1,dimensionsCovered/4)*Math.min(1,observations/18),.08,1)};}
function nearestCatalyst(events,currencies,nowMs){return (events||[]).filter(e=>currencies.includes(String(e.currency||'').toUpperCase())&&Number(e.importance||1)>=2&&Date.parse(e.date)>=nowMs-20*60000).map(e=>({...e,delta:Date.parse(e.date)-nowMs})).filter(e=>e.delta<=8*3600000).sort((a,b)=>Math.abs(a.delta)-Math.abs(b.delta))[0]||null;}
function eventRisk(catalyst){if(!catalyst)return {risk:'normal',penalty:1,hardLock:false,minutes:null};const minutes=Math.round(catalyst.delta/60000),abs=Math.abs(minutes);if(Number(catalyst.importance||1)>=3&&abs<=20)return {risk:'event-lockout',penalty:0,hardLock:true,minutes};if(Number(catalyst.importance||1)>=3&&abs<=90)return {risk:'elevated',penalty:.62,hardLock:false,minutes};if(abs<=180)return {risk:'elevated',penalty:.82,hardLock:false,minutes};return {risk:'normal',penalty:1,hardLock:false,minutes};}
function contradictionAudit(components,score){const sign=Math.sign(score),contradictions=[];for(const [name,value] of Object.entries(components)){if(name==='market')continue;if(Math.abs(value)>=18&&sign&&Math.sign(value)!==sign)contradictions.push(`${name} opposes the aggregate edge (${value>0?'+':''}${Math.round(value)})`);}return contradictions;}
function agreementScore(components,score){const entries=Object.entries(COMPONENT_WEIGHTS).map(([name,weight])=>({value:Number(components[name]||0),weight}));const dispersion=Math.sqrt(entries.reduce((s,x)=>s+x.weight*((x.value-score)**2),0));return clamp(1-dispersion/115,.22,1);}
function componentContribution(components){return Object.fromEntries(Object.entries(COMPONENT_WEIGHTS).map(([k,w])=>[k,Math.round((components[k]||0)*w*10)/10]));}
function counterThesis(components,score){const opposing=Object.entries(components).filter(([k,v])=>k!=='market'&&Math.sign(v)&&Math.sign(v)!==Math.sign(score)).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1]));if(opposing.length)return `The strongest opposing evidence is ${opposing[0][0]} at ${Math.round(opposing[0][1])}; if it strengthens, the aggregate thesis can fail.`;return 'No major component currently opposes the aggregate direction, but an event surprise or policy repricing can still invalidate the thesis.';}
function whatChangesMind(symbol,score,threshold,catalyst){const side=score>=0?'positive':'negative';const reverse=score>=0?'below':'above';const list=[`Aggregate score crossing ${reverse} ${score>=0?-threshold:threshold}.`,`Structure or policy divergence reversing the current ${side} sign by at least 20 points.`,`A fresh high-impact release producing a strong opposite standardized surprise.`,`Family confidence falling below 38/100 or evidence coverage becoming provisional.`];if(catalyst)list.unshift(`${catalyst.event} materially contradicting the current thesis.`);return list;}
function scenarioSensitivity(components,confidence,threshold){const scenarios=[['structure +20',{...components,structure:clamp((components.structure+20)/100,-1,1)*100}],['structure -20',{...components,structure:clamp((components.structure-20)/100,-1,1)*100}],['policy +20',{...components,policy:clamp((components.policy+20)/100,-1,1)*100}],['policy -20',{...components,policy:clamp((components.policy-20)/100,-1,1)*100}],['release reversal',{...components,release:-components.release}]];return scenarios.map(([name,c])=>{const score=Math.round(scoreScenario(c));return {name,score,direction:directionFrom(score,confidence,threshold,false)};});}
function pairModel(symbol,base,quote,byCurrency,releaseByCurrency,narrativeByEconomy,events,nowMs){const q=byCurrency.get(quote),b=byCurrency.get(base),quoteQuality=q?qualityState(q):null,baseQuality=b?qualityState(b):null;let structure=0,policy=0,release=0,narrative=0,baseScore=0,quoteScore=q?.currencyScore||0,basePolicy=0,quotePolicy=q?policyReaction(q,narrativeByEconomy[q.id]?.score||0):0,coverage='full',missing=['real-time market-price confirmation'];if(base==='XAU'){const riskBid=-(dim(q,'financial')||0);structure=Math.round(-.45*quoteScore-.35*dim(q,'policy')+.20*riskBid);policy=-quotePolicy;release=-(releaseByCurrency[quote]?.score||0);narrative=-(narrativeByEconomy[q?.id]?.score||0);baseScore=structure;coverage='asset-model';}else{baseScore=b?.currencyScore||0;const basePolicyScore=b?policyReaction(b,narrativeByEconomy[b.id]?.score||0):0;structure=baseScore-quoteScore;policy=basePolicyScore-quotePolicy;release=(releaseByCurrency[base]?.score||0)-(releaseByCurrency[quote]?.score||0);narrative=(narrativeByEconomy[b?.id]?.score||0)-(narrativeByEconomy[q?.id]?.score||0);basePolicy=basePolicyScore;if(!b||!q)coverage='partial';}
  const components={structure:clamp(structure/100,-1,1)*100,policy:clamp(policy/100,-1,1)*100,release:clamp(release/100,-1,1)*100,narrative:clamp(narrative/100,-1,1)*100,market:0};
  const raw=Math.round(scoreScenario(components));const agreement=agreementScore(components,raw),contradictions=contradictionAudit(components,raw),currencies=base==='XAU'?[quote]:[base,quote],catalyst=nearestCatalyst(events,currencies,nowMs),risk=eventRisk(catalyst);const qFactor=base==='XAU'?(quoteQuality?.factor||.08):Math.sqrt((baseQuality?.factor||.08)*(quoteQuality?.factor||.08));const confidence=Math.round(100*clamp(qFactor*agreement*.90*risk.penalty,0,1));const threshold=Math.round(16+10*(1-confidence/100)+2*Math.min(3,contradictions.length));const direction=directionFrom(raw,confidence,threshold,risk.hardLock);const executionGate=risk.hardLock?'WAIT_EVENT':direction==='WAIT'?'NO_MACRO_EDGE':'AWAIT_TECHNICAL_CONFIRMATION';const conviction=Math.round(Math.min(100,(Math.abs(raw)*.58+confidence*.42)*Math.max(.35,risk.penalty)));const convictionLabel=conviction>=70?'high':conviction>=45?'medium':'low';const waitUtility=(threshold-Math.abs(raw))/11+(1-confidence/100)*1.5+contradictions.length*.35+(risk.hardLock?4:0),edgeUtility=raw/18*(confidence/100),probabilities=softmax3(edgeUtility,-edgeUtility,waitUtility);const contributions=componentContribution(components);const centralBankDivergence=base==='XAU'?`Gold sensitivity versus ${q?.centralBank||quote}`:`${b?.centralBank||base} vs ${q?.centralBank||quote}: ${policy>=0?'+':''}${Math.round(policy)} reaction-score spread`;const regimes=base==='XAU'?['gold defensive asset model',q?.regime||'unknown']:[b?.regime||'unknown',q?.regime||'unknown'];const rationale=[`Structure ${Math.round(components.structure)} contributes ${contributions.structure}.`,`Policy ${Math.round(components.policy)} contributes ${contributions.policy}.`,`Recent release impulse ${Math.round(components.release)} contributes ${contributions.release}.`,`Official-source narrative ${Math.round(components.narrative)} contributes ${contributions.narrative}.`,`Evidence agreement ${Math.round(agreement*100)}%; data-quality confidence ${confidence}/100.`];if(risk.risk!=='normal')rationale.push(`${risk.risk}: ${catalyst?.event||'high-impact catalyst'} ${risk.minutes==null?'':`${risk.minutes}m from now`}.`);if(contradictions.length)rationale.push(`Contradictions: ${contradictions.join('; ')}.`);
  return {symbol,direction,score:raw,confidence,conviction,convictionLabel,coverage,risk:risk.risk,executionGate,components:{structuralDivergence:Math.round(components.structure),policyDivergence:Math.round(components.policy),releaseDivergence:Math.round(components.release),narrativeDivergence:Math.round(components.narrative),marketConfirmation:0,baseCurrencyScore:Math.round(baseScore),quoteCurrencyScore:Math.round(quoteScore)},centralBankDivergence,regimes,rationale,invalidation:`Invalid if aggregate score crosses ${raw>=0?-threshold:threshold}, confidence falls below 38, or a high-impact catalyst reverses the thesis.`,catalyst:catalyst?.event,catalystAt:catalyst?.date,minutesToCatalyst:risk.minutes,threshold,probabilities,criticalThinking:{thesis:`${symbol} ${raw>=0?'favours the base/long side':'favours the quote/short side'} with aggregate macro edge ${raw}.`,counterThesis:counterThesis(components,raw),contradictions,missingEvidence:missing,whatWouldChangeMyMind:whatChangesMind(symbol,raw,threshold,catalyst),scenarioSensitivity:scenarioSensitivity(components,confidence,threshold)},equationTrace:{rawScore:raw,weights:COMPONENT_WEIGHTS,contributions,agreement:Number(agreement.toFixed(4)),dataQuality:Number(qFactor.toFixed(4)),eventPenalty:risk.penalty,decisionThreshold:threshold}};}

export function buildDecisionMatrix({economies=[],events=[],news=[],now=new Date()}={}){
  const nowMs=now.getTime(),byCurrency=new Map(economies.map(e=>[e.currency,e])),releaseByCurrency={},narrativeByEconomy={};for(const currency of Object.keys(ECONOMY_BY_CURRENCY))releaseByCurrency[currency]=releaseScore(events,currency,nowMs);for(const economy of economies)narrativeByEconomy[economy.id]=narrativeScore(news,economy.id,nowMs);
  const currencyStates=economies.map(e=>{const q=qualityState(e),n=narrativeByEconomy[e.id],r=releaseByCurrency[e.currency],reaction=policyReaction(e,n.score);return {id:e.id,currency:e.currency,economy:e.label,centralBank:e.centralBank,regime:e.regime,policyStance:e.policyStance,policyScore:reaction,score:e.currencyScore,confidence:e.confidence,observationCount:e.observationCount,dimensionsCovered:q.dimensionsCovered,quality:q.quality,narrativeScore:n.score,releaseImpulse:r.score};}).sort((a,b)=>b.score-a.score).map((x,i)=>({...x,rank:i+1}));
  const opportunities=PAIRS.map(([symbol,base,quote])=>pairModel(symbol,base,quote,byCurrency,releaseByCurrency,narrativeByEconomy,events,nowMs)).sort((a,b)=>b.conviction-a.conviction);
  const hours=now.getUTCHours()+now.getUTCMinutes()/60,sessions=SESSION_DEFS.map(([id,label,windowUtc,isActive])=>{const active=isActive(hours),signals=opportunities.map(x=>({...x})),focus=[...new Set(signals.flatMap(s=>s.symbol==='XAUUSD'?['USD']:s.symbol.match(/.{3}/g)||[]))],nearby=events.filter(e=>Math.abs(Date.parse(e.date)-nowMs)<8*3600000&&focus.includes(e.currency));return {id,label,windowUtc,active,state:active?'active':'upcoming',risk:signals.some(s=>s.risk==='event-lockout')?'event-lockout':signals.some(s=>s.risk==='elevated')?'elevated':'normal',focusCurrencies:focus,nextCatalyst:nearby.sort((a,b)=>Math.abs(Date.parse(a.date)-nowMs)-Math.abs(Date.parse(b.date)-nowMs))[0]?.event,eventCount:nearby.length,signals};});
  const actionable=opportunities.filter(x=>x.direction!=='WAIT'),top=actionable[0]||opportunities[0]||null;
  const equations={familyWeight:'w_f = availability × freshness × dataQuality × reliability² × causalRelevance × independencePenalty',dimensionScore:'D_k = robustWeightedMean(family z-scores in dimension k)',policyReaction:'PR_c = Σ beta(c,k) × D_k + 0.12 × officialNarrative',releaseImpulse:'R_c = weightedMean[ orientation × (actual-consensus)/robustScale × exp(-ln2×age/150m) ]',pairScore:'S_pair = 0.44×Structure + 0.26×Policy + 0.18×Release + 0.12×Narrative',agreement:'A = max(0.22, 1 - weightedDispersion(components)/115)',confidence:'C = dataQuality × agreement × 0.90(missing market confirmation) × eventPenalty',dynamicThreshold:'T = 16 + 10×(1-C) + 2×min(3, contradictionCount)',decision:'BUY if Score≥T and C≥0.38; SELL if Score≤-T and C≥0.38; otherwise WAIT; ±20m high-impact event => WAIT_EVENT',probabilities:'P(BUY), P(SELL), P(WAIT) = softmax(edgeUtility, -edgeUtility, waitUtility)'};
  return {generatedAt:now.toISOString(),methodology:'FXGA Critical Intelligence Matrix v4: independent-family macro evidence + central-bank reaction + decayed release surprise + official-source narrative + contradiction audit.',caution:'The engine must explain uncertainty and can choose WAIT. Real-time market-price/order-book confirmation is deliberately marked missing until a Google-side market feed is connected.',macroRegime:economies.find(e=>e.id==='USA')?.regime||'mixed',macroConfidence:economies.find(e=>e.id==='USA')?.confidence||0,currencyStates,rankedOpportunities:opportunities,sessions,decisionSummary:{strongestCurrency:currencyStates[0]?.currency||null,weakestCurrency:currencyStates.at(-1)?.currency||null,actionableCount:actionable.length,waitCount:opportunities.length-actionable.length,topOpportunity:top?{symbol:top.symbol,direction:top.direction,score:top.score,confidence:top.confidence,conviction:top.conviction,executionGate:top.executionGate}:null},dataQuality:{minimumStructuralObservations:8,minimumCoveredDimensions:3,structuralEconomies:currencyStates.filter(x=>x.quality==='structural').map(x=>x.id),provisionalEconomies:currencyStates.filter(x=>x.quality==='provisional').map(x=>x.id)},intelligenceMatrix:{equations,componentWeights:COMPONENT_WEIGHTS,currencyEvidence:Object.fromEntries(currencyStates.map(c=>[c.currency,{structuralScore:c.score,policyReaction:c.policyScore,releaseImpulse:c.releaseImpulse,narrativeImpulse:c.narrativeScore,confidence:c.confidence,quality:c.quality}])),pairCount:opportunities.length,missingGlobalInputs:['real-time cross-asset market confirmation','order-book/option-surface microstructure','alternative data'],criticalThinkingRules:['separate thesis from counter-thesis','penalize component disagreement','increase threshold when contradictions rise','lock execution around high-impact releases','state missing evidence explicitly','define what would change the decision','recompute counterfactual scenarios before BUY/SELL']}};
}

export { eventEconomy, orientation, narrativeScore, releaseScore, policyReaction };
