import { DurableObject } from 'cloudflare:workers';
import { verifyCollectorWebhook } from './collector-webhook';
import type { CalendarEvent, Env, MacroObservation } from './types';

const CALENDAR_KEY='google:calendar';
const MACRO_KEY='google:macro';
const INTELLIGENCE_KEY='google:intelligence';
const MARKET_KEY='google:market';
const TECHNICAL_KEY='market:technical';
const EVENT_STUDIES_KEY='research:event-studies';
const META_KEY='google:meta';
const REPLAY_KEY='google:recent-request-ids';
const INTELLIGENCE_CHUNK_CHARS=60_000;
const TARGET_ECONOMIES=['USA','EUROPE','UK','SOUTH_AFRICA','JAPAN'] as const;
const SECURITY_HEADERS={'X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=()'};
function json(data:unknown,init:ResponseInit={}){const headers=new Headers(init.headers);headers.set('Content-Type','application/json; charset=utf-8');for(const [k,v] of Object.entries(SECURITY_HEADERS))headers.set(k,v);return new Response(JSON.stringify(data),{...init,headers});}
function error(message:string,status=400){return json({error:message},{status,headers:{'Cache-Control':'no-store'}});}
function coordinator(env:Env){return env.FXGA_COORDINATOR.getByName('global-calendar-v3');}
function normalizeObservation(item:any):MacroObservation{return {seriesId:String(item?.seriesId??''),title:String(item?.title??item?.seriesId??''),value:typeof item?.value==='number'?item.value:null,date:typeof item?.date==='string'?item.date:null,previous:typeof item?.previous==='number'?item.previous:null,change:typeof item?.change==='number'?item.change:null,units:String(item?.units??''),frequency:String(item?.frequency??''),categories:Array.isArray(item?.categories)?item.categories.map(String):[],economy:typeof item?.economy==='string'?item.economy:undefined,economies:Array.isArray(item?.economies)?item.economies.map(String):undefined,importance:item?.importance==='critical'?'critical':'high',source:typeof item?.source==='string'?item.source:'Primary data network',lastUpdated:typeof item?.lastUpdated==='string'?item.lastUpdated:undefined,history:Array.isArray(item?.history)?item.history.filter((x:any)=>x&&typeof x.date==='string'&&typeof x.value==='number'):[]} as MacroObservation;}
function groupMacro(observations:MacroObservation[],generatedAt:string|null=null){const economies:Record<string,MacroObservation[]>=Object.fromEntries(TARGET_ECONOMIES.map(e=>[e,[]]));const global:MacroObservation[]=[];for(const observation of observations){const tags=Array.isArray((observation as any).economies)&&(observation as any).economies.length?(observation as any).economies.map(String):[String((observation as any).economy??'GLOBAL')];let assigned=false;for(const economy of TARGET_ECONOMIES)if(tags.includes(economy)){economies[economy].push(observation);assigned=true;}if(!assigned||tags.includes('GLOBAL'))global.push(observation);}return {generatedAt,mode:publicMode(),targetEconomies:TARGET_ECONOMIES,totalObservations:observations.length,counts:Object.fromEntries(TARGET_ECONOMIES.map(e=>[e,economies[e].length])),economies,global};}
function compactQualityAudit(audit:any){if(!audit||typeof audit!=='object')return audit;const {methods:_,...rest}=audit;return rest;}
function compactResearch(intel:any){if(!intel?.research)return null;const research={...intel.research};if(research.qualityCalibrationEvidence)research.qualityCalibrationEvidence=compactQualityAudit(research.qualityCalibrationEvidence);return {...research,decisionCore:intel.decisionGovernance??null,decisionMemory:intel.decisionMemory??null,intelligenceGeneratedAt:intel.generatedAt??null};}
function compactSessionSignals(intel:any){if(!intel?.sessionSignals)return null;const sessionSignals={...intel.sessionSignals};if(sessionSignals.researchSummary?.qualityCalibrationEvidence)sessionSignals.researchSummary={...sessionSignals.researchSummary,qualityCalibrationEvidence:compactQualityAudit(sessionSignals.researchSummary.qualityCalibrationEvidence)};return sessionSignals;}
function compactPublicIntelligence(intel:any){if(!intel||typeof intel!=='object')return intel;const {executionLocation:_,registry:__,collectorMode:___,...rest}=intel;const output={...rest};if(output.qualityCalibrationEvidence)output.qualityCalibrationEvidence=compactQualityAudit(output.qualityCalibrationEvidence);if(output.research)output.research=compactResearch(intel);if(output.sessionSignals)output.sessionSignals=compactSessionSignals(intel);return output;}
const SOURCE_VIEW=[{id:'macro-primary',name:'FRED Economic Data',category:'Macro Data API',region:'Global',status:'live',note:'Primary macroeconomic series with last-good retention and freshness controls.'},{id:'calendar-primary',name:'Global Economic Calendar',category:'Economic Calendar',region:'Global',status:'live',note:'Economic releases with actual, consensus, previous, revision and currency-bias history.'},{id:'calendar-crosscheck',name:'Calendar Cross Check',category:'Economic Calendar',region:'Global',status:'live',note:'Independent calendar source used for reconciliation and release validation.'},{id:'official-publications',name:'Official Central Bank & Statistics Feeds',category:'Official Publications',region:'Global',status:'live',note:'Primary-source statements, releases and statistical publications.'},{id:'decision-research',name:'Decision Research Engine',category:'Research & Risk',region:'Global',status:'live',note:'Macro, event, risk, scenario and probability research used by the dashboard.'}] as const;

export class FxgaCoordinator extends DurableObject<Env>{
  private intelligenceCache:any=null;
  constructor(ctx:DurableObjectState,env:Env){super(ctx,env);}
  private intelligenceChunkKey(generation:string,index:number){return `${INTELLIGENCE_KEY}:chunk:${generation}:${String(index).padStart(4,'0')}`;}
  private async deleteIntelligenceChunks(manifest:any){if(!manifest?.chunked||!manifest?.generation||!Number.isInteger(Number(manifest?.chunkCount)))return;const count=Number(manifest.chunkCount);for(let i=0;i<count;i+=12){const indexes=Array.from({length:Math.min(12,count-i)},(_,offset)=>i+offset);await Promise.all(indexes.map(index=>this.ctx.storage.delete(this.intelligenceChunkKey(String(manifest.generation),index)).catch(()=>false)));}}
  private async readIntelligence(){if(this.intelligenceCache)return this.intelligenceCache;const stored=await this.ctx.storage.get<any>(INTELLIGENCE_KEY);if(!stored?.chunked){this.intelligenceCache=stored??null;return this.intelligenceCache;}const generation=String(stored.generation||''),count=Number(stored.chunkCount||0);if(!generation||!Number.isInteger(count)||count<1)throw new Error('Intelligence chunk manifest is invalid');const chunks:string[]=[];for(let i=0;i<count;i+=12){const indexes=Array.from({length:Math.min(12,count-i)},(_,offset)=>i+offset),values=await Promise.all(indexes.map(index=>this.ctx.storage.get<string>(this.intelligenceChunkKey(generation,index))));for(let j=0;j<values.length;j++){const value=values[j],index=indexes[j];if(typeof value!=='string')throw new Error(`Intelligence chunk ${index+1}/${count} is missing`);chunks[index]=value;}}const serialized=chunks.join('');if(Number(stored.charLength||0)&&serialized.length!==Number(stored.charLength))throw new Error('Intelligence chunk length mismatch');this.intelligenceCache=JSON.parse(serialized);return this.intelligenceCache;}
  private async writeIntelligence(payload:Record<string,any>,requestId:string){const serialized=JSON.stringify(payload),previous=await this.ctx.storage.get<any>(INTELLIGENCE_KEY);if(serialized.length<=INTELLIGENCE_CHUNK_CHARS){await this.ctx.storage.put(INTELLIGENCE_KEY,payload);this.intelligenceCache=payload;if(previous?.chunked)await this.deleteIntelligenceChunks(previous);return {chunked:false,charLength:serialized.length,chunkCount:1};}const generation=(requestId||crypto.randomUUID()).replace(/[^a-zA-Z0-9_-]/g,'').slice(0,48)||String(Date.now()),chunks=[] as string[];for(let offset=0;offset<serialized.length;offset+=INTELLIGENCE_CHUNK_CHARS)chunks.push(serialized.slice(offset,offset+INTELLIGENCE_CHUNK_CHARS));for(let i=0;i<chunks.length;i+=10){const indexes=Array.from({length:Math.min(10,chunks.length-i)},(_,offset)=>i+offset);await Promise.all(indexes.map(index=>this.ctx.storage.put(this.intelligenceChunkKey(generation,index),chunks[index])));}await this.ctx.storage.put(INTELLIGENCE_KEY,{chunked:true,version:1,generation,chunkCount:chunks.length,charLength:serialized.length,generatedAt:payload.generatedAt??new Date().toISOString()});this.intelligenceCache=payload;if(previous?.chunked&&previous.generation!==generation)await this.deleteIntelligenceChunks(previous);return {chunked:true,charLength:serialized.length,chunkCount:chunks.length};}
  private broadcast(payload:unknown){const message=JSON.stringify(payload);for(const socket of this.ctx.getWebSockets())if(socket.readyState===WebSocket.OPEN){try{socket.send(message);}catch{}}}
  private async remember(requestId:string){const recent=(await this.ctx.storage.get<string[]>(REPLAY_KEY))??[];if(recent.includes(requestId))return false;await this.ctx.storage.put(REPLAY_KEY,[...recent,requestId].slice(-500));return true;}
  private async applyWebhook(requestId:string,envelope:Record<string,any>){
    if(!(await this.remember(requestId)))return {duplicate:true};const type=String(envelope.type??''),payload=envelope.payload as Record<string,any>;
    if(type==='calendar-snapshot'){if(!Array.isArray(payload?.events))throw new Error('calendar-snapshot missing events');await this.ctx.storage.put(CALENDAR_KEY,payload);}
    else if(type==='release-delta'){const existing=(await this.ctx.storage.get<Record<string,any>>(CALENDAR_KEY))??{events:[]};const byId=new Map<string,CalendarEvent>((existing.events??[]).map((e:CalendarEvent)=>[e.id,e]));for(const event of Array.isArray(payload?.events)?payload.events:[]){if(!event?.id)continue;byId.set(event.id,{...(byId.get(event.id)??{}),...event} as CalendarEvent);const historyKey=`google-release:${event.id}`;const history=(await this.ctx.storage.get<any[]>(historyKey))??[];await this.ctx.storage.put(historyKey,[...history,{capturedAt:envelope.generatedAt??new Date().toISOString(),event}].slice(-30));}await this.ctx.storage.put(CALENDAR_KEY,{...existing,generatedAt:envelope.generatedAt??new Date().toISOString(),events:[...byId.values()]});}
    else if(type==='macro-snapshot'){const observations:MacroObservation[]=(Array.isArray(payload?.observations)?payload.observations:[]).filter((x:any)=>x?.seriesId).map(normalizeObservation);if(!observations.length)throw new Error('macro-snapshot missing observations');await this.ctx.storage.put(MACRO_KEY,{...payload,observations});}
    else if(type==='market-snapshot'){if(!Array.isArray(payload?.assets))throw new Error('market-snapshot missing assets');await this.ctx.storage.put(MARKET_KEY,payload);}
    else if(type==='technical-snapshot'){if(!payload?.assets||typeof payload.assets!=='object')throw new Error('technical-snapshot missing assets');await this.ctx.storage.put(TECHNICAL_KEY,payload);}
    else if(type==='event-study-snapshot'){if(!Array.isArray(payload?.studies))throw new Error('event-study-snapshot missing studies');await this.ctx.storage.put(EVENT_STUDIES_KEY,payload);}
    else if(type==='intelligence-snapshot'){if(Number(payload?.registry?.totalMethods)!==9705||Number(payload?.registry?.totalFamilies)!==150)throw new Error('intelligence-snapshot registry contract failed');const stored=await this.writeIntelligence(payload,requestId);console.log('Stored intelligence snapshot',JSON.stringify(stored));}
    else throw new Error(`Unsupported collector webhook type: ${type}`);
    const previous=(await this.ctx.storage.get<Record<string,any>>(META_KEY))??{};const meta={...previous,lastWebhookAt:new Date().toISOString(),lastType:type,lastRequestId:requestId,updates:Number(previous.updates??0)+1};await this.ctx.storage.put(META_KEY,meta);this.broadcast({type:'data-update',updateType:type,timestamp:meta.lastWebhookAt});return {accepted:true,type,updates:meta.updates};
  }
  private async liteState(){const [calendar,macro,market,technical,eventStudies,meta]=await Promise.all([this.ctx.storage.get<Record<string,any>>(CALENDAR_KEY),this.ctx.storage.get<Record<string,any>>(MACRO_KEY),this.ctx.storage.get<Record<string,any>>(MARKET_KEY),this.ctx.storage.get<Record<string,any>>(TECHNICAL_KEY),this.ctx.storage.get<Record<string,any>>(EVENT_STUDIES_KEY),this.ctx.storage.get<Record<string,any>>(META_KEY)]);const events=Array.isArray(calendar?.events)?calendar!.events as CalendarEvent[]:[];const now=Date.now();const upcoming=events.filter(e=>Date.parse(e.date)>=now).slice(0,250).map(event=>({event,releaseAt:event.date}));const active=events.filter(e=>Math.abs(Date.parse(e.date)-now)<=10*60000).map(event=>({event,releaseAt:event.date}));const recent=events.filter(e=>Date.parse(e.date)<now&&Date.parse(e.date)>=now-6*3600000).slice(-100).map(event=>({event,releaseAt:event.date}));return {calendar,macro,market,technical,eventStudies,meta,events,upcoming,active,recent,initialized:Boolean(events.length&&macro?.observations?.length)};}
  private async basicIntelligence(){const intel=await this.readIntelligence();if(!intel)return null;return {generatedAt:intel.generatedAt??null,macroAnalysis:intel.macroAnalysis??null,economyAnalysis:intel.economyAnalysis??null,sessionSignals:compactSessionSignals(intel),releaseImpact:intel.releaseImpact??null,news:Array.isArray(intel.news)?intel.news:[],fredCatalog:intel.fredCatalog??null,globalMacro:intel.globalMacro??null,operationalHealth:intel.operationalHealth??null};}
  async fetch(request:Request):Promise<Response>{const url=new URL(request.url);if(url.pathname==='/ws'){if(request.headers.get('Upgrade')?.toLowerCase()!=='websocket')return new Response('Expected WebSocket upgrade',{status:426});const pair=new WebSocketPair(),[client,server]=Object.values(pair);this.ctx.acceptWebSocket(server);server.serializeAttachment({connectedAt:Date.now()});server.send(JSON.stringify({type:'connected',channel:'macro-intelligence-live',timestamp:new Date().toISOString()}));return new Response(null,{status:101,webSocket:client});}if(url.pathname==='/collector/webhook'&&request.method==='POST'){if(request.headers.get('X-FXGA-Verified')!=='1')return json({error:'Unverified internal collector request'},{status:403});try{return json(await this.applyWebhook(request.headers.get('X-FXGA-Request-Id')?.trim()??'',await request.json() as Record<string,any>));}catch(e){return json({error:e instanceof Error?e.message:'Collector update failed'},{status:400});}}if(url.pathname==='/lite-state')return json(await this.liteState());if(url.pathname==='/basic-intelligence'){const intel=await this.basicIntelligence();return intel?json(intel):error('Decision research is not initialized',503);}if(url.pathname==='/research'){const intel=await this.readIntelligence(),research=compactResearch(intel);return research?json(research):error('Research snapshot is not initialized',503);}if(url.pathname==='/scenarios'){const intel=await this.readIntelligence();return intel?.research?.scenarios?json({generatedAt:intel.research.generatedAt,scenarios:intel.research.scenarios}):error('Scenario research is not initialized',503);}if(url.pathname==='/release-analytics'){const intel=await this.readIntelligence();return intel?.research?.releaseAnalytics?json(intel.research.releaseAnalytics):error('Release analytics are not initialized',503);}if(url.pathname==='/public-intelligence'){const intel=await this.readIntelligence();return intel?json(compactPublicIntelligence(intel)):error('Decision research is not initialized',503);}if(url.pathname==='/status'){const s=await this.liteState();return json({collectorMode:'external-webhook',websocketClients:this.ctx.getWebSockets().length,lastWebhookAt:s.meta?.lastWebhookAt??null,initialized:s.initialized,safety:{upstreamCalendarRequestsFromCloudflare:0,upstreamFredRequestsFromCloudflare:0,upstreamNewsRequestsFromCloudflare:0,upstreamMarketRequestsFromCloudflare:0,browserSecondsFromCloudflare:0}});}if(url.pathname==='/release'){const id=url.searchParams.get('id')?.trim()??'';return json({id,snapshots:id?(await this.ctx.storage.get<any[]>(`google-release:${id}`))??[]:[]});}return new Response('Not found',{status:404});}
  async alarm(){return;}
}

async function getCoordinatorJson(env:Env,path:string){const response=await coordinator(env).fetch(`https://fxga-coordinator.internal${path}`);if(!response.ok)throw new Error(`Passive state ${response.status}`);return await response.json() as Record<string,any>;}
async function getState(env:Env){return getCoordinatorJson(env,'/lite-state');}
async function getBasicIntelligence(env:Env){return getCoordinatorJson(env,'/basic-intelligence');}
function eventsFromState(s:Record<string,any>):CalendarEvent[]{return Array.isArray(s?.events)?s.events as CalendarEvent[]:[];}
function macroFromState(s:Record<string,any>):MacroObservation[]{const raw:any[]=Array.isArray(s?.macro?.observations)?s.macro.observations:[];return raw.map(normalizeObservation);}
function publicMode(){return 'authenticated-primary-data-service';}
function filterMacro(observations:MacroObservation[],url:URL){const raw=url.searchParams.get('series');let selected=observations;if(raw){const ids=new Set(raw.split(',').map(x=>x.trim().toUpperCase()).filter(Boolean));selected=selected.filter(x=>ids.has(x.seriesId.toUpperCase()));}const category=url.searchParams.get('category');if(category)selected=selected.filter(x=>x.categories?.includes(category));const q=url.searchParams.get('q')?.toLowerCase();if(q)selected=selected.filter(x=>`${x.seriesId} ${x.title} ${(x.categories||[]).join(' ')}`.toLowerCase().includes(q));const limit=Math.min(220,Math.max(1,Number(url.searchParams.get('limit')||16)));return selected.slice(0,limit);}

export default{
  async fetch(request:Request,env:Env):Promise<Response>{
    const url=new URL(request.url);if(!url.pathname.startsWith('/api/'))return new Response(null,{status:404});
    if(url.pathname==='/api/collector-webhook'){if(request.method!=='POST')return error('Method not allowed',405);if(!env.COLLECTOR_WEBHOOK_SECRET)return error('Collector webhook is not configured',503);try{const verified=await verifyCollectorWebhook(request,env.COLLECTOR_WEBHOOK_SECRET);const upstream=await coordinator(env).fetch(new Request('https://fxga-coordinator.internal/collector/webhook',{method:'POST',headers:{'Content-Type':'application/json','X-FXGA-Verified':'1','X-FXGA-Request-Id':verified.requestId},body:verified.rawBody}));return new Response(upstream.body,{status:upstream.status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...SECURITY_HEADERS}});}catch(e){return error(e instanceof Error?e.message:'Collector webhook rejected',401);}}
    if(url.pathname==='/api/live'){if(request.method!=='GET')return error('Method not allowed',405);return coordinator(env).fetch(new Request('https://fxga-coordinator.internal/ws',request));}
    if(request.method!=='GET')return error('Method not allowed',405);
    if(url.pathname==='/api/research')return coordinator(env).fetch('https://fxga-coordinator.internal/research');
    if(url.pathname==='/api/scenarios')return coordinator(env).fetch('https://fxga-coordinator.internal/scenarios');
    if(url.pathname==='/api/release-analytics')return coordinator(env).fetch('https://fxga-coordinator.internal/release-analytics');
    if(url.pathname==='/api/super-economist'||url.pathname==='/api/decision-intelligence')return coordinator(env).fetch('https://fxga-coordinator.internal/public-intelligence');
    try{
      const s=await getState(env),events=eventsFromState(s),observations=macroFromState(s);
      const basicPaths=new Set(['/api/health','/api/dashboard','/api/analysis','/api/economy-analysis','/api/session-signals','/api/release-impact','/api/global-macro','/api/release-state','/api/news','/api/fred/catalog']);
      const intel=basicPaths.has(url.pathname)?await getBasicIntelligence(env):null;
      if(url.pathname==='/api/health')return json({ok:true,app:'FXGA Macro Intelligence',dataService:'authenticated-primary-data-service',timestamp:new Date().toISOString(),configured:{calendarScraping:false,externalCollectorWebhook:Boolean(env.COLLECTOR_WEBHOOK_SECRET),calendarSources:['Primary calendar','Independent calendar cross-check','Market reference feed'],browserRun:false,durableCoordinator:Boolean(env.FXGA_COORDINATOR),officialNewsScraping:false},scheduler:{initialized:s.initialized,mode:'authenticated-live-updates',calendarSyncedAt:s.calendar?.generatedAt??null,nextReleaseAt:s.upcoming?.[0]?.event?.date??null,active:s.active,upcoming:s.upcoming,recent:s.recent,baseline:intel?.macroAnalysis?{generatedAt:intel.generatedAt,analysis:intel.macroAnalysis,observations}:null},safety:{workerSubrequestCeiling:0,collectorMaxConcurrentConnections:0,browserSoftBudgetSecondsPerUtcDay:0,browserSessionReuse:false,releaseMode:'scheduled release capture -> authenticated live update',normalStateUpstreamCalendarRequests:0,normalStateUpstreamFredRequests:0,normalStateUpstreamNewsRequests:0,normalStateUpstreamMarketRequests:0,releaseWindowPrimary:'primary data service',applicationEdgeRole:'receive authenticated updates, persist state, serve API/UI and live channel'}},{headers:{'Cache-Control':'no-store'}});
      if(url.pathname==='/api/sources')return json({sources:SOURCE_VIEW});
      if(url.pathname==='/api/dashboard'){const now=Date.now(),calendar=events.filter(e=>Date.parse(e.date)>=now-7*86400000).slice(0,600);return json({generatedAt:intel?.generatedAt??s.meta?.lastWebhookAt??new Date().toISOString(),macro:observations.slice(0,80),calendar,market:Array.isArray(s.market?.assets)?s.market.assets:[],news:intel?.news??[],sources:SOURCE_VIEW,errors:[]});}
      if(url.pathname==='/api/data-quality'){const macro=s.macro??{},quality=macro.coverageQuality??{},diag=macro.failureDiagnostics??{},marketAssets=Array.isArray(s.market?.assets)?s.market.assets:[];return json({generatedAt:macro.generatedAt??s.meta?.lastWebhookAt??null,macro:{coverage:quality,failures:{total:Number(diag.total??macro.failures?.length??0),retryable:Number(diag.retryable??0),nonRetryable:Number(diag.nonRetryable??0),unresolved:Number(diag.unresolved??Math.max(0,Number(macro.requested??0)-observations.length)),byType:diag.byType??{},byEconomy:diag.byEconomy??{},byCategory:diag.byCategory??{},series:(Array.isArray(macro.failures)?macro.failures:[]).slice(0,40).map((item:any)=>({seriesId:item.seriesId,title:item.title??item.seriesId,economy:item.economy??'UNKNOWN',category:item.category??'other',type:item.type??'other',retryable:Boolean(item.retryable)}))}},market:{assets:marketAssets.length,priced:marketAssets.filter((item:any)=>typeof item.price==='number'&&Number.isFinite(item.price)).length,stale:marketAssets.filter((item:any)=>item.stale).length},technical:{assets:Object.keys(s.technical?.assets??{}).length,confirmed:Number(s.technical?.counts?.confirmed??0),warming:Number(s.technical?.counts?.warming??0)},calendar:{events:events.length,sourceHealth:s.calendar?.sourceHealth??{}},publicPolicy:'Quality metrics describe coverage and freshness; unavailable evidence is never synthesized.'});}
      if(url.pathname==='/api/analysis')return intel?.macroAnalysis?json(intel.macroAnalysis):error('Analysis snapshot is not initialized',503);
      if(url.pathname==='/api/economy-analysis')return intel?.economyAnalysis?json(intel.economyAnalysis):error('Economy analysis is not initialized',503);
      if(url.pathname==='/api/session-signals'){if(!intel?.sessionSignals)return error('Currency outlook is not initialized',503);const technicalAssets=s.technical?.assets??{};const applyTechnical=(signal:any)=>{const technical=technicalAssets[String(signal?.symbol||'').toUpperCase()]??null;const gate=technical?.decisionGate??null;const macroDirection=String(signal?.direction||'WAIT').toUpperCase();const technicalAligned=gate?.status==='confirmed'&&((macroDirection==='BUY'&&gate.direction==='bullish')||(macroDirection==='SELL'&&gate.direction==='bearish'));return {...signal,technicalGate:gate?.status??'warming',technicalBias:gate?.direction??'neutral',technicalConfidence:Number(gate?.confidence??0),technicalModel:gate?.model??null,technicalReason:gate?.reason??'Awaiting verified price history.',executionGate:macroDirection==='WAIT'?'NO_DIRECTIONAL_EXECUTION':technicalAligned?'TECHNICAL_CONFIRMATION_PASSED':'AWAIT_TECHNICAL_CONFIRMATION'};};const sessions=(intel.sessionSignals.sessions??[]).map((session:any)=>({...session,signals:(session.signals??[]).map(applyTechnical)}));const rankedOpportunities=(intel.sessionSignals.rankedOpportunities??[]).map(applyTechnical);const rankedBySymbol=new Map(rankedOpportunities.map((item:any)=>[String(item.symbol||'').toUpperCase(),item]));const originalSummary=intel.sessionSignals.decisionSummary??{};const originalTop=originalSummary?.topOpportunity;const topOpportunity=originalTop?{...originalTop,...(rankedBySymbol.get(String(originalTop.symbol||'').toUpperCase())??{})}:rankedOpportunities[0]??null;const technicalExecutableCount=rankedOpportunities.filter((item:any)=>item.executionGate==='TECHNICAL_CONFIRMATION_PASSED').length;const macroCandidateCount=Number(originalSummary.actionableCount??rankedOpportunities.filter((item:any)=>String(item.direction||'WAIT')!=='WAIT').length);return json({...intel.sessionSignals,sessions,rankedOpportunities,decisionSummary:{...originalSummary,macroCandidateCount,technicalExecutableCount,actionableCount:technicalExecutableCount,topOpportunity},economyObservationCount:observations.length,technicalGeneratedAt:s.technical?.generatedAt??null});}
      if(url.pathname==='/api/release-impact')return intel?.releaseImpact?json(intel.releaseImpact):error('Release impact is not initialized',503);
      if(url.pathname==='/api/global-macro')return json(intel?.globalMacro??groupMacro(observations,s.macro?.generatedAt??null));
      if(url.pathname==='/api/market-prices')return json(s.market??{generatedAt:null,source:'CNBC',assets:[]});
      if(url.pathname==='/api/technical')return json(s.technical??{generatedAt:null,methodology:'evidence-gated-multi-timeframe-market-structure',counts:{assets:0,confirmed:0,contextAligned:0,conflict:0,warming:0},assets:{}});
      if(url.pathname==='/api/event-studies'){const days=Math.min(7,Math.max(1,Number(url.searchParams.get('days')||7))),currency=(url.searchParams.get('currency')||'').toUpperCase(),cutoff=Date.now()-days*86400000;let studies=Array.isArray(s.eventStudies?.studies)?s.eventStudies.studies:[];studies=studies.filter((study:any)=>Date.parse(study.releaseAt)>=cutoff&&(!currency||study.currency===currency));return json({generatedAt:s.eventStudies?.generatedAt??null,days,currency:currency||null,summary:s.eventStudies?.summary??{studies:studies.length,measuredHorizons:0,byHorizon:{}},studies});}
      if(url.pathname==='/api/technical-history'){const asset=(url.searchParams.get('asset')||'EURUSD').toUpperCase(),timeframe=(url.searchParams.get('timeframe')||'H1').toUpperCase();const item=s.technical?.assets?.[asset],frame=item?.timeframes?.[timeframe];return frame?json({generatedAt:s.technical?.generatedAt??null,asset,timeframe,bias:frame.bias,quality:frame.quality,history:frame.history??[]}):error('Technical history is not available for the requested asset/timeframe',404);}
      if(url.pathname==='/api/calendar-history'){const days=Math.min(7,Math.max(1,Number(url.searchParams.get('days')||7))),now=Date.now(),cutoff=now-days*86400000;return json({generatedAt:s.calendar?.generatedAt??null,days,events:events.filter(e=>{const time=Date.parse(e.date);return Number.isFinite(time)&&time<=now&&time>=cutoff;})});}
      if(url.pathname==='/api/release-state')return json({initialized:s.initialized,mode:publicMode(),calendarSources:['Myfxbook','FXStreet','CNBC'],calendarSyncedAt:s.calendar?.generatedAt??null,nextReleaseAt:s.upcoming?.[0]?.event?.date??null,nextAlarmAt:null,active:s.active,upcoming:s.upcoming,recent:s.recent,baseline:intel?.macroAnalysis?{generatedAt:intel.generatedAt,analysis:intel.macroAnalysis,observations}:null,stats:{upstreamCalendarRequestsFromApplicationEdge:0,upstreamMacroRequestsFromApplicationEdge:0,upstreamNewsRequestsFromApplicationEdge:0,authenticatedUpdates:s.meta?.updates??0}});
      if(url.pathname==='/api/release-history'){const id=url.searchParams.get('id')?.trim()??'';if(!id)return error('id is required');return coordinator(env).fetch(`https://fxga-coordinator.internal/release?id=${encodeURIComponent(id)}`);}
      if(url.pathname==='/api/calendar'){const days=Math.min(31,Math.max(1,Number(url.searchParams.get('days')||7))),importance=Math.min(3,Math.max(1,Number(url.searchParams.get('importance')||1))),cutoff=Date.now()+days*86400000;return json({events:events.filter(e=>Number(e.importance??1)>=importance&&Date.parse(e.date)<=cutoff).sort((a,b)=>Date.parse(a.date)-Date.parse(b.date)),cached:true,mode:publicMode(),calendarSources:['Primary calendar','Independent calendar cross-check','Market reference feed'],calendarSyncedAt:s.calendar?.generatedAt??null});}
      if(url.pathname==='/api/news')return json({items:Array.isArray(intel?.news)?intel.news:[],mode:publicMode()});
      if(url.pathname==='/api/fred/catalog')return intel?.fredCatalog?json(intel.fredCatalog):json({total:observations.length,series:observations.map((x:MacroObservation)=>({id:x.seriesId,title:x.title,units:x.units,frequency:x.frequency,categories:x.categories})),categories:[],policy:{importantOnly:true,scope:'persisted primary-source macro data'}});
      if(url.pathname==='/api/fred'){const series=filterMacro(observations,url);return json({series,selection:{cachedOnly:true,source:'verified persisted macro state',count:series.length}});}
      if(url.pathname==='/api/acquisition/catalog')return json({methods:[],sources:SOURCE_VIEW,status:{websocketClients:0,inFlightSources:0,browserBudget:{dayUtc:new Date().toISOString().slice(0,10),usedSeconds:0,softLimitSeconds:0,remainingSeconds:0,browserSessionReuse:false,reason:'Acquisition is isolated to the primary data service',nextLaunchAllowedAt:null},sources:SOURCE_VIEW.length},limits:{externalSubrequestsPerInvocation:0,simultaneousOutgoingConnections:0,collectorMaxConcurrentConnections:0,browserSoftBudgetSecondsPerUtcDay:0,browserConcurrentJobsInFxga:0,minBrowserLaunchGapSeconds:0},policy:{publicPagesOnly:true,robotsAware:true,bypassLogin:false,bypassCaptcha:false,bypassPaywall:false,botEvasion:false,applicationEdgeAcquisitionDisabled:true}});
      if(url.pathname==='/api/acquire')return error('Direct acquisition is disabled on the application edge. The primary data service owns acquisition.',409);
      return error('API route not found',404);
    }catch(e){return error(e instanceof Error?e.message:'Passive webhook state unavailable',503);}
  },
  async scheduled(_controller:ScheduledController,_env:Env,_ctx:ExecutionContext){return;},
};
